import lunarPackage from "lunar-javascript";
import { astro } from "iztro";
import type { AstroConsultationPayload } from "./AstroConsultationFlow";

export type PlanetPosition={name:string;symbol:string;longitude:number;latitude:number;speed:number;retrograde:boolean;sign:number;degree:number;house:number};
export type Aspect={from:string;to:string;type:string;angle:number;orb:number};
export type WesternCalculation={planets:PlanetPosition[];houses:number[];ascendant:number;mc:number;aspects:Aspect[];transits:PlanetPosition[];transitAspects:Aspect[];solarReturn:string;solarReturnPlanets:PlanetPosition[];solarReturnHouses:number[];solarReturnAspects:Aspect[];solarReturnAscendant:number;solarReturnMc:number;age:number;targetDate:string};
export type BaziPillar={key:"year"|"month"|"day"|"hour";ganZhi:string;wuXing:string;tenGod:string;hidden:string[];naYin:string};
export type BaziCalculation={lunarDate:string;pillars:BaziPillar[];dayMaster:string;dayElement:string;dayPolarity:string;elements:Record<string,number>;mingGong:string;shenGong:string;luckStart:string;luckCycles:{ganZhi:string;startYear:number;endYear:number;startAge:number;endAge:number}[];currentLuck?:{ganZhi:string;startYear:number;endYear:number;startAge:number;endAge:number}};
export type ZiWeiPalace={index:number;name:string;stem:string;branch:string;isBody:boolean;isOrigin:boolean;majorStars:{name:string;brightness:string;mutagen?:string}[];minorStars:string[];adjectiveStars?:string[];decadal:[number,number]};
export type ZiWeiCalculation={lunarDate:string;chineseDate:string;time:string;zodiac:string;soul:string;body:string;fiveElementsClass:string;palaces:ZiWeiPalace[];current:{nominalAge:number;decadalPalace:string;yearlyPalace:string;yearStemBranch:string}};
export type NumerologyCalculation={life:number;expression:number;soul:number;personality:number;maturity:number;birthday:number;attitude:number;balance:number;hiddenPassion:number;subconsciousSelf:number;karmicLessons:number[];cornerstone:number;capstone:number;firstVowel:number;year:number;month:number;day:number;pinnacles:number[];pinnaclePeriods:string[];challenges:number[];lifeCycles:number[];karmicDebts:number[]};
export type FullAstroCalculation={western?:WesternCalculation;bazi?:BaziCalculation;ziwei?:ZiWeiCalculation;numerology:NumerologyCalculation};

const {Solar}=lunarPackage as unknown as {Solar:{fromYmdHms:(year:number,month:number,day:number,hour:number,minute:number,second:number)=>any}};
const elements:Record<string,string>={甲:"Madera",乙:"Madera",丙:"Fuego",丁:"Fuego",戊:"Tierra",己:"Tierra",庚:"Metal",辛:"Metal",壬:"Agua",癸:"Agua",寅:"Madera",卯:"Madera",巳:"Fuego",午:"Fuego",辰:"Tierra",戌:"Tierra",丑:"Tierra",未:"Tierra",申:"Metal",酉:"Metal",亥:"Agua",子:"Agua"};
const yinYang:Record<string,string>={甲:"Yang",乙:"Yin",丙:"Yang",丁:"Yin",戊:"Yang",己:"Yin",庚:"Yang",辛:"Yin",壬:"Yang",癸:"Yin"};
const coords:Record<string,{latitude:number;longitude:number}>={"Ciudad de México, México":{latitude:19.4326,longitude:-99.1332},"Mexico City, México":{latitude:19.4326,longitude:-99.1332}};
const planetDefs=[
  {id:0,name:"Sun",symbol:"☉"},{id:1,name:"Moon",symbol:"☽"},{id:2,name:"Mercury",symbol:"☿"},{id:3,name:"Venus",symbol:"♀"},{id:4,name:"Mars",symbol:"♂"},{id:5,name:"Jupiter",symbol:"♃"},{id:6,name:"Saturn",symbol:"♄"},{id:7,name:"Uranus",symbol:"♅"},{id:8,name:"Neptune",symbol:"♆"},{id:9,name:"Pluto",symbol:"♇"},{id:11,name:"North Node",symbol:"☊"},
];
const aspectDefs=[{type:"conjunction",angle:0,orb:8},{type:"sextile",angle:60,orb:5},{type:"square",angle:90,orb:7},{type:"trine",angle:120,orb:7},{type:"opposition",angle:180,orb:8}];
const mod=(value:number,base=360)=>((value%base)+base)%base;
const signedAngle=(a:number,b:number)=>mod(a-b+180)-180;
const reduce=(value:number)=>{let result=value;while(result>9&&![11,22,33].includes(result))result=String(result).split("").reduce((sum,digit)=>sum+Number(digit),0);return result};
const letterValue=(letter:string)=>((letter.charCodeAt(0)-65)%9)+1;

function zonedDate(date:string,time:string,timeZone:string){
  const [year,month,day]=date.split("-").map(Number);const [hour,minute]=time.split(":").map(Number);const desired=Date.UTC(year,month-1,day,hour,minute);let guess=desired;
  const formatter=new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"});
  for(let index=0;index<3;index++){const p=Object.fromEntries(formatter.formatToParts(new Date(guess)).map(part=>[part.type,part.value]));const represented=Date.UTC(Number(p.year),Number(p.month)-1,Number(p.day),Number(p.hour),Number(p.minute));guess+=desired-represented}
  return new Date(guess);
}

function houseOf(longitude:number,cusps:number[]){
  const list=cusps.length>=13?cusps.slice(1,13):cusps.slice(0,12);
  for(let index=0;index<12;index++){const start=mod(list[index]);const end=mod(list[(index+1)%12]);const span=mod(end-start);if(mod(longitude-start)<span)return index+1}return 1;
}

function aspectsBetween(first:PlanetPosition[],second:PlanetPosition[],transit=false){
  const found:Aspect[]=[];first.forEach((a,index)=>second.forEach((b,j)=>{if(!transit&&j<=index)return;const separation=Math.abs(signedAngle(a.longitude,b.longitude));aspectDefs.forEach(def=>{const orb=transit?Math.min(def.orb,3):def.orb;const delta=Math.abs(separation-def.angle);if(delta<=orb)found.push({from:a.name,to:b.name,type:def.type,angle:def.angle,orb:Number(delta.toFixed(2))})})}));return found.sort((a,b)=>a.orb-b.orb);
}

function planetList(swe:any,jd:number,cusps:number[]):PlanetPosition[]{return planetDefs.map(def=>{const p=swe.calculatePosition(jd,def.id);return{name:def.name,symbol:def.symbol,longitude:p.longitude,latitude:p.latitude,speed:p.longitudeSpeed,retrograde:p.longitudeSpeed<0,sign:Math.floor(mod(p.longitude)/30),degree:mod(p.longitude,30),house:houseOf(p.longitude,cusps)}})}

async function western(payload:AstroConsultationPayload):Promise<WesternCalculation>{
  const {SwissEphemeris,HouseSystem}=await import("@swisseph/browser");const swe=new SwissEphemeris();await swe.init();
  try{
    const location=coords[payload.birthPlace||""]||coords["Ciudad de México, México"];
    const birth=zonedDate(payload.birthDate,payload.birthTime||"12:00",payload.timezone||"America/Mexico_City");const birthJd=swe.dateToJulianDay(birth);const houseData=swe.calculateHouses(birthJd,location.latitude,location.longitude,HouseSystem.Placidus);const planets=planetList(swe,birthJd,houseData.cusps);
    const targetDate=payload.targetDate||new Date().toISOString().slice(0,10);const target=zonedDate(targetDate,"12:00",payload.timezone||"America/Mexico_City");const targetJd=swe.dateToJulianDay(target);const targetHouses=swe.calculateHouses(targetJd,location.latitude,location.longitude,HouseSystem.Placidus);const transits=planetList(swe,targetJd,targetHouses.cusps);
    const birthYear=Number(payload.birthDate.slice(0,4));const targetYear=Number(targetDate.slice(0,4));const sunLongitude=planets[0].longitude;const [,birthMonth,birthDay]=payload.birthDate.split("-").map(Number);let low=swe.julianDay(targetYear,birthMonth,birthDay,-48);let high=swe.julianDay(targetYear,birthMonth,birthDay,72);for(let i=0;i<42;i++){const mid=(low+high)/2;const diff=signedAngle(swe.calculatePosition(mid,0).longitude,sunLongitude);if(diff<0)low=mid;else high=mid}const returnJd=(low+high)/2;const returnDate=swe.julianDayToDate(returnJd);const returnHouses=swe.calculateHouses(returnJd,location.latitude,location.longitude,HouseSystem.Placidus);const solarReturnPlanets=planetList(swe,returnJd,returnHouses.cusps);
    return{planets,houses:(houseData.cusps.length>=13?houseData.cusps.slice(1,13):houseData.cusps.slice(0,12)),ascendant:houseData.ascendant,mc:houseData.mc,aspects:aspectsBetween(planets,planets),transits,transitAspects:aspectsBetween(transits,planets,true),solarReturn:`${returnDate.year}-${String(returnDate.month).padStart(2,"0")}-${String(returnDate.day).padStart(2,"0")} ${String(Math.floor(returnDate.hour)).padStart(2,"0")}:${String(Math.round((returnDate.hour%1)*60)).padStart(2,"0")} UTC`,solarReturnPlanets,solarReturnHouses:(returnHouses.cusps.length>=13?returnHouses.cusps.slice(1,13):returnHouses.cusps.slice(0,12)),solarReturnAspects:aspectsBetween(solarReturnPlanets,solarReturnPlanets),solarReturnAscendant:returnHouses.ascendant,solarReturnMc:returnHouses.mc,age:targetYear-birthYear-(targetDate.slice(5)<payload.birthDate.slice(5)?1:0),targetDate};
  }finally{swe.close()}
}

function numerology(payload:AstroConsultationPayload):NumerologyCalculation{
  const rawName=(payload.birthName||payload.name).normalize("NFD").replace(/[^a-z\s]/gi,"").toUpperCase().trim();const name=rawName.replace(/\s/g,"");const words=rawName.split(/\s+/).filter(Boolean);const vowels=new Set(["A","E","I","O","U"]);const [year,month,day]=payload.birthDate.split("-").map(Number);const target=(payload.targetDate||new Date().toISOString().slice(0,10)).split("-").map(Number);const lifeRaw=String(year)+String(month).padStart(2,"0")+String(day).padStart(2,"0");const lifeTotal=[...lifeRaw].reduce((a,b)=>a+Number(b),0);const values=[...name].map(letterValue);const expressionTotal=values.reduce((a,b)=>a+b,0);const soulTotal=[...name].filter(c=>vowels.has(c)).reduce((a,b)=>a+letterValue(b),0);const personalityTotal=[...name].filter(c=>!vowels.has(c)).reduce((a,b)=>a+letterValue(b),0);const life=reduce(lifeTotal);const expression=reduce(expressionTotal);const personalYear=reduce(reduce(day)+reduce(month)+reduce(target[0]));const personalMonth=reduce(personalYear+target[1]);const personalDay=reduce(personalMonth+target[2]);const m=reduce(month),d=reduce(day),y=reduce(year);const p1=reduce(m+d),p2=reduce(d+y);const frequency=values.reduce<Record<number,number>>((acc,value)=>(acc[value]=(acc[value]||0)+1,acc),{});const hiddenPassion=Number(Object.entries(frequency).sort((a,b)=>b[1]-a[1]||Number(a[0])-Number(b[0]))[0]?.[0]||0);const distinct=new Set(values);const firstEnd=36-life;const debts=[lifeTotal,expressionTotal,soulTotal,personalityTotal].filter(value=>[13,14,16,19].includes(value));return{life,expression,soul:reduce(soulTotal),personality:reduce(personalityTotal),maturity:reduce(life+expression),birthday:reduce(day),attitude:reduce(month+day),balance:reduce(words.reduce((sum,word)=>sum+letterValue(word[0]),0)),hiddenPassion,subconsciousSelf:distinct.size,karmicLessons:Array.from({length:9},(_,i)=>i+1).filter(value=>!distinct.has(value)),cornerstone:letterValue(name[0]),capstone:letterValue(name[name.length-1]),firstVowel:letterValue([...name].find(c=>vowels.has(c))||"A"),year:personalYear,month:personalMonth,day:personalDay,pinnacles:[p1,p2,reduce(p1+p2),reduce(m+y)],pinnaclePeriods:[`0–${firstEnd}`,`${firstEnd+1}–${firstEnd+9}`,`${firstEnd+10}–${firstEnd+18}`,`${firstEnd+19}+`],challenges:[Math.abs(m-d),Math.abs(d-y),Math.abs(Math.abs(m-d)-Math.abs(d-y)),Math.abs(m-y)],lifeCycles:[m,d,y],karmicDebts:[...new Set(debts)]};
}

function eastern(payload:AstroConsultationPayload):{bazi:BaziCalculation;ziwei:ZiWeiCalculation}{
  const [year,month,day]=payload.birthDate.split("-").map(Number);const [hour,minute]=String(payload.birthTime||"12:00").split(":").map(Number);const lunar=Solar.fromYmdHms(year,month,day,hour,minute,0).getLunar();const chart=lunar.getEightChar();const pillarKeys=["Year","Month","Day","Time"] as const;const keys=["year","month","day","hour"] as const;const pillars:BaziPillar[]=pillarKeys.map((key,index)=>({key:keys[index],ganZhi:chart[`get${key}`](),wuXing:chart[`get${key}WuXing`](),tenGod:chart[`get${key}ShiShenGan`](),hidden:chart[`get${key}HideGan`](),naYin:chart[`get${key}NaYin`]()}));const counts:Record<string,number>={Madera:0,Fuego:0,Tierra:0,Metal:0,Agua:0};pillars.forEach(p=>[...p.ganZhi].forEach(char=>{const element=elements[char];if(element)counts[element]++}));const yun=chart.getYun(payload.gender==="male"?1:0);const luckCycles=yun.getDaYun().slice(1,9).map((cycle:any)=>({ganZhi:cycle.getGanZhi(),startYear:cycle.getStartYear(),endYear:cycle.getEndYear(),startAge:cycle.getStartAge(),endAge:cycle.getEndAge()}));const bazi:BaziCalculation={lunarDate:lunar.toString(),pillars,dayMaster:pillars[2].ganZhi[0],dayElement:elements[pillars[2].ganZhi[0]],dayPolarity:yinYang[pillars[2].ganZhi[0]],elements:counts,mingGong:chart.getMingGong(),shenGong:chart.getShenGong(),luckStart:yun.getStartSolar().toYmd(),luckCycles};
  bazi.currentLuck=luckCycles.find(c=>Number(payload.targetDate?.slice(0,4)||new Date().getFullYear())>=c.startYear&&Number(payload.targetDate?.slice(0,4)||new Date().getFullYear())<=c.endYear);
  const timeIndex=Math.floor((hour+1)/2)%12;const a:any=astro.astrolabeBySolarDate(`${year}-${month}-${day}`,timeIndex,payload.gender==="female"?"female":"male",true,"en-US");const target=String(payload.targetDate||new Date().toISOString().slice(0,10));const horoscope:any=a.horoscope(target);const palaces:ZiWeiPalace[]=a.palaces.map((p:any)=>({index:p.index,name:p.name,stem:p.heavenlyStem,branch:p.earthlyBranch,isBody:p.isBodyPalace,isOrigin:p.isOriginalPalace,majorStars:p.majorStars.map((s:any)=>({name:s.name,brightness:s.brightness||"",mutagen:s.mutagen})),minorStars:p.minorStars.map((s:any)=>s.name),decadal:p.decadal.range as [number,number]}));const ziwei:ZiWeiCalculation={lunarDate:a.lunarDate,chineseDate:a.chineseDate,time:a.time,zodiac:a.zodiac,soul:a.soul,body:a.body,fiveElementsClass:a.fiveElementsClass,palaces,current:{nominalAge:horoscope.age.nominalAge,decadalPalace:horoscope.decadal.palaceNames[0]||"",yearlyPalace:horoscope.yearly.palaceNames[0]||"",yearStemBranch:`${horoscope.yearly.heavenlyStem} ${horoscope.yearly.earthlyBranch}`}};return{bazi,ziwei};
}

export async function calculateAllAstros(payload:AstroConsultationPayload):Promise<FullAstroCalculation>{const nums=numerology(payload);if(payload.discipline==="western")return{numerology:nums,western:await western(payload)};if(payload.discipline==="eastern")return{numerology:nums,...eastern(payload)};return{numerology:nums};}
