"use client";

import { useEffect, useState } from "react";
import type { Language } from "../translations";
import { DisciplineLibrary, type DisciplineLibraryItem } from "./DisciplineLibrary";
import "./astrology-sites.css";
import "./astrology-card-colors.css";
import "./astrology-introduction.css";

type AstrologyBranch = "western" | "eastern";
type AstrologySiteProps = { branch: AstrologyBranch; lang: Language; onBack: () => void };
type Focus = { symbol: string; title: string; level: string; description: string };
type SiteCopy = { back: string; eyebrow: string; title: string; subtitle: string; introduction: string; choose: string; pending: string; pendingDescription: string; focuses: Focus[] };
type IntroSection = { title: string; paragraphs: string[] };

const content: Record<Language, Record<AstrologyBranch, SiteCopy>> = {
  ES: {
    western: { back: "Volver al inicio", eyebrow: "CIELO · CICLOS · EXPERIENCIA", title: "Astrología Occidental", subtitle: "Del mapa natal al movimiento del cielo", introduction: "La Carta Natal es el mapa raíz. Los tránsitos observan el presente, la Revolución Solar estudia el ciclo anual y los horóscopos ofrecen una orientación general por signo solar o ascendente.", choose: "Elige el enfoque", pending: "MÓDULO PENDIENTE", pendingDescription: "La interfaz del cálculo y la interpretación se desarrollará en la siguiente etapa.", focuses: [
      { symbol: "◎", title: "Carta Natal", level: "Raíz · Estática", description: "Mapa del cielo al nacer: base psicológica y predictiva del sistema occidental." },
      { symbol: "☍", title: "Tránsitos Astrológicos", level: "Dinámica · Actual", description: "Movimiento planetario actual en relación con la Carta Natal." },
      { symbol: "☀", title: "Revolución Solar", level: "Cíclica · Anual", description: "Carta calculada para el retorno exacto del Sol, de cumpleaños a cumpleaños." },
      { symbol: "✦", title: "Horóscopos", level: "Día · Semana · Mes", description: "Orientaciones generales basadas en el signo solar o el ascendente." },
    ] },
    eastern: { back: "Volver al inicio", eyebrow: "DESTINO · ELEMENTOS · EQUILIBRIO", title: "Astrología Oriental", subtitle: "Estructura natal y cosmología china", introduction: "BaZi —los Cuatro Pilares del Destino— ocupa el lugar estructural de la Carta Natal occidental. Los animales, los cinco elementos y las polaridades Yin/Yang no son categorías aisladas: forman el alfabeto con el que se construyen e interpretan los pilares.", choose: "Elige el enfoque", pending: "MÓDULO PENDIENTE", pendingDescription: "La interfaz del cálculo y la interpretación se desarrollará en la siguiente etapa.", focuses: [
      { symbol: "八", title: "BaZi · Cuatro Pilares", level: "Estructural · Natal", description: "Año, mes, día y hora expresados mediante Troncos Celestes y Ramas Terrestres." },
      { symbol: "陰", title: "Animales, elementos y polaridades", level: "Cosmología base", description: "Doce animales, cinco elementos y Yin/Yang: los bloques fundamentales que componen el BaZi." },
      { symbol: "紫", title: "Zi Wei Dou Shu", level: "Estelar · Destino", description: "Sistema avanzado basado en más de cien estrellas distribuidas en un mapa de doce palacios." },
    ] },
  },
  EN: {
    western: { back: "Back to home", eyebrow: "SKY · CYCLES · EXPERIENCE", title: "Western Astrology", subtitle: "From the natal map to the moving sky", introduction: "The Natal Chart is the root map. Transits observe the present, the Solar Return studies the annual cycle, and horoscopes offer general guidance by sun sign or rising sign.", choose: "Choose a focus", pending: "MODULE PENDING", pendingDescription: "The calculation and interpretation interface will be developed in the next stage.", focuses: [
      { symbol: "◎", title: "Natal Chart", level: "Root · Static", description: "A map of the sky at birth: the psychological and predictive foundation of Western astrology." },
      { symbol: "☍", title: "Astrological Transits", level: "Dynamic · Current", description: "Current planetary movement in relation to the Natal Chart." },
      { symbol: "☀", title: "Solar Return", level: "Cyclical · Annual", description: "A chart calculated for the Sun’s exact return, from birthday to birthday." },
      { symbol: "✦", title: "Horoscopes", level: "Day · Week · Month", description: "General guidance based on the sun sign or rising sign." },
    ] },
    eastern: { back: "Back to home", eyebrow: "DESTINY · ELEMENTS · BALANCE", title: "Eastern Astrology", subtitle: "Natal structure and Chinese cosmology", introduction: "BaZi—the Four Pillars of Destiny—holds the structural place of the Western Natal Chart. Animals, the five elements, and Yin/Yang polarities are not separate categories: they form the alphabet used to build and interpret the pillars.", choose: "Choose a focus", pending: "MODULE PENDING", pendingDescription: "The calculation and interpretation interface will be developed in the next stage.", focuses: [
      { symbol: "八", title: "BaZi · Four Pillars", level: "Structural · Natal", description: "Year, month, day, and hour expressed through Heavenly Stems and Earthly Branches." },
      { symbol: "陰", title: "Animals, elements, and polarities", level: "Core cosmology", description: "Twelve animals, five elements, and Yin/Yang: the fundamental building blocks of BaZi." },
      { symbol: "紫", title: "Zi Wei Dou Shu", level: "Stellar · Destiny", description: "An advanced system using more than one hundred stars across a twelve-palace chart." },
    ] },
  },
  FR: {
    western: { back: "Retour à l’accueil", eyebrow: "CIEL · CYCLES · EXPÉRIENCE", title: "Astrologie Occidentale", subtitle: "De la carte natale au mouvement du ciel", introduction: "La Carte Natale est la carte racine. Les transits observent le présent, la Révolution Solaire étudie le cycle annuel et les horoscopes proposent une orientation générale selon le signe solaire ou l’ascendant.", choose: "Choisissez l’approche", pending: "MODULE EN ATTENTE", pendingDescription: "L’interface de calcul et d’interprétation sera développée lors de la prochaine étape.", focuses: [
      { symbol: "◎", title: "Carte Natale", level: "Racine · Statique", description: "Carte du ciel à la naissance : fondement psychologique et prédictif de l’astrologie occidentale." },
      { symbol: "☍", title: "Transits Astrologiques", level: "Dynamique · Actuel", description: "Mouvement planétaire actuel en relation avec la Carte Natale." },
      { symbol: "☀", title: "Révolution Solaire", level: "Cyclique · Annuel", description: "Carte calculée pour le retour exact du Soleil, d’un anniversaire à l’autre." },
      { symbol: "✦", title: "Horoscopes", level: "Jour · Semaine · Mois", description: "Orientations générales fondées sur le signe solaire ou l’ascendant." },
    ] },
    eastern: { back: "Retour à l’accueil", eyebrow: "DESTIN · ÉLÉMENTS · ÉQUILIBRE", title: "Astrologie Orientale", subtitle: "Structure natale et cosmologie chinoise", introduction: "Le BaZi —les Quatre Piliers du Destin— occupe la place structurelle de la Carte Natale occidentale. Les animaux, les cinq éléments et les polarités Yin/Yang ne sont pas des catégories séparées : ils forment l’alphabet qui compose et interprète les piliers.", choose: "Choisissez l’approche", pending: "MODULE EN ATTENTE", pendingDescription: "L’interface de calcul et d’interprétation sera développée lors de la prochaine étape.", focuses: [
      { symbol: "八", title: "BaZi · Quatre Piliers", level: "Structurel · Natal", description: "Année, mois, jour et heure exprimés par les Troncs Célestes et les Branches Terrestres." },
      { symbol: "陰", title: "Animaux, éléments et polarités", level: "Cosmologie fondamentale", description: "Douze animaux, cinq éléments et Yin/Yang : les composants fondamentaux du BaZi." },
      { symbol: "紫", title: "Zi Wei Dou Shu", level: "Stellaire · Destin", description: "Système avancé fondé sur plus de cent étoiles dans une carte de douze palais." },
    ] },
  },
  DE: {
    western: { back: "Zurück zum Anfang", eyebrow: "HIMMEL · ZYKLEN · ERFAHRUNG", title: "Westliche Astrologie", subtitle: "Von der Geburtskarte zum bewegten Himmel", introduction: "Die Geburtskarte ist die Wurzelkarte. Transite betrachten die Gegenwart, die Solarrevolution untersucht den Jahreszyklus und Horoskope bieten allgemeine Orientierung nach Sonnenzeichen oder Aszendent.", choose: "Schwerpunkt wählen", pending: "MODUL AUSSTEHEND", pendingDescription: "Die Oberfläche für Berechnung und Deutung wird in der nächsten Phase entwickelt.", focuses: [
      { symbol: "◎", title: "Geburtskarte", level: "Wurzel · Statisch", description: "Karte des Himmels bei der Geburt: psychologische und prognostische Grundlage der westlichen Astrologie." },
      { symbol: "☍", title: "Astrologische Transite", level: "Dynamisch · Aktuell", description: "Aktuelle Planetenbewegungen in Beziehung zur Geburtskarte." },
      { symbol: "☀", title: "Solarrevolution", level: "Zyklisch · Jährlich", description: "Für die exakte Sonnenwiederkehr berechnete Karte, von Geburtstag zu Geburtstag." },
      { symbol: "✦", title: "Horoskope", level: "Tag · Woche · Monat", description: "Allgemeine Orientierung nach Sonnenzeichen oder Aszendent." },
    ] },
    eastern: { back: "Zurück zum Anfang", eyebrow: "SCHICKSAL · ELEMENTE · GLEICHGEWICHT", title: "Östliche Astrologie", subtitle: "Geburtsstruktur und chinesische Kosmologie", introduction: "BaZi —die Vier Säulen des Schicksals— nimmt strukturell den Platz der westlichen Geburtskarte ein. Tiere, fünf Elemente und Yin/Yang-Polaritäten sind keine getrennten Kategorien: Sie bilden das Alphabet, aus dem die Säulen aufgebaut und gedeutet werden.", choose: "Schwerpunkt wählen", pending: "MODUL AUSSTEHEND", pendingDescription: "Die Oberfläche für Berechnung und Deutung wird in der nächsten Phase entwickelt.", focuses: [
      { symbol: "八", title: "BaZi · Vier Säulen", level: "Strukturell · Geburt", description: "Jahr, Monat, Tag und Stunde durch Himmelsstämme und Erdzweige ausgedrückt." },
      { symbol: "陰", title: "Tiere, Elemente und Polaritäten", level: "Grundkosmologie", description: "Zwölf Tiere, fünf Elemente und Yin/Yang: die grundlegenden Bausteine des BaZi." },
      { symbol: "紫", title: "Zi Wei Dou Shu", level: "Stellar · Schicksal", description: "Fortgeschrittenes System mit mehr als hundert Sternen in einer Karte aus zwölf Palästen." },
    ] },
  },
  PT: {
    western: { back: "Voltar ao início", eyebrow: "CÉU · CICLOS · EXPERIÊNCIA", title: "Astrologia Ocidental", subtitle: "Do mapa natal ao movimento do céu", introduction: "O Mapa Natal é o mapa raiz. Os trânsitos observam o presente, a Revolução Solar estuda o ciclo anual e os horóscopos oferecem orientação geral pelo signo solar ou ascendente.", choose: "Escolha o enfoque", pending: "MÓDULO PENDENTE", pendingDescription: "A interface de cálculo e interpretação será desenvolvida na próxima etapa.", focuses: [
      { symbol: "◎", title: "Mapa Natal", level: "Raiz · Estático", description: "Mapa do céu no nascimento: base psicológica e preditiva da astrologia ocidental." },
      { symbol: "☍", title: "Trânsitos Astrológicos", level: "Dinâmico · Atual", description: "Movimento planetário atual em relação ao Mapa Natal." },
      { symbol: "☀", title: "Revolução Solar", level: "Cíclico · Anual", description: "Mapa calculado para o retorno exato do Sol, de aniversário a aniversário." },
      { symbol: "✦", title: "Horóscopos", level: "Dia · Semana · Mês", description: "Orientações gerais baseadas no signo solar ou ascendente." },
    ] },
    eastern: { back: "Voltar ao início", eyebrow: "DESTINO · ELEMENTOS · EQUILÍBRIO", title: "Astrologia Oriental", subtitle: "Estrutura natal e cosmologia chinesa", introduction: "BaZi —os Quatro Pilares do Destino— ocupa o lugar estrutural do Mapa Natal ocidental. Os animais, os cinco elementos e as polaridades Yin/Yang não são categorias separadas: formam o alfabeto usado para compor e interpretar os pilares.", choose: "Escolha o enfoque", pending: "MÓDULO PENDENTE", pendingDescription: "A interface de cálculo e interpretação será desenvolvida na próxima etapa.", focuses: [
      { symbol: "八", title: "BaZi · Quatro Pilares", level: "Estrutural · Natal", description: "Ano, mês, dia e hora expressos por Troncos Celestes e Ramos Terrestres." },
      { symbol: "陰", title: "Animais, elementos e polaridades", level: "Cosmologia básica", description: "Doze animais, cinco elementos e Yin/Yang: os blocos fundamentais que compõem o BaZi." },
      { symbol: "紫", title: "Zi Wei Dou Shu", level: "Estelar · Destino", description: "Sistema avançado baseado em mais de cem estrelas em um mapa de doze palácios." },
    ] },
  },
};

const westernIntroductions: Record<Language, IntroSection[]> = {
  ES: [
    { title: "Historia y contexto", paragraphs: ["La astrología occidental tiene sus raíces en la antigua Mesopotamia. En Babilonia y Asiria, aproximadamente desde el segundo milenio a. C., los sacerdotes observaban los ciclos celestes para relacionarlos con acontecimientos colectivos como el clima, las cosechas, las guerras y el destino de los reinos.", "Entre los siglos II a. C. y II d. C., esta tradición se encontró en Alejandría con la filosofía griega y la geometría egipcia. De esa integración surgió la astrología genetlíaca: un sistema centrado en el individuo y en la Carta Natal como representación del cielo en el momento exacto del nacimiento.", "En el siglo II d. C., Claudio Ptolomeo organizó buena parte de sus fundamentos técnicos en el Tetrabiblos. Durante el Renacimiento, astrología y astronomía todavía convivían en un mismo campo de estudio; figuras como Johannes Kepler practicaron ambas disciplinas.", "Su cosmovisión se apoya en el principio hermético de correspondencia —«como es arriba, es abajo»— y comprende los ciclos planetarios y zodiacales como un lenguaje simbólico. El cielo no determina un destino inamovible: ofrece un mapa de arquetipos, potenciales, tensiones psicológicas y tendencias temporales que deben interpretarse en conjunto."] },
    { title: "Forma de consulta", paragraphs: ["Una consulta astrológica occidental no se basa en un signo, planeta o aspecto aislado. La Carta Natal constituye la raíz estructural: registra las coordenadas celestes de la fecha, hora y lugar de nacimiento para estudiar la personalidad, los potenciales, los bloqueos y las dinámicas psicológicas internas.", "Los Tránsitos y las Progresiones aportan la dimensión dinámica al comparar el movimiento planetario de un periodo con la Carta Natal. La Revolución Solar completa la dimensión cíclica anual: se calcula para el instante exacto en que el Sol regresa a su posición natal y permite observar los temas predominantes desde un cumpleaños hasta el siguiente."] },
    { title: "Clave para la interpretación", paragraphs: ["La Carta Natal debe utilizarse como estructura base. Para obtener una lectura clara y evitar interpretaciones saturadas, conviene contrastar los tránsitos actuales con sus puntos más sensibles: el Ascendente, el Sol, la Luna y los regentes de las casas relacionadas con la consulta.", "La astrología organiza ciclos y correspondencias; la intuición permite reconocer cuáles de esos símbolos resuenan de manera significativa en la experiencia de la persona. Ambas deben trabajar juntas, sin convertir las tendencias observadas en afirmaciones absolutas."] },
  ],
  EN: [
    { title: "History and context", paragraphs: ["Western astrology has its roots in ancient Mesopotamia. In Babylonia and Assyria, from approximately the second millennium BCE, priests observed celestial cycles and related them to collective events such as weather, harvests, wars, and the fate of kingdoms.", "Between the second century BCE and the second century CE, this tradition met Greek philosophy and Egyptian geometry in Alexandria. Their integration gave rise to natal astrology: a system focused on the individual and the Natal Chart as a representation of the sky at the exact moment of birth.", "In the second century CE, Claudius Ptolemy organized many of its technical foundations in the Tetrabiblos. During the Renaissance, astrology and astronomy still shared a field of study; figures such as Johannes Kepler practiced both.", "Its worldview draws on the Hermetic principle of correspondence—‘as above, so below’—and understands planetary and zodiacal cycles as a symbolic language. The sky does not determine an unchangeable fate: it offers a map of archetypes, potentials, psychological tensions, and temporal tendencies that must be interpreted together."] },
    { title: "Consultation structure", paragraphs: ["A Western astrology consultation is not based on an isolated sign, planet, or aspect. The Natal Chart is the structural root: it records the celestial coordinates for the date, time, and place of birth to study personality, potential, blocks, and inner psychological dynamics.", "Transits and Progressions provide the dynamic dimension by comparing planetary movement during a given period with the Natal Chart. The Solar Return completes the annual cyclical dimension: it is calculated for the exact instant the Sun returns to its natal position and reveals the prevailing themes from one birthday to the next."] },
    { title: "Key to interpretation", paragraphs: ["The Natal Chart should be used as the foundation of every analysis. For a clear reading without interpretive overload, current transits should be compared with its most sensitive points: the Ascendant, Sun, Moon, and rulers of the houses connected with the consultation.", "Astrology organizes cycles and correspondences; intuition helps recognize which symbols resonate meaningfully with a person’s experience. Both should work together without turning observed tendencies into absolute statements."] },
  ],
  FR: [
    { title: "Histoire et contexte", paragraphs: ["L’astrologie occidentale trouve ses racines dans l’ancienne Mésopotamie. En Babylonie et en Assyrie, dès le deuxième millénaire avant notre ère, les prêtres observaient les cycles célestes et les reliaient au climat, aux récoltes, aux guerres et au destin des royaumes.", "Entre le IIe siècle av. J.-C. et le IIe siècle apr. J.-C., cette tradition rencontra à Alexandrie la philosophie grecque et la géométrie égyptienne. De leur intégration naquit l’astrologie généthliaque, centrée sur l’individu et sur la Carte Natale comme représentation du ciel au moment exact de la naissance.", "Au IIe siècle, Claude Ptolémée organisa une grande partie de ses fondements techniques dans le Tetrabiblos. À la Renaissance, astrologie et astronomie partageaient encore un même champ d’étude ; des figures comme Johannes Kepler pratiquaient les deux.", "Sa vision repose sur le principe hermétique de correspondance —« ce qui est en haut est comme ce qui est en bas »— et considère les cycles planétaires et zodiacaux comme un langage symbolique. Le ciel ne fixe pas un destin immuable : il propose une carte d’archétypes, de potentiels, de tensions psychologiques et de tendances temporelles à interpréter ensemble."] },
    { title: "Forme de consultation", paragraphs: ["Une consultation d’astrologie occidentale ne repose pas sur un signe, une planète ou un aspect isolé. La Carte Natale constitue la racine structurelle : elle enregistre les coordonnées célestes de la date, de l’heure et du lieu de naissance afin d’étudier la personnalité, les potentiels, les blocages et les dynamiques psychologiques internes.", "Les Transits et les Progressions apportent la dimension dynamique en comparant le mouvement planétaire d’une période avec la Carte Natale. La Révolution Solaire complète la dimension cyclique annuelle : elle est calculée pour l’instant exact où le Soleil revient à sa position natale et révèle les thèmes dominants d’un anniversaire au suivant."] },
    { title: "Clé d’interprétation", paragraphs: ["La Carte Natale doit servir de base à toute analyse. Pour obtenir une lecture claire sans surcharge, il convient de comparer les transits actuels à ses points les plus sensibles : l’Ascendant, le Soleil, la Lune et les maîtres des maisons liées à la consultation.", "L’astrologie organise les cycles et les correspondances ; l’intuition aide à reconnaître les symboles qui résonnent dans l’expérience de la personne. Toutes deux doivent agir ensemble, sans transformer les tendances observées en affirmations absolues."] },
  ],
  DE: [
    { title: "Geschichte und Kontext", paragraphs: ["Die westliche Astrologie hat ihre Wurzeln im alten Mesopotamien. In Babylonien und Assyrien beobachteten Priester seit etwa dem zweiten Jahrtausend v. Chr. die Himmelszyklen und bezogen sie auf Wetter, Ernten, Kriege und das Schicksal der Reiche.", "Zwischen dem 2. Jahrhundert v. Chr. und dem 2. Jahrhundert n. Chr. verband sich diese Tradition in Alexandria mit griechischer Philosophie und ägyptischer Geometrie. Daraus entstand die Geburtsastrologie, die den Menschen und die Geburtskarte als Darstellung des Himmels im genauen Augenblick der Geburt in den Mittelpunkt stellt.", "Im 2. Jahrhundert ordnete Claudius Ptolemäus viele ihrer technischen Grundlagen im Tetrabiblos. In der Renaissance gehörten Astrologie und Astronomie noch zu einem gemeinsamen Studienfeld; Persönlichkeiten wie Johannes Kepler praktizierten beides.", "Ihr Weltbild beruht auf dem hermetischen Entsprechungsprinzip —„Wie oben, so unten“— und versteht planetare sowie zodiakale Zyklen als symbolische Sprache. Der Himmel bestimmt kein unabänderliches Schicksal, sondern bietet eine Karte von Archetypen, Potenzialen, psychologischen Spannungen und zeitlichen Tendenzen, die gemeinsam gedeutet werden."] },
    { title: "Form der Beratung", paragraphs: ["Eine westlich-astrologische Beratung beruht nicht auf einem einzelnen Zeichen, Planeten oder Aspekt. Die Geburtskarte bildet die strukturelle Wurzel: Sie erfasst die Himmelskoordinaten von Datum, Uhrzeit und Ort der Geburt, um Persönlichkeit, Potenziale, Blockaden und innere psychologische Dynamiken zu untersuchen.", "Transite und Progressionen liefern die dynamische Dimension, indem sie die Planetenbewegungen eines Zeitraums mit der Geburtskarte vergleichen. Die Solarrevolution ergänzt die jährliche zyklische Dimension: Sie wird für den exakten Augenblick der Rückkehr der Sonne an ihre Geburtsposition berechnet und zeigt die vorherrschenden Themen von Geburtstag zu Geburtstag."] },
    { title: "Schlüssel zur Deutung", paragraphs: ["Die Geburtskarte sollte die Grundlage jeder Analyse sein. Für eine klare Deutung ohne Überladung werden aktuelle Transite mit ihren empfindlichsten Punkten verglichen: Aszendent, Sonne, Mond und die Herrscher der für die Frage wichtigen Häuser.", "Astrologie ordnet Zyklen und Entsprechungen; Intuition hilft zu erkennen, welche Symbole in der Erfahrung eines Menschen bedeutsam nachklingen. Beides sollte zusammenwirken, ohne beobachtete Tendenzen zu absoluten Aussagen zu machen."] },
  ],
  PT: [
    { title: "História e contexto", paragraphs: ["A astrologia ocidental tem suas raízes na antiga Mesopotâmia. Na Babilônia e na Assíria, aproximadamente desde o segundo milênio a.C., os sacerdotes observavam os ciclos celestes e os relacionavam ao clima, às colheitas, às guerras e ao destino dos reinos.", "Entre os séculos II a.C. e II d.C., essa tradição encontrou em Alexandria a filosofia grega e a geometria egípcia. Dessa integração nasceu a astrologia natal, centrada no indivíduo e no Mapa Natal como representação do céu no momento exato do nascimento.", "No século II, Cláudio Ptolomeu organizou grande parte de seus fundamentos técnicos no Tetrabiblos. Durante o Renascimento, astrologia e astronomia ainda compartilhavam um mesmo campo de estudo; figuras como Johannes Kepler praticavam ambas.", "Sua cosmovisão se apoia no princípio hermético da correspondência —“assim em cima como embaixo”— e compreende os ciclos planetários e zodiacais como uma linguagem simbólica. O céu não determina um destino imutável: oferece um mapa de arquétipos, potenciais, tensões psicológicas e tendências temporais que devem ser interpretados em conjunto."] },
    { title: "Forma de consulta", paragraphs: ["Uma consulta de astrologia ocidental não se baseia em um signo, planeta ou aspecto isolado. O Mapa Natal constitui a raiz estrutural: registra as coordenadas celestes da data, hora e local de nascimento para estudar a personalidade, os potenciais, os bloqueios e as dinâmicas psicológicas internas.", "Os Trânsitos e as Progressões fornecem a dimensão dinâmica ao comparar o movimento planetário de um período com o Mapa Natal. A Revolução Solar completa a dimensão cíclica anual: é calculada para o instante exato em que o Sol retorna à posição natal e revela os temas predominantes de um aniversário ao seguinte."] },
    { title: "Chave para a interpretação", paragraphs: ["O Mapa Natal deve ser usado como base de toda análise. Para obter uma leitura clara e evitar excesso de informação, convém comparar os trânsitos atuais com seus pontos mais sensíveis: Ascendente, Sol, Lua e regentes das casas relacionadas à consulta.", "A astrologia organiza ciclos e correspondências; a intuição permite reconhecer quais símbolos ressoam de maneira significativa na experiência da pessoa. Ambas devem trabalhar juntas, sem transformar as tendências observadas em afirmações absolutas."] },
  ],
};

const libraryCopy: Record<Language, { reference: string; westernWheel: string; westernDesc: string; easternWheel: string; easternDesc: string; planets: string; planetsDesc: string; elements: string; elementsDesc: string; polarity: string; polarityDesc: string }> = {
  ES: { reference: "Imagen de referencia", westernWheel: "Rueda celeste occidental", westernDesc: "Síntesis visual del zodiaco, las órbitas y la geometría astrológica.", easternWheel: "Rueda cosmológica oriental", easternDesc: "Síntesis visual de Yin/Yang, cinco elementos y doce animales.", planets: "Planetas", planetsDesc: "Funciones simbólicas que actúan dentro de signos, casas y aspectos.", elements: "Cinco elementos", elementsDesc: "Madera, Fuego, Tierra, Metal y Agua en sus ciclos.", polarity: "Yin y Yang", polarityDesc: "Polaridad complementaria presente en cada elemento y pilar." },
  EN: { reference: "Reference image", westernWheel: "Western celestial wheel", westernDesc: "A visual synthesis of the zodiac, planetary orbits, and astrological geometry.", easternWheel: "Eastern cosmological wheel", easternDesc: "A visual synthesis of Yin/Yang, five elements, and twelve animals.", planets: "Planets", planetsDesc: "Symbolic functions acting through signs, houses, and aspects.", elements: "Five elements", elementsDesc: "Wood, Fire, Earth, Metal, and Water in their cycles.", polarity: "Yin and Yang", polarityDesc: "Complementary polarity present in every element and pillar." },
  FR: { reference: "Image de référence", westernWheel: "Roue céleste occidentale", westernDesc: "Synthèse visuelle du zodiaque, des orbites et de la géométrie astrologique.", easternWheel: "Roue cosmologique orientale", easternDesc: "Synthèse visuelle du Yin/Yang, des cinq éléments et des douze animaux.", planets: "Planètes", planetsDesc: "Fonctions symboliques actives dans les signes, maisons et aspects.", elements: "Cinq éléments", elementsDesc: "Bois, Feu, Terre, Métal et Eau dans leurs cycles.", polarity: "Yin et Yang", polarityDesc: "Polarité complémentaire présente dans chaque élément et pilier." },
  DE: { reference: "Referenzbild", westernWheel: "Westliches Himmelsrad", westernDesc: "Visuelle Synthese von Tierkreis, Umlaufbahnen und astrologischer Geometrie.", easternWheel: "Östliches kosmologisches Rad", easternDesc: "Visuelle Synthese von Yin/Yang, fünf Elementen und zwölf Tieren.", planets: "Planeten", planetsDesc: "Symbolische Funktionen in Zeichen, Häusern und Aspekten.", elements: "Fünf Elemente", elementsDesc: "Holz, Feuer, Erde, Metall und Wasser in ihren Zyklen.", polarity: "Yin und Yang", polarityDesc: "Komplementäre Polarität in jedem Element und jeder Säule." },
  PT: { reference: "Imagem de referência", westernWheel: "Roda celeste ocidental", westernDesc: "Síntese visual do zodíaco, das órbitas e da geometria astrológica.", easternWheel: "Roda cosmológica oriental", easternDesc: "Síntese visual de Yin/Yang, cinco elementos e doze animais.", planets: "Planetas", planetsDesc: "Funções simbólicas que atuam em signos, casas e aspectos.", elements: "Cinco elementos", elementsDesc: "Madeira, Fogo, Terra, Metal e Água em seus ciclos.", polarity: "Yin e Yang", polarityDesc: "Polaridade complementar presente em cada elemento e pilar." },
};

export function AstrologySite({ branch, lang, onBack }: AstrologySiteProps) {
  const [selected, setSelected] = useState<number | null>(null);
  const text = content[lang][branch];
  const lib = libraryCopy[lang];
  const astrologyLibrary = branch === "western" ? [
    { id: "western-wheel", name: lib.westernWheel, category: lib.reference, image: "/oracles/astrology/western-celestial-wheel.png", description: lib.westernDesc },
    ...text.focuses.map((item, index) => ({ id: `western-${index}`, name: item.title, category: item.level, symbol: ["◎", "☍", "☀", "✦"][index], description: item.description })),
    { id: "planets", name: lib.planets, category: text.eyebrow, symbol: "☿", description: lib.planetsDesc },
  ] : [
    { id: "eastern-wheel", name: lib.easternWheel, category: lib.reference, image: "/oracles/astrology/eastern-cosmology-wheel.png", description: lib.easternDesc },
    { id: "bazi", name: text.focuses[0].title, category: text.focuses[0].level, symbol: "八", description: text.focuses[0].description },
    { id: "animals", name: text.focuses[1].title, category: text.focuses[1].level, symbol: "子", description: text.focuses[1].description },
    { id: "elements", name: lib.elements, category: "Wu Xing", symbol: "木", description: lib.elementsDesc },
    { id: "polarity", name: lib.polarity, category: "Yin/Yang", symbol: "☯", description: lib.polarityDesc },
    { id: "ziwei", name: text.focuses[2].title, category: text.focuses[2].level, symbol: "紫", description: text.focuses[2].description },
  ] satisfies DisciplineLibraryItem[];
  const focus = selected === null ? null : text.focuses[selected];

  useEffect(() => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  }, []);

  return <section className={`astrology-site astrology-${branch}`}>
    <button type="button" className="astrology-back" onClick={onBack}>← {text.back}</button>
    <header className="astrology-heading"><span>{text.eyebrow}</span><h1>{text.title}</h1><strong>{text.subtitle}</strong>{branch === "western" ? <div className="astrology-introduction-sections">{westernIntroductions[lang].map(section => <section key={section.title}><h2>{section.title}</h2>{section.paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</section>)}</div> : <p>{text.introduction}</p>}</header>
    <section className="astrology-focus-panel" aria-labelledby={`${branch}-focus-title`}>
      <span className="astrology-mini-label" id={`${branch}-focus-title`}>{text.choose}</span>
      <div className="astrology-focus-grid">
        {text.focuses.map((item, index) => <button type="button" className={selected === index ? "selected" : ""} onClick={() => setSelected(index)} key={item.title}><i aria-hidden="true">{item.symbol}</i><span><small>{item.level}</small><b>{item.title}</b><em>{item.description}</em></span><strong aria-hidden="true">{selected === index ? "−" : "+"}</strong></button>)}
      </div>
      {focus && <article className="astrology-pending" aria-live="polite"><small>{text.pending}</small><h2>{focus.title}</h2><p>{text.pendingDescription}</p></article>}
    </section>
    <DisciplineLibrary lang={lang} items={astrologyLibrary} />
  </section>;
}
