import type { Language } from "../translations";
import type { AstroDiscipline } from "./AstroConsultationFlow";
import type { Aspect, FullAstroCalculation, PlanetPosition } from "./astro-full-calculations";
import "./astro-interpretation-chart.css";
import "./astro-complete-chart.css";

type Props={discipline:AstroDiscipline;focusIndex:number;lang:Language;data:FullAstroCalculation};
const text:Record<Language,Record<string,string>>={
  ES:{chart:"MAPA CALCULADO",verified:"Datos calculados",natal:"Carta Natal",transits:"Tránsitos sobre la Carta Natal",solar:"Revolución Solar",horoscope:"Clima zodiacal actual",pillars:"Cuatro Pilares",elements:"Balance de elementos",palaces:"Doce palacios de Zi Wei Dou Shu",life:"Vida",expression:"Expresión",soul:"Alma",year:"Año personal"},
  EN:{chart:"CALCULATED CHART",verified:"Calculated data",natal:"Natal Chart",transits:"Transits to the Natal Chart",solar:"Solar Return",horoscope:"Current zodiac climate",pillars:"Four Pillars",elements:"Element balance",palaces:"Twelve Zi Wei Dou Shu palaces",life:"Life",expression:"Expression",soul:"Soul",year:"Personal year"},
  FR:{chart:"CARTE CALCULÉE",verified:"Données calculées",natal:"Thème natal",transits:"Transits sur le thème natal",solar:"Révolution solaire",horoscope:"Climat zodiacal actuel",pillars:"Quatre Piliers",elements:"Équilibre des éléments",palaces:"Douze palais Zi Wei Dou Shu",life:"Vie",expression:"Expression",soul:"Âme",year:"Année personnelle"},
  DE:{chart:"BERECHNETE KARTE",verified:"Berechnete Daten",natal:"Geburtshoroskop",transits:"Transite zum Geburtshoroskop",solar:"Sonnenwiederkehr",horoscope:"Aktuelles Tierkreis-Klima",pillars:"Vier Säulen",elements:"Element-Balance",palaces:"Zwölf Zi-Wei-Dou-Shu-Paläste",life:"Leben",expression:"Ausdruck",soul:"Seele",year:"Persönliches Jahr"},
  PT:{chart:"MAPA CALCULADO",verified:"Dados calculados",natal:"Mapa natal",transits:"Trânsitos sobre o mapa natal",solar:"Revolução Solar",horoscope:"Clima zodiacal atual",pillars:"Quatro Pilares",elements:"Equilíbrio dos elementos",palaces:"Doze palácios Zi Wei Dou Shu",life:"Vida",expression:"Expressão",soul:"Alma",year:"Ano pessoal"},
};
const zodiac=["♈","♉","♊","♋","♌","♍","♎","♏","♐","♑","♒","♓"];
const point=(cx:number,cy:number,r:number,angle:number)=>({x:cx+Math.cos((angle-90)*Math.PI/180)*r,y:cy+Math.sin((angle-90)*Math.PI/180)*r});
const aspectClass:Record<string,string>={conjunction:"neutral",sextile:"flow",square:"tension",trine:"flow",opposition:"tension"};

function aspectLines(aspects:Aspect[],positions:PlanetPosition[],radius:number){const byName=Object.fromEntries(positions.map(p=>[p.name,p]));return aspects.slice(0,24).map((aspect,index)=>{const a=byName[aspect.from],b=byName[aspect.to];if(!a||!b)return null;const pa=point(300,210,radius,a.longitude),pb=point(300,210,radius,b.longitude);return <line key={`${aspect.from}-${aspect.to}-${index}`} className={`chart-aspect ${aspectClass[aspect.type]||"neutral"}`} x1={pa.x} y1={pa.y} x2={pb.x} y2={pb.y}/>})}
function transitAspectLines(aspects:Aspect[],transits:PlanetPosition[],natal:PlanetPosition[]){const moving=Object.fromEntries(transits.map(p=>[p.name,p])),root=Object.fromEntries(natal.map(p=>[p.name,p]));return aspects.slice(0,24).map((item,index)=>{const a=moving[item.from],b=root[item.to];if(!a||!b)return null;const pa=point(300,210,112,a.longitude),pb=point(300,210,83,b.longitude);return <line key={`${item.from}-${item.to}-${index}`} className={`chart-aspect ${aspectClass[item.type]||"neutral"}`} x1={pa.x} y1={pa.y} x2={pb.x} y2={pb.y}/>})}

function Wheel({focusIndex,data}:{focusIndex:number;data:FullAstroCalculation}){const w=data.western!;const moving=focusIndex===1||focusIndex===3;const current=moving?w.transits:focusIndex===2?w.solarReturnPlanets:w.planets;const houses=focusIndex===2?w.solarReturnHouses:w.houses;const aspects=moving?w.transitAspects:focusIndex===2?w.solarReturnAspects:w.aspects;const asc=focusIndex===2?w.solarReturnAscendant:w.ascendant,mc=focusIndex===2?w.solarReturnMc:w.mc;return <svg viewBox="0 0 600 420" role="img">
  <circle className="chart-ring outer" cx="300" cy="210" r="174"/><circle className="chart-ring" cx="300" cy="210" r="138"/><circle className="chart-ring inner" cx="300" cy="210" r="70"/>
  {zodiac.map((symbol,index)=>{const label=point(300,210,156,index*30+15);const line=point(300,210,174,index*30);return <g key={symbol}><line className="chart-axis" x1="300" y1="210" x2={line.x} y2={line.y}/><text className="chart-symbol" x={label.x} y={label.y}>{symbol}</text></g>})}
  {houses.map((cusp,index)=>{const edge=point(300,210,138,cusp);const label=point(300,210,121,cusp+3);return <g key={index}><line className="chart-house" x1="300" y1="210" x2={edge.x} y2={edge.y}/><text className="chart-house-label" x={label.x} y={label.y}>{index+1}</text></g>})}
  {moving?transitAspectLines(aspects,w.transits,w.planets):aspectLines(aspects,current,91)}
  {current.map((planet,index)=>{const radius=104+(index%3)*10;const p=point(300,210,radius,planet.longitude);return <g className="planet-node" key={planet.name}><circle cx={p.x} cy={p.y} r="12"/><text x={p.x} y={p.y+5}>{planet.symbol}</text></g>})}
  <text className="chart-angle-label" x="300" y="205">ASC {Math.floor(asc%30)}° {zodiac[Math.floor(asc/30)]}</text><text className="chart-angle-label secondary" x="300" y="225">MC {Math.floor(mc%30)}° {zodiac[Math.floor(mc/30)]}</text>
 </svg>}

const elementOrder=["Madera","Fuego","Tierra","Metal","Agua"];
function Eastern({focusIndex,data}:{focusIndex:number;data:FullAstroCalculation}){const b=data.bazi!,z=data.ziwei!;
 if(focusIndex===1){const values=elementOrder.map(name=>35+(b.elements[name]||0)/8*85);const valuePoints=values.map((value,index)=>point(300,210,value,index*72)).map(p=>`${p.x},${p.y}`).join(" ");return <svg viewBox="0 0 600 420"><polygon className="element-frame" points={elementOrder.map((_,i)=>{const p=point(300,210,120,i*72);return `${p.x},${p.y}`}).join(" ")}/>{elementOrder.map((name,i)=>{const p=point(300,210,145,i*72);return <text className="element-label" x={p.x} y={p.y} key={name}>{name} {b.elements[name]}</text>})}<polygon className="element-value" points={valuePoints}/><text className="chart-center-glyph tiger" x="300" y="228">{b.dayMaster}</text></svg>}
 if(focusIndex===2)return <svg viewBox="0 0 600 420"><rect className="ziwei-frame" x="116" y="26" width="368" height="368" rx="8"/>{z.palaces.map((palace,index)=>{const col=index%4,row=Math.floor(index/4);const x=120+col*91,y=30+row*121;return <g className={palace.isBody||palace.isOrigin?"ziwei-cell active":"ziwei-cell"} key={palace.index}><rect x={x} y={y} width="87" height="117" rx="6"/><text x={x+43.5} y={y+24}>{palace.name}</text><text className="ziwei-stars" x={x+43.5} y={y+50}>{palace.majorStars.slice(0,2).map(s=>s.name).join(" · ")||"—"}</text><text className="ziwei-range" x={x+43.5} y={y+101}>{palace.decadal[0]}–{palace.decadal[1]}</text></g>})}</svg>;
 return <svg viewBox="0 0 600 420">{b.pillars.map((pillar,index)=><g className={pillar.key==="day"?"pillar active":"pillar"} key={pillar.key} transform={`translate(${65+index*125} 60)`}><rect width="105" height="300" rx="16"/><text className="pillar-label" x="52" y="38">{pillar.key}</text><text className="pillar-value" x="52" y="155">{pillar.ganZhi}</text><text className="pillar-animal" x="52" y="220">{pillar.wuXing}</text><text className="pillar-detail" x="52" y="270">{pillar.tenGod}</text></g>)}</svg>}

function NumberChart({focusIndex,data,t}:{focusIndex:number;data:FullAstroCalculation;t:Record<string,string>}){const n=data.numerology;const values=[n.life,n.expression,n.soul,n.year],labels=[t.life,t.expression,t.soul,t.year],chosen=values[focusIndex]??n.life;return <svg viewBox="0 0 600 420"><circle className="chart-ring outer" cx="300" cy="210" r="168"/><circle className="chart-ring" cx="300" cy="210" r="126"/><circle className="chart-ring inner" cx="300" cy="210" r="79"/>{values.map((value,index)=>{const p=point(300,210,145,index*90);return <g className={index===focusIndex?"number-node active":"number-node"} key={labels[index]}><circle cx={p.x} cy={p.y} r="30"/><text x={p.x} y={p.y+7}>{value}</text><text className="number-label" x={p.x} y={p.y+(index===0?-42:48)}>{labels[index]}</text></g>})}<text className="number-core" x="300" y="237">{chosen}</text></svg>}

export function AstroInterpretationChart({discipline,focusIndex,lang,data}:Props){const t=text[lang];const subtitles=discipline==="western"?[t.natal,t.transits,t.solar,t.horoscope]:discipline==="eastern"?[t.pillars,t.elements,t.palaces]:[t.life,t.expression,t.soul,t.year];return <section className={`astro-chart astro-chart-${discipline}`}><header><span>{t.chart}</span><h3>{subtitles[focusIndex]}</h3></header><div className="astro-chart-canvas">{discipline==="western"?<Wheel focusIndex={focusIndex} data={data}/>:discipline==="eastern"?<Eastern focusIndex={focusIndex} data={data}/>:<NumberChart focusIndex={focusIndex} data={data} t={t}/>}</div><footer><i/><span>{t.verified}</span></footer></section>}
