import type { Language } from "../translations";
import { useAstroThemeInterpretation } from "../hooks/useAstroThemeInterpretation";
import type { AstroConsultationPayload, AstroDiscipline } from "./AstroConsultationFlow";
import type { FullAstroCalculation } from "./astro-full-calculations";
import { getAstroThemeContracts, getHighlightedThemeIds, type AstroThemeContract } from "./astro-theme-contracts";
import "./astro-theme-explorer.css";

const copy:Record<Language,Record<string,string>>={
  ES:{title:"Profundiza en las áreas de tu vida",subtitle:"Explora este reporte desde distintos enfoques y descubre cómo se manifiestan sus símbolos en áreas específicas de tu experiencia.",featured:"DESTACADO",open:"Abrir reporte",launcher:"Profundiza en las áreas de tu vida",launcherHint:"Explora la interpretación desde enfoques específicos.",back:"Volver a Profundiza en las áreas de tu vida",backReport:"Volver a la interpretación general",context:"REPORTE DE ORIGEN",indicators:"INDICADORES UTILIZADOS",deterministic:"INTERPRETACIÓN DETERMINISTA",editorial:"AMPLIACIÓN EDITORIAL",loading:"Construyendo la ampliación editorial…",fallback:"La interpretación determinista está completa; la ampliación editorial no respondió en este momento.",trace:"Cada conclusión conserva trazabilidad interna hacia estos cálculos."},
  EN:{title:"Explore the areas of your life",subtitle:"Explore this report through different lenses and discover how its symbols manifest in specific areas of your experience.",featured:"FEATURED",open:"Open report",launcher:"Explore the areas of your life",launcherHint:"Explore the interpretation through specific lenses.",back:"Back to Explore the areas of your life",backReport:"Back to the general interpretation",context:"SOURCE REPORT",indicators:"INDICATORS USED",deterministic:"DETERMINISTIC INTERPRETATION",editorial:"EDITORIAL EXPANSION",loading:"Building the editorial expansion…",fallback:"The deterministic interpretation is complete; editorial enrichment did not respond at this time.",trace:"Each conclusion retains an internal trace to these calculations."},
  FR:{title:"Approfondissez les domaines de votre vie",subtitle:"Explorez ce rapport sous différents angles et découvrez comment ses symboles se manifestent dans des domaines précis de votre expérience.",featured:"À LA UNE",open:"Ouvrir le rapport",launcher:"Approfondissez les domaines de votre vie",launcherHint:"Explorez l’interprétation sous des angles précis.",back:"Retour aux domaines de votre vie",backReport:"Retour à l’interprétation générale",context:"RAPPORT D’ORIGINE",indicators:"INDICATEURS UTILISÉS",deterministic:"INTERPRÉTATION DÉTERMINISTE",editorial:"DÉVELOPPEMENT ÉDITORIAL",loading:"Création du développement éditorial…",fallback:"L’interprétation déterministe est complète ; l’enrichissement éditorial n’a pas répondu pour le moment.",trace:"Chaque conclusion conserve une trace interne vers ces calculs."},
  DE:{title:"Vertiefen Sie Ihre Lebensbereiche",subtitle:"Betrachten Sie diesen Bericht aus verschiedenen Perspektiven und entdecken Sie, wie seine Symbole in einzelnen Lebensbereichen wirken.",featured:"HERVORGEHOBEN",open:"Bericht öffnen",launcher:"Vertiefen Sie Ihre Lebensbereiche",launcherHint:"Betrachten Sie die Deutung aus spezifischen Perspektiven.",back:"Zurück zu den Lebensbereichen",backReport:"Zurück zur allgemeinen Deutung",context:"AUSGANGSBERICHT",indicators:"VERWENDETE INDIKATOREN",deterministic:"DETERMINISTISCHE DEUTUNG",editorial:"REDAKTIONELLE ERWEITERUNG",loading:"Die redaktionelle Erweiterung wird erstellt…",fallback:"Die deterministische Deutung ist vollständig; die redaktionelle Erweiterung antwortete derzeit nicht.",trace:"Jede Schlussfolgerung bleibt intern auf diese Berechnungen zurückführbar."},
  PT:{title:"Aprofunde as áreas da sua vida",subtitle:"Explore este relatório por diferentes enfoques e descubra como seus símbolos se manifestam em áreas específicas da sua experiência.",featured:"DESTAQUE",open:"Abrir relatório",launcher:"Aprofunde as áreas da sua vida",launcherHint:"Explore a interpretação por enfoques específicos.",back:"Voltar às áreas da sua vida",backReport:"Voltar à interpretação geral",context:"RELATÓRIO DE ORIGEM",indicators:"INDICADORES UTILIZADOS",deterministic:"INTERPRETAÇÃO DETERMINÍSTICA",editorial:"AMPLIAÇÃO EDITORIAL",loading:"Construindo a ampliação editorial…",fallback:"A interpretação determinística está completa; a ampliação editorial não respondeu neste momento.",trace:"Cada conclusão conserva rastreabilidade interna até estes cálculos."},
};

export function AstroThemeLauncher({lang,onOpen}:{lang:Language;onOpen:()=>void}){
  const t=copy[lang];
  return <div className="astro-theme-launcher"><p>{t.launcherHint}</p><button type="button" onClick={onOpen}>{t.launcher} <span aria-hidden="true">→</span></button></div>
}

export function AstroThemeMenu({discipline,focusIndex,lang,data,onSelect,onBack}:{discipline:AstroDiscipline;focusIndex:number;lang:Language;data:FullAstroCalculation;onSelect:(theme:AstroThemeContract)=>void;onBack?:()=>void}){
  const t=copy[lang];const contracts=getAstroThemeContracts(discipline,focusIndex,lang);const highlighted=getHighlightedThemeIds(discipline,focusIndex,contracts,data,lang);
  return <section className="astro-theme-menu" aria-labelledby="astro-theme-menu-title">{onBack&&<button type="button" className="astro-theme-back astro-theme-menu-back" onClick={onBack}>← {t.backReport}</button>}<header><h2 id="astro-theme-menu-title">{t.title}</h2><p>{t.subtitle}</p></header><div className="astro-theme-grid">{contracts.map(theme=><button type="button" key={theme.id} onClick={()=>onSelect(theme)} className={highlighted.has(theme.id)?"is-highlighted":""}><i aria-hidden="true">{theme.symbol}</i><span><small>{theme.category}</small>{highlighted.has(theme.id)&&<em>{t.featured}</em>}<b>{theme.title}</b><p>{theme.description}</p><span className="astro-theme-open">{t.open} →</span></span><strong aria-hidden="true">+</strong></button>)}</div></section>
}

export function AstroThemeReport({payload,focusIndex,data,theme,originalFocus,lang,onBack}:{payload:AstroConsultationPayload;focusIndex:number;data:FullAstroCalculation;theme:AstroThemeContract;originalFocus:string;lang:Language;onBack:()=>void}){
  const t=copy[lang];const {sections,deterministicSections,evidence,isLoading,streamingText,usedFallback}=useAstroThemeInterpretation(payload,focusIndex,data,theme);
  const streamed=streamingText.replace(/^#\s+[^\n]*\n+/,"").split(/^##\s+/m).filter(Boolean).map(part=>{const[title,...body]=part.split("\n");return{title:title.trim(),text:body.join("\n").trim()}}).filter(section=>section.text);
  const editorial=isLoading?streamed:usedFallback?[]:sections;
  return <section className="astro-theme-report">
    <button type="button" className="astro-theme-back" onClick={onBack}>← {t.back}</button>
    <header><div className="astro-theme-report-symbol" aria-hidden="true">{theme.symbol}</div><div><small>{theme.category}</small><h2>{theme.title}</h2><p>{theme.centralQuestion}</p><span>{t.context}: {originalFocus}</span></div></header>
    <aside className="astro-theme-evidence"><small>{t.indicators}</small><div>{evidence.map((item,index)=><span key={`${item.source}-${index}`}><b>{item.label}</b>{item.value}</span>)}</div><p>{t.trace}</p></aside>
    <section className="astro-theme-reading"><small>{t.deterministic}</small><div className="astro-theme-report-body">{deterministicSections.map(section=><article key={section.title}><h3>{section.title}</h3><p>{section.text}</p></article>)}</div></section>
    {isLoading&&<p className="astro-theme-status" aria-live="polite">{t.loading}</p>}
    {usedFallback&&<p className="astro-theme-status is-warning">{t.fallback}</p>}
    {editorial.length>0&&<section className="astro-theme-reading is-editorial"><small>{t.editorial}</small><div className="astro-theme-report-body">{editorial.map(section=><article key={section.title}><h3>{section.title}</h3><p>{section.text}</p></article>)}</div></section>}
    <button type="button" className="astro-theme-back is-bottom" onClick={onBack}>← {t.back}</button>
  </section>
}
