import type { Language } from "../translations";
import type { AstroDiscipline } from "./AstroConsultationFlow";
import type { FullAstroCalculation } from "./astro-full-calculations";
import "./astro-calculation-details.css";

const signs:Record<Language,string[]>={ES:["Aries","Tauro","Géminis","Cáncer","Leo","Virgo","Libra","Escorpio","Sagitario","Capricornio","Acuario","Piscis"],EN:["Aries","Taurus","Gemini","Cancer","Leo","Virgo","Libra","Scorpio","Sagittarius","Capricorn","Aquarius","Pisces"],FR:["Bélier","Taureau","Gémeaux","Cancer","Lion","Vierge","Balance","Scorpion","Sagittaire","Capricorne","Verseau","Poissons"],DE:["Widder","Stier","Zwillinge","Krebs","Löwe","Jungfrau","Waage","Skorpion","Schütze","Steinbock","Wassermann","Fische"],PT:["Áries","Touro","Gêmeos","Câncer","Leão","Virgem","Libra","Escorpião","Sagitário","Capricórnio","Aquário","Peixes"]};
const planetNames:Record<string,string>={Sun:"Sol",Moon:"Luna",Mercury:"Mercurio",Venus:"Venus",Mars:"Marte",Jupiter:"Júpiter",Saturn:"Saturno",Uranus:"Urano",Neptune:"Neptuno",Pluto:"Plutón","North Node":"Nodo Norte"};
const aspectNames:Record<string,string>={conjunction:"Conjunción",sextile:"Sextil",square:"Cuadratura",trine:"Trígono",opposition:"Oposición"};
const palaceNames:Record<string,string>={surface:"Apariencia",health:"Salud",wealth:"Riqueza",children:"Descendencia",spouse:"Pareja",siblings:"Hermanos",soul:"Destino",parents:"Padres",spirit:"Espíritu",property:"Propiedad",career:"Carrera",friends:"Amistades"};
const starNames:Record<string,string>={emperor:"Emperador",advisor:"Consejero",fortunate:"Fortuna",judge:"Juicio",sage:"Sabio",sun:"Sol",moon:"Luna",general:"General",scholar:"Erudito",officer:"Oficial",rebel:"Rebelde",empress:"Emperatriz",wolf:"Lobo",advocator:"Defensor",minister:"Ministro",marshal:"Mariscal"};
const ui:Record<Language,Record<string,string>>={
 ES:{details:"CÁLCULOS COMPLETOS",planet:"Planeta",position:"Posición",house:"Casa",motion:"Movimiento",retrograde:"Retrógrado",direct:"Directo",aspects:"Aspectos principales",asc:"Ascendente",mc:"Medio Cielo",return:"Retorno solar exacto",dayMaster:"Maestro del Día",soulBody:"Alma · Cuerpo",element:"Elemento",balance:"Balance de los cinco elementos",luck:"Ciclos de diez años",decade:"Década",pinnacles:"Pináculos",challenges:"Desafíos",cycles:"Ciclos vitales",lessons:"Lecciones kármicas",debts:"Deudas kármicas",none:"Ninguna"},
 EN:{details:"FULL CALCULATIONS",planet:"Planet",position:"Position",house:"House",motion:"Motion",retrograde:"Retrograde",direct:"Direct",aspects:"Main aspects",asc:"Ascendant",mc:"Midheaven",return:"Exact solar return",dayMaster:"Day Master",soulBody:"Soul · Body",element:"Element",balance:"Five-element balance",luck:"Ten-year cycles",decade:"Decade",pinnacles:"Pinnacles",challenges:"Challenges",cycles:"Life cycles",lessons:"Karmic lessons",debts:"Karmic debts",none:"None"},
 FR:{details:"CALCULS COMPLETS",planet:"Planète",position:"Position",house:"Maison",motion:"Mouvement",retrograde:"Rétrograde",direct:"Direct",aspects:"Aspects principaux",asc:"Ascendant",mc:"Milieu du Ciel",return:"Retour solaire exact",dayMaster:"Maître du Jour",soulBody:"Âme · Corps",element:"Élément",balance:"Équilibre des cinq éléments",luck:"Cycles de dix ans",decade:"Décennie",pinnacles:"Sommets",challenges:"Défis",cycles:"Cycles de vie",lessons:"Leçons karmiques",debts:"Dettes karmiques",none:"Aucune"},
 DE:{details:"VOLLSTÄNDIGE BERECHNUNGEN",planet:"Planet",position:"Position",house:"Haus",motion:"Bewegung",retrograde:"Rückläufig",direct:"Direkt",aspects:"Hauptaspekte",asc:"Aszendent",mc:"Medium Coeli",return:"Exakte Sonnenwiederkehr",dayMaster:"Tagesmeister",soulBody:"Seele · Körper",element:"Element",balance:"Fünf-Elemente-Balance",luck:"Zehnjahreszyklen",decade:"Dekade",pinnacles:"Höhepunkte",challenges:"Herausforderungen",cycles:"Lebenszyklen",lessons:"Karmische Lektionen",debts:"Karmische Schulden",none:"Keine"},
 PT:{details:"CÁLCULOS COMPLETOS",planet:"Planeta",position:"Posição",house:"Casa",motion:"Movimento",retrograde:"Retrógrado",direct:"Direto",aspects:"Aspectos principais",asc:"Ascendente",mc:"Meio do Céu",return:"Retorno solar exato",dayMaster:"Mestre do Dia",soulBody:"Alma · Corpo",element:"Elemento",balance:"Equilíbrio dos cinco elementos",luck:"Ciclos de dez anos",decade:"Década",pinnacles:"Pináculos",challenges:"Desafios",cycles:"Ciclos de vida",lessons:"Lições kármicas",debts:"Dívidas kármicas",none:"Nenhuma"},
};
const numLabels:Record<Language,string[]>={ES:["Vida","Expresión","Alma","Personalidad","Madurez","Cumpleaños","Actitud","Balance","Pasión oculta","Yo subconsciente","Piedra angular","Piedra final","Primera vocal","Año personal","Mes personal","Día personal"],EN:["Life Path","Expression","Soul","Personality","Maturity","Birthday","Attitude","Balance","Hidden Passion","Subconscious Self","Cornerstone","Capstone","First Vowel","Personal Year","Personal Month","Personal Day"],FR:["Chemin de Vie","Expression","Âme","Personnalité","Maturité","Anniversaire","Attitude","Équilibre","Passion cachée","Moi subconscient","Pierre angulaire","Pierre finale","Première voyelle","Année personnelle","Mois personnel","Jour personnel"],DE:["Lebensweg","Ausdruck","Seele","Persönlichkeit","Reife","Geburtstag","Haltung","Balance","Verborgene Leidenschaft","Unterbewusstes Selbst","Grundstein","Schlussstein","Erster Vokal","Persönliches Jahr","Persönlicher Monat","Persönlicher Tag"],PT:["Caminho de Vida","Expressão","Alma","Personalidade","Maturidade","Aniversário","Atitude","Equilíbrio","Paixão oculta","Eu subconsciente","Pedra angular","Pedra final","Primeira vogal","Ano pessoal","Mês pessoal","Dia pessoal"]};
const position=(longitude:number,lang:Language)=>`${Math.floor(longitude%30)}° ${String(Math.round((longitude%1)*60)).padStart(2,"0")}′ ${signs[lang][Math.floor(longitude/30)]}`;

export function AstroCalculationDetails({discipline,focusIndex,lang,data}:{discipline:AstroDiscipline;focusIndex:number;lang:Language;data:FullAstroCalculation}){const t=ui[lang];
 if(discipline==="western"&&data.western){const w=data.western;const moving=focusIndex===1||focusIndex===3;const planets=moving?w.transits:focusIndex===2?w.solarReturnPlanets:w.planets;const aspects=moving?w.transitAspects:focusIndex===2?w.solarReturnAspects:w.aspects;const asc=focusIndex===2?w.solarReturnAscendant:w.ascendant,mc=focusIndex===2?w.solarReturnMc:w.mc;return <section className="astro-calculation-details"><h3>{t.details}</h3><div className="astro-detail-summary"><b>{t.asc}<span>{position(asc,lang)}</span></b><b>{t.mc}<span>{position(mc,lang)}</span></b>{focusIndex===2&&<b>{t.return}<span>{w.solarReturn}</span></b>}</div><div className="astro-data-table"><table><thead><tr><th>{t.planet}</th><th>{t.position}</th><th>{t.house}</th><th>{t.motion}</th></tr></thead><tbody>{planets.map(p=><tr key={p.name}><td>{p.symbol} {lang==="ES"?(planetNames[p.name]||p.name):p.name}</td><td>{position(p.longitude,lang)}</td><td>{p.house}</td><td>{p.retrograde?t.retrograde:t.direct}</td></tr>)}</tbody></table></div><h4>{t.aspects}</h4><div className="astro-aspect-list">{aspects.slice(0,24).map((a,index)=><span key={`${a.from}-${a.to}-${index}`}><b>{lang==="ES"?(planetNames[a.from]||a.from):a.from} — {lang==="ES"?(planetNames[a.to]||a.to):a.to}</b>{lang==="ES"?(aspectNames[a.type]||a.type):a.type} · {a.orb.toFixed(2)}°</span>)}</div></section>}
 if(discipline==="eastern"&&data.bazi&&data.ziwei){const b=data.bazi,z=data.ziwei;if(focusIndex<2)return <section className="astro-calculation-details"><h3>{t.details}</h3><div className="astro-detail-summary"><b>{t.dayMaster}<span>{b.dayMaster} · {b.dayElement} {b.dayPolarity}</span></b><b>命宫 Ming Gong<span>{b.mingGong}</span></b><b>身宫 Shen Gong<span>{b.shenGong}</span></b></div><div className="bazi-pillar-grid">{b.pillars.map(p=><article key={p.key}><small>{p.key}</small><strong>{p.ganZhi}</strong><span>{p.wuXing}</span><span>{p.tenGod}</span><em>{p.hidden.join(" · ")}</em><em>{p.naYin}</em></article>)}</div><h4>{t.balance}</h4><div className="element-bars">{Object.entries(b.elements).map(([name,value])=><p key={name}><span>{name}</span><i><b style={{width:`${value/8*100}%`}}/></i><strong>{value}/8</strong></p>)}</div><h4>{t.luck}</h4><div className="luck-cycle-grid">{b.luckCycles.map(c=><span key={c.ganZhi+c.startYear}><b>{c.ganZhi}</b>{c.startYear}–{c.endYear}<small>{c.startAge}–{c.endAge}</small></span>)}</div></section>;return <section className="astro-calculation-details"><h3>{t.details}</h3><div className="astro-detail-summary"><b>{t.soulBody}<span>{lang==="ES"?(starNames[z.soul]||z.soul):z.soul} · {lang==="ES"?(starNames[z.body]||z.body):z.body}</span></b><b>{t.element}<span>{lang==="ES"?z.fiveElementsClass.replace("metal","Metal").replace("4th","4ª configuración"):z.fiveElementsClass}</span></b><b>{t.decade}<span>{lang==="ES"?(palaceNames[z.current.decadalPalace]||z.current.decadalPalace):z.current.decadalPalace}</span></b></div><div className="ziwei-palace-grid">{z.palaces.map(p=><article className={p.isBody||p.isOrigin?"active":""} key={p.index}><small>{lang==="ES"?(palaceNames[p.name]||p.name):p.name}</small><b>{p.stem} · {p.branch}</b><span>{p.majorStars.map(s=>lang==="ES"?(starNames[s.name]||s.name):s.name).join(" · ")||"—"}</span><span>{p.minorStars.slice(0,5).join(" · ")}</span><em>{p.decadal[0]}–{p.decadal[1]}</em></article>)}</div></section>}
 const n=data.numerology;const values=[n.life,n.expression,n.soul,n.personality,n.maturity,n.birthday,n.attitude,n.balance,n.hiddenPassion,n.subconsciousSelf,n.cornerstone,n.capstone,n.firstVowel,n.year,n.month,n.day];return <section className="astro-calculation-details"><h3>{t.details}</h3><div className="numerology-detail-grid">{values.map((value,index)=><b key={numLabels[lang][index]}><span>{numLabels[lang][index]}</span>{value}</b>)}</div><div className="numerology-cycles"><p><b>{t.pinnacles}</b>{n.pinnacles.map((value,index)=>`${value} (${n.pinnaclePeriods[index]})`).join(" · ")}</p><p><b>{t.challenges}</b>{n.challenges.join(" · ")}</p><p><b>{t.cycles}</b>{n.lifeCycles.join(" · ")}</p><p><b>{t.lessons}</b>{n.karmicLessons.join(" · ")||t.none}</p><p><b>{t.debts}</b>{n.karmicDebts.join(" · ")||t.none}</p></div></section>
}
