import type { Language } from "../translations";
import { useAstroThemeInterpretation } from "../hooks/useAstroThemeInterpretation";
import type { AstroConsultationPayload, AstroDiscipline } from "./AstroConsultationFlow";
import type { FullAstroCalculation } from "./astro-full-calculations";
import { getAstroThemeContracts, getHighlightedThemeIds, type AstroThemeContract } from "./astro-theme-contracts";
import "./astro-theme-explorer.css";

const copy:Record<Language,Record<string,string>>={
  ES:{eyebrow:"NIVEL 3 · PROFUNDIZACIÓN TEMÁTICA",title:"Profundiza en las áreas de tu vida",subtitle:"Explora este reporte desde distintos enfoques y descubre cómo se manifiestan sus símbolos en áreas específicas de tu experiencia.",featured:"DESTACADO",open:"Abrir reporte",back:"Volver a Profundiza en las áreas de tu vida",context:"REPORTE DE ORIGEN",indicators:"INDICADORES UTILIZADOS",loading:"Construyendo el reporte especializado…",fallback:"Lectura calculada disponible; la ampliación editorial no respondió en este momento.",trace:"Cada conclusión conserva trazabilidad interna hacia estos cálculos."},
  EN:{eyebrow:"LEVEL 3 · THEMATIC DEEP DIVE",title:"Explore the areas of your life",subtitle:"Explore this report through different lenses and discover how its symbols manifest in specific areas of your experience.",featured:"FEATURED",open:"Open report",back:"Back to Explore the areas of your life",context:"SOURCE REPORT",indicators:"INDICATORS USED",loading:"Building the specialized report…",fallback:"The calculated reading is available; editorial enrichment did not respond at this time.",trace:"Each conclusion retains an internal trace to these calculations."},
  FR:{eyebrow:"NIVEAU 3 · APPROFONDISSEMENT THÉMATIQUE",title:"Approfondissez les domaines de votre vie",subtitle:"Explorez ce rapport sous différents angles et découvrez comment ses symboles se manifestent dans des domaines précis de votre expérience.",featured:"À LA UNE",open:"Ouvrir le rapport",back:"Retour aux domaines de votre vie",context:"RAPPORT D’ORIGINE",indicators:"INDICATEURS UTILISÉS",loading:"Création du rapport spécialisé…",fallback:"La lecture calculée est disponible ; l’enrichissement éditorial n’a pas répondu pour le moment.",trace:"Chaque conclusion conserve une trace interne vers ces calculs."},
  DE:{eyebrow:"EBENE 3 · THEMATISCHE VERTIEFUNG",title:"Vertiefen Sie Ihre Lebensbereiche",subtitle:"Betrachten Sie diesen Bericht aus verschiedenen Perspektiven und entdecken Sie, wie seine Symbole in einzelnen Lebensbereichen wirken.",featured:"HERVORGEHOBEN",open:"Bericht öffnen",back:"Zurück zu den Lebensbereichen",context:"AUSGANGSBERICHT",indicators:"VERWENDETE INDIKATOREN",loading:"Der Fachbericht wird erstellt…",fallback:"Die berechnete Deutung ist verfügbar; die redaktionelle Erweiterung antwortete derzeit nicht.",trace:"Jede Schlussfolgerung bleibt intern auf diese Berechnungen zurückführbar."},
  PT:{eyebrow:"NÍVEL 3 · APROFUNDAMENTO TEMÁTICO",title:"Aprofunde as áreas da sua vida",subtitle:"Explore este relatório por diferentes enfoques e descubra como seus símbolos se manifestam em áreas específicas da sua experiência.",featured:"DESTAQUE",open:"Abrir relatório",back:"Voltar às áreas da sua vida",context:"RELATÓRIO DE ORIGEM",indicators:"INDICADORES UTILIZADOS",loading:"Construindo o relatório especializado…",fallback:"A leitura calculada está disponível; a ampliação editorial não respondeu neste momento.",trace:"Cada conclusão conserva rastreabilidade interna até estes cálculos."},
};

export function AstroThemeMenu({discipline,focusIndex,lang,data,onSelect}:{discipline:AstroDiscipline;focusIndex:number;lang:Language;data:FullAstroCalculation;onSelect:(theme:AstroThemeContract)=>void}){
  const t=copy[lang];const contracts=getAstroThemeContracts(discipline,focusIndex,lang);const highlighted=getHighlightedThemeIds(discipline,focusIndex,contracts,data);
  return <section className="astro-theme-menu" aria-labelledby="astro-theme-menu-title"><header><small>{t.eyebrow}</small><h2 id="astro-theme-menu-title">{t.title}</h2><p>{t.subtitle}</p></header><div className="astro-theme-grid">{contracts.map(theme=><button type="button" key={theme.id} onClick={()=>onSelect(theme)} className={highlighted.has(theme.id)?"is-highlighted":""}><i aria-hidden="true">{theme.symbol}</i><span><small>{theme.category}</small>{highlighted.has(theme.id)&&<em>{t.featured}</em>}<b>{theme.title}</b><p>{theme.description}</p><span className="astro-theme-open">{t.open} →</span></span><strong aria-hidden="true">+</strong></button>)}</div></section>
}

export function AstroThemeReport({payload,focusIndex,data,theme,originalFocus,lang,onBack}:{payload:AstroConsultationPayload;focusIndex:number;data:FullAstroCalculation;theme:AstroThemeContract;originalFocus:string;lang:Language;onBack:()=>void}){
  const t=copy[lang];const {sections,evidence,isLoading,streamingText,usedFallback}=useAstroThemeInterpretation(payload,focusIndex,data,theme);
  const streamed=streamingText.replace(/^#\s+[^\n]*\n+/,"").split(/^##\s+/m).filter(Boolean).map(part=>{const[title,...body]=part.split("\n");return{title:title.trim(),text:body.join("\n").trim()}}).filter(section=>section.text);
  const visible=isLoading&&streamed.length?streamed:sections;
  return <section className="astro-theme-report"><button type="button" className="astro-theme-back" onClick={onBack}>← {t.back}</button><header><div className="astro-theme-report-symbol" aria-hidden="true">{theme.symbol}</div><div><small>{theme.category}</small><h2>{theme.title}</h2><p>{theme.centralQuestion}</p><span>{t.context}: {originalFocus}</span></div></header>{isLoading&&<p className="astro-theme-status" aria-live="polite">{t.loading}</p>}{usedFallback&&<p className="astro-theme-status is-warning">{t.fallback}</p>}<div className="astro-theme-report-body">{visible.map(section=><article key={section.title}><small>{section.title}</small><p>{section.text}</p></article>)}</div><aside className="astro-theme-evidence"><small>{t.indicators}</small><div>{evidence.map((item,index)=><span key={`${item.source}-${index}`}><b>{item.label}</b>{item.value}</span>)}</div><p>{t.trace}</p></aside><button type="button" className="astro-theme-back is-bottom" onClick={onBack}>← {t.back}</button></section>
}
