"use client";

import { useEffect, useMemo, useState } from "react";
import type { Language } from "../translations";
import "./astro-consultation-flow.css";

export type AstroDiscipline = "western" | "eastern" | "numerology";

export type AstroConsultationPayload = {
  discipline: AstroDiscipline;
  focus: string;
  language: Language;
  name: string;
  birthName?: string;
  currentName?: string;
  birthDate: string;
  birthTime?: string;
  birthPlace?: string;
  currentPlace?: string;
  timezone?: string;
  targetDate?: string;
  calendar?: "solar" | "lunar";
  gender?: string;
  question: string;
};

type FormState = Omit<AstroConsultationPayload, "discipline" | "focus" | "language">;

const copy: Record<Language, Record<string, string>> = {
  ES: { eyebrow:"DATOS DE LA CONSULTA", title:"Prepara tu mapa", subtitle:"La precisión de los datos determina la precisión del cálculo.", name:"Nombre", birthName:"Nombre completo de nacimiento", currentName:"Nombre actual (opcional)", date:"Fecha de nacimiento", time:"Hora exacta de nacimiento", place:"Ciudad y país de nacimiento", currentPlace:"Ciudad actual", timezone:"Zona horaria de nacimiento", target:"Fecha que deseas analizar", calendar:"Calendario de nacimiento", solar:"Solar", lunar:"Lunar", gender:"Sexo registrado al nacer", female:"Femenino", male:"Masculino", other:"Prefiero no indicarlo", question:"Pregunta o intención", submit:"Preparar interpretación", required:"Completa los campos obligatorios.", result:"MAPA PREPARADO", resultTitle:"Tu consulta está lista", calculation:"Cálculo base", interpretation:"Interpretación", pending:"El contrato de la consulta ya está preparado. La interpretación editorial se mostrará aquí cuando Claude incorpore esta disciplina; no se sustituye temporalmente con lógica de Tarot.", new:"Modificar datos", focus:"Enfoque", data:"Datos utilizados", life:"Número de Vida", expression:"Número de Expresión", soul:"Número del Alma", year:"Año Personal", exactTime:"Si desconoces la hora, indícalo en tu pregunta; algunos cálculos no podrán ser exactos." },
  EN: { eyebrow:"CONSULTATION DATA", title:"Prepare your chart", subtitle:"Accurate data is essential for an accurate calculation.", name:"Name", birthName:"Full birth name", currentName:"Current name (optional)", date:"Date of birth", time:"Exact birth time", place:"Birth city and country", currentPlace:"Current city", timezone:"Birth timezone", target:"Date to analyze", calendar:"Birth calendar", solar:"Solar", lunar:"Lunar", gender:"Sex recorded at birth", female:"Female", male:"Male", other:"Prefer not to say", question:"Question or intention", submit:"Prepare interpretation", required:"Complete all required fields.", result:"CHART PREPARED", resultTitle:"Your consultation is ready", calculation:"Base calculation", interpretation:"Interpretation", pending:"The consultation contract is ready. The editorial interpretation will appear here when Claude adds this discipline; it is not temporarily replaced with Tarot logic.", new:"Edit data", focus:"Focus", data:"Data used", life:"Life Path", expression:"Expression Number", soul:"Soul Number", year:"Personal Year", exactTime:"If the time is unknown, mention it in your question; some calculations cannot be exact." },
  FR: { eyebrow:"DONNÉES DE CONSULTATION", title:"Préparez votre carte", subtitle:"La précision des données détermine celle du calcul.", name:"Nom", birthName:"Nom complet de naissance", currentName:"Nom actuel (facultatif)", date:"Date de naissance", time:"Heure exacte de naissance", place:"Ville et pays de naissance", currentPlace:"Ville actuelle", timezone:"Fuseau horaire de naissance", target:"Date à analyser", calendar:"Calendrier de naissance", solar:"Solaire", lunar:"Lunaire", gender:"Sexe enregistré à la naissance", female:"Féminin", male:"Masculin", other:"Je préfère ne pas l’indiquer", question:"Question ou intention", submit:"Préparer l’interprétation", required:"Complétez les champs obligatoires.", result:"CARTE PRÉPARÉE", resultTitle:"Votre consultation est prête", calculation:"Calcul de base", interpretation:"Interprétation", pending:"Le contrat de consultation est prêt. L’interprétation éditoriale apparaîtra ici lorsque Claude intégrera cette discipline; elle n’est pas remplacée par la logique du Tarot.", new:"Modifier les données", focus:"Approche", data:"Données utilisées", life:"Chemin de Vie", expression:"Nombre d’Expression", soul:"Nombre de l’Âme", year:"Année personnelle", exactTime:"Si l’heure est inconnue, indiquez-le dans votre question; certains calculs ne pourront pas être exacts." },
  DE: { eyebrow:"BERATUNGSDATEN", title:"Bereiten Sie Ihre Karte vor", subtitle:"Die Genauigkeit der Daten bestimmt die Genauigkeit der Berechnung.", name:"Name", birthName:"Vollständiger Geburtsname", currentName:"Aktueller Name (optional)", date:"Geburtsdatum", time:"Genaue Geburtszeit", place:"Geburtsstadt und Land", currentPlace:"Aktueller Wohnort", timezone:"Zeitzone der Geburt", target:"Zu analysierendes Datum", calendar:"Geburtskalender", solar:"Solar", lunar:"Lunar", gender:"Bei Geburt eingetragenes Geschlecht", female:"Weiblich", male:"Männlich", other:"Keine Angabe", question:"Frage oder Absicht", submit:"Deutung vorbereiten", required:"Füllen Sie alle Pflichtfelder aus.", result:"KARTE VORBEREITET", resultTitle:"Ihre Beratung ist bereit", calculation:"Grundberechnung", interpretation:"Deutung", pending:"Der Beratungsvertrag ist vorbereitet. Die redaktionelle Deutung erscheint hier, sobald Claude diese Disziplin integriert; sie wird nicht vorübergehend durch Tarot-Logik ersetzt.", new:"Daten bearbeiten", focus:"Schwerpunkt", data:"Verwendete Daten", life:"Lebensweg", expression:"Ausdruckszahl", soul:"Seelenzahl", year:"Persönliches Jahr", exactTime:"Falls die Uhrzeit unbekannt ist, erwähnen Sie dies in Ihrer Frage; manche Berechnungen sind dann nicht exakt möglich." },
  PT: { eyebrow:"DADOS DA CONSULTA", title:"Prepare seu mapa", subtitle:"A precisão dos dados determina a precisão do cálculo.", name:"Nome", birthName:"Nome completo de nascimento", currentName:"Nome atual (opcional)", date:"Data de nascimento", time:"Hora exata de nascimento", place:"Cidade e país de nascimento", currentPlace:"Cidade atual", timezone:"Fuso horário de nascimento", target:"Data a analisar", calendar:"Calendário de nascimento", solar:"Solar", lunar:"Lunar", gender:"Sexo registrado ao nascer", female:"Feminino", male:"Masculino", other:"Prefiro não informar", question:"Pergunta ou intenção", submit:"Preparar interpretação", required:"Preencha os campos obrigatórios.", result:"MAPA PREPARADO", resultTitle:"Sua consulta está pronta", calculation:"Cálculo base", interpretation:"Interpretação", pending:"O contrato da consulta está preparado. A interpretação editorial aparecerá aqui quando Claude incorporar esta disciplina; ela não será substituída temporariamente pela lógica do Tarot.", new:"Modificar dados", focus:"Enfoque", data:"Dados utilizados", life:"Caminho de Vida", expression:"Número de Expressão", soul:"Número da Alma", year:"Ano Pessoal", exactTime:"Se a hora for desconhecida, mencione isso em sua pergunta; alguns cálculos não poderão ser exatos." },
};

const initial: FormState = { name:"", birthName:"", currentName:"", birthDate:"", birthTime:"", birthPlace:"", currentPlace:"", timezone:Intl.DateTimeFormat().resolvedOptions().timeZone, targetDate:new Date().toISOString().slice(0,10), calendar:"solar", gender:"", question:"" };

const reduce = (value:number) => { let result=value; while(result>9 && ![11,22,33].includes(result)) result=String(result).split("").reduce((sum,digit)=>sum+Number(digit),0); return result; };
const letterValue = (letter:string) => ((letter.charCodeAt(0)-65)%9)+1;
function numerologyValues(name:string,date:string){ const clean=name.normalize("NFD").replace(/[^a-z]/gi,"").toUpperCase(); const vowels=new Set(["A","E","I","O","U"]); const digits=date.replace(/\D/g,"").split("").map(Number); const now=new Date(); const [year,month,day]=date.split("-").map(Number); return { life:reduce(digits.reduce((a,b)=>a+b,0)), expression:reduce([...clean].reduce((a,b)=>a+letterValue(b),0)), soul:reduce([...clean].filter(c=>vowels.has(c)).reduce((a,b)=>a+letterValue(b),0)), year:reduce(reduce(day)+reduce(month)+reduce(now.getFullYear())), birthday:reduce(day), birthYear:year }; }

export function AstroConsultationFlow({ discipline, focus, lang }: { discipline: AstroDiscipline; focus: string; lang: Language }) {
  const [form,setForm]=useState<FormState>(initial);
  const [submitted,setSubmitted]=useState<AstroConsultationPayload|null>(null);
  const [error,setError]=useState("");
  const t=copy[lang];
  const image=discipline==="western"?"/oracles/astrology/western-astrolabe-v2.jpg":discipline==="eastern"?"/oracles/astrology/eastern-luopan-v2.jpg":"/oracles/numerology/numerology-oracle-v2.jpg";
  const numbers=useMemo(()=>discipline==="numerology"&&submitted?numerologyValues(submitted.birthName||submitted.name,submitted.birthDate):null,[discipline,submitted]);
  useEffect(()=>{ setSubmitted(null); setError(""); window.setTimeout(()=>document.querySelector(".astro-consultation-flow")?.scrollIntoView({behavior:"smooth",block:"start"}),50); },[focus]);
  const update=(key:keyof FormState,value:string)=>setForm(current=>({...current,[key]:value}));
  function submit(event:React.FormEvent){ event.preventDefault(); const required=discipline==="numerology"?[form.birthName,form.birthDate,form.question]:[form.name,form.birthDate,form.birthTime,form.birthPlace,form.timezone,form.question]; if(required.some(value=>!value?.trim())){setError(t.required);return;} setError(""); setSubmitted({discipline,focus,language:lang,...form}); window.setTimeout(()=>document.querySelector(".astro-result")?.scrollIntoView({behavior:"smooth",block:"start"}),50); }
  if(submitted) return <section className="astro-consultation-flow astro-result"><button className="astro-edit" onClick={()=>setSubmitted(null)}>← {t.new}</button><div className="astro-result-hero"><img src={image} alt=""/><div><small>{t.result}</small><h2>{t.resultTitle}</h2><p><b>{t.focus}:</b> {focus}</p></div></div><div className="astro-result-grid"><article><small>{t.data}</small><h3>{submitted.birthName||submitted.name}</h3><p>{submitted.birthDate}{submitted.birthTime?` · ${submitted.birthTime}`:""}</p><p>{submitted.birthPlace}</p><p>{submitted.question}</p></article><article><small>{t.calculation}</small>{numbers?<div className="astro-number-grid"><b>{numbers.life}<span>{t.life}</span></b><b>{numbers.expression}<span>{t.expression}</span></b><b>{numbers.soul}<span>{t.soul}</span></b><b>{numbers.year}<span>{t.year}</span></b></div>:<p>{focus}<br/>{submitted.targetDate}</p>}</article><article className="astro-interpretation-contract"><small>{t.interpretation}</small><p>{t.pending}</p></article></div></section>;
  return <section className="astro-consultation-flow"><header><small>{t.eyebrow}</small><h2>{t.title}</h2><p>{t.subtitle}</p></header><form onSubmit={submit} noValidate><div className="astro-form-grid">{discipline==="numerology"?<><label>{t.birthName}<input required value={form.birthName} onChange={e=>update("birthName",e.target.value)}/></label><label>{t.currentName}<input value={form.currentName} onChange={e=>update("currentName",e.target.value)}/></label></>:<label>{t.name}<input required value={form.name} onChange={e=>update("name",e.target.value)}/></label>}<label>{t.date}<input type="date" required value={form.birthDate} onInput={e=>update("birthDate",e.currentTarget.value)}/></label>{discipline!=="numerology"&&<><label>{t.time}<input type="time" required value={form.birthTime} onInput={e=>update("birthTime",e.currentTarget.value)}/><small>{t.exactTime}</small></label><label>{t.place}<input required value={form.birthPlace} onChange={e=>update("birthPlace",e.target.value)}/></label><label>{t.timezone}<input required value={form.timezone} onChange={e=>update("timezone",e.target.value)}/></label><label>{t.currentPlace}<input value={form.currentPlace} onChange={e=>update("currentPlace",e.target.value)}/></label><label>{t.target}<input type="date" value={form.targetDate} onInput={e=>update("targetDate",e.currentTarget.value)}/></label></>}{discipline==="eastern"&&<><label>{t.calendar}<select value={form.calendar} onChange={e=>update("calendar",e.target.value)}><option value="solar">{t.solar}</option><option value="lunar">{t.lunar}</option></select></label><label>{t.gender}<select value={form.gender} onChange={e=>update("gender",e.target.value)}><option value="">—</option><option value="female">{t.female}</option><option value="male">{t.male}</option><option value="other">{t.other}</option></select></label></>}<label className="astro-question">{t.question}<textarea required rows={4} value={form.question} onChange={e=>update("question",e.target.value)}/></label></div>{error&&<p className="astro-form-error" role="alert">{error}</p>}<button className="astro-submit" type="submit">{t.submit} →</button></form></section>;
}
