"use client";

import { useEffect } from "react";
import type { Language } from "../translations";
import type { DisciplineLibraryItem } from "./DisciplineLibrary";
import { CollapsibleDisciplineLibrary } from "./CollapsibleDisciplineLibrary";
import { AstroConsultationFlow } from "./AstroConsultationFlow";
import "./astrology-sites.css";
import "./astrology-introduction.css";
import "./numerology-site.css";
import "./astro-artwork-v2.css";

type Focus = { symbol: string; title: string; level: string; description: string };
type IntroSection = { title: string; paragraphs: string[] };
type Copy = { back: string; eyebrow: string; title: string; subtitle: string; choose: string; pending: string; pendingDescription: string; numberLabel: string; masterLabel: string; focuses: Focus[]; intro: IntroSection[] };

const content: Record<Language, Copy> = {
  ES: { back: "Volver al inicio", eyebrow: "NÚMERO · CICLO · SIGNIFICADO", title: "Numerología", subtitle: "La arquitectura simbólica del nombre y la fecha", choose: "Elige el enfoque", pending: "CÁLCULO PENDIENTE", pendingDescription: "El formulario de datos y el cálculo numerológico se incorporarán en la siguiente etapa.", numberLabel: "Número esencial", masterLabel: "Número maestro", focuses: [
    { symbol: "∑", title: "Número de Vida", level: "Esencial · Raíz", description: "La fecha completa de nacimiento como directriz, aprendizaje y recorrido vital." },
    { symbol: "A", title: "Número de Expresión", level: "Identidad · Manifestación", description: "El nombre completo de nacimiento como mapa de talentos y capacidades." },
    { symbol: "◉", title: "Número del Alma", level: "Interna · Deseo", description: "Las vocales del nombre como señal de motivaciones y necesidades profundas." },
    { symbol: "↻", title: "Año Personal y Ciclos", level: "Dinámica · Temporal", description: "El clima simbólico del periodo actual y la etapa activa del ciclo de nueve años." },
  ], intro: [
    { title: "Historia y contexto", paragraphs: ["La numerología estudia el significado simbólico de los números y los interpreta como arquetipos capaces de expresar patrones de personalidad, aprendizaje y ciclos de experiencia.", "Sus raíces se relacionan con tradiciones de la antigua Babilonia, la gematría hebrea vinculada con el Sefer Yetzirah, los Vedas de la India y, especialmente, la escuela pitagórica de la Grecia clásica. En el siglo VI a. C., el pensamiento atribuido a Pitágoras propuso que el orden del universo podía comprenderse mediante relaciones numéricas.", "Desde esta cosmovisión, los números no representan únicamente cantidades: también funcionan como cualidades simbólicas. La lectura numerológica explora esas correspondencias sin convertirlas en determinaciones absolutas."] },
    { title: "Forma de consulta", paragraphs: ["La consulta utiliza la reducción teosófica: se suman los dígitos de una fecha o los valores asignados a las letras de un nombre hasta obtener un número del 1 al 9, conservando 11, 22 y 33 como números maestros cuando el método aplicado así lo establece.", "El Número de Vida se calcula con la fecha completa de nacimiento; el Número de Expresión, con todas las letras del nombre de nacimiento; el Número del Alma, únicamente con sus vocales; y el Año Personal relaciona el día y el mes de nacimiento con el año calendario en curso."] },
    { title: "Clave para la interpretación", paragraphs: ["El Número de Vida ofrece la directriz estructural, pero debe contrastarse con el Año Personal para comprender el momento actual. Cada año tiene una función propia: 1 inicia, 2 vincula, 3 expresa, 4 consolida, 5 transforma, 6 responsabiliza, 7 interioriza, 8 materializa y 9 concluye.", "Una interpretación sólida cruza los números en lugar de aislarlos y utiliza la intuición para reconocer cómo se manifiestan sus símbolos en la experiencia concreta de la persona."] },
  ] },
  EN: { back: "Back to home", eyebrow: "NUMBER · CYCLE · MEANING", title: "Numerology", subtitle: "The symbolic architecture of name and date", choose: "Choose a focus", pending: "CALCULATION PENDING", pendingDescription: "The personal-data form and numerological calculation will be added in the next stage.", numberLabel: "Essential number", masterLabel: "Master number", focuses: [
    { symbol: "∑", title: "Life Path Number", level: "Essential · Root", description: "The complete birth date as a guide to learning and the life journey." },
    { symbol: "A", title: "Expression Number", level: "Identity · Manifestation", description: "The full birth name as a map of talents and abilities." },
    { symbol: "◉", title: "Soul Urge Number", level: "Inner · Desire", description: "The vowels in the name as a sign of deep motivations and needs." },
    { symbol: "↻", title: "Personal Year and Cycles", level: "Dynamic · Temporal", description: "The symbolic climate of the current period and the active nine-year stage." },
  ], intro: [
    { title: "History and context", paragraphs: ["Numerology studies the symbolic meaning of numbers and interprets them as archetypes that express patterns of personality, learning, and cycles of experience.", "Its roots are associated with ancient Babylonian traditions, Hebrew gematria linked to the Sefer Yetzirah, the Vedas of India, and especially the Pythagorean school of Classical Greece. In the sixth century BCE, thought attributed to Pythagoras proposed that the order of the universe could be understood through numerical relationships.", "In this worldview, numbers represent more than quantities: they also act as symbolic qualities. Numerological reading explores these correspondences without turning them into absolute determinations."] },
    { title: "Consultation structure", paragraphs: ["The consultation uses theosophical reduction: digits in a date or values assigned to letters are added until a number from 1 to 9 is obtained, while 11, 22, and 33 are retained as master numbers when required by the chosen method.", "The Life Path Number uses the complete birth date; the Expression Number uses every letter of the birth name; the Soul Urge Number uses only its vowels; and the Personal Year connects the birth day and month with the current calendar year."] },
    { title: "Key to interpretation", paragraphs: ["The Life Path Number provides the structural direction, but it should be compared with the Personal Year to understand the present moment. Each year has its own function: 1 begins, 2 connects, 3 expresses, 4 consolidates, 5 transforms, 6 assumes responsibility, 7 turns inward, 8 materializes, and 9 completes.", "A sound interpretation crosses the numbers instead of isolating them and uses intuition to recognize how their symbols manifest in a person’s actual experience."] },
  ] },
  FR: { back: "Retour à l’accueil", eyebrow: "NOMBRE · CYCLE · SIGNIFICATION", title: "Numérologie", subtitle: "L’architecture symbolique du nom et de la date", choose: "Choisissez l’approche", pending: "CALCUL EN ATTENTE", pendingDescription: "Le formulaire de données et le calcul numérologique seront intégrés à la prochaine étape.", numberLabel: "Nombre essentiel", masterLabel: "Nombre maître", focuses: [
    { symbol: "∑", title: "Chemin de Vie", level: "Essentiel · Racine", description: "La date complète de naissance comme orientation et parcours d’apprentissage." },
    { symbol: "A", title: "Nombre d’Expression", level: "Identité · Manifestation", description: "Le nom complet de naissance comme carte des talents et capacités." },
    { symbol: "◉", title: "Nombre de l’Âme", level: "Intérieur · Désir", description: "Les voyelles du nom comme signe des motivations et besoins profonds." },
    { symbol: "↻", title: "Année Personnelle et Cycles", level: "Dynamique · Temporel", description: "Le climat symbolique de la période et l’étape active du cycle de neuf ans." },
  ], intro: [
    { title: "Histoire et contexte", paragraphs: ["La numérologie étudie la signification symbolique des nombres et les interprète comme des archétypes exprimant des schémas de personnalité, d’apprentissage et de cycles d’expérience.", "Ses racines sont associées à l’ancienne Babylone, à la gematria hébraïque liée au Sefer Yetzirah, aux Védas de l’Inde et surtout à l’école pythagoricienne de la Grèce classique. Au VIe siècle av. J.-C., la pensée attribuée à Pythagore proposait de comprendre l’ordre de l’univers à travers les relations numériques.", "Dans cette vision, les nombres ne représentent pas seulement des quantités : ils agissent aussi comme des qualités symboliques. La lecture explore ces correspondances sans les transformer en déterminations absolues."] },
    { title: "Forme de consultation", paragraphs: ["La consultation utilise la réduction théosophique : les chiffres d’une date ou les valeurs des lettres sont additionnés jusqu’à obtenir un nombre de 1 à 9, tandis que 11, 22 et 33 sont conservés comme nombres maîtres lorsque la méthode le prévoit.", "Le Chemin de Vie utilise la date complète de naissance ; le Nombre d’Expression, toutes les lettres du nom de naissance ; le Nombre de l’Âme, uniquement ses voyelles ; et l’Année Personnelle relie le jour et le mois de naissance à l’année civile en cours."] },
    { title: "Clé d’interprétation", paragraphs: ["Le Chemin de Vie donne la direction structurelle, mais il doit être comparé à l’Année Personnelle pour comprendre le moment présent. Chaque année a sa fonction : 1 initie, 2 relie, 3 exprime, 4 consolide, 5 transforme, 6 responsabilise, 7 intériorise, 8 matérialise et 9 conclut.", "Une interprétation solide croise les nombres au lieu de les isoler et utilise l’intuition pour reconnaître comment leurs symboles se manifestent dans l’expérience concrète de la personne."] },
  ] },
  DE: { back: "Zurück zum Anfang", eyebrow: "ZAHL · ZYKLUS · BEDEUTUNG", title: "Numerologie", subtitle: "Die symbolische Architektur von Name und Datum", choose: "Schwerpunkt wählen", pending: "BERECHNUNG AUSSTEHEND", pendingDescription: "Das Datenformular und die numerologische Berechnung werden in der nächsten Phase ergänzt.", numberLabel: "Grundzahl", masterLabel: "Meisterzahl", focuses: [
    { symbol: "∑", title: "Lebenswegzahl", level: "Wesentlich · Wurzel", description: "Das vollständige Geburtsdatum als Leitlinie für Lernen und Lebensweg." },
    { symbol: "A", title: "Ausdruckszahl", level: "Identität · Ausdruck", description: "Der vollständige Geburtsname als Karte von Talenten und Fähigkeiten." },
    { symbol: "◉", title: "Seelenzahl", level: "Inneres · Wunsch", description: "Die Vokale des Namens als Zeichen tiefer Motivationen und Bedürfnisse." },
    { symbol: "↻", title: "Persönliches Jahr und Zyklen", level: "Dynamisch · Zeitlich", description: "Das symbolische Klima der Gegenwart und die aktive Phase des Neunjahreszyklus." },
  ], intro: [
    { title: "Geschichte und Kontext", paragraphs: ["Numerologie untersucht die symbolische Bedeutung der Zahlen und deutet sie als Archetypen für Persönlichkeit, Lernprozesse und Erfahrungszyklen.", "Ihre Wurzeln werden mit dem alten Babylonien, der hebräischen Gematria im Umfeld des Sefer Jetzira, den indischen Veden und besonders der pythagoreischen Schule des klassischen Griechenlands verbunden. Im 6. Jahrhundert v. Chr. schlug das Pythagoras zugeschriebene Denken vor, die Ordnung des Universums durch Zahlenverhältnisse zu verstehen.", "In diesem Weltbild sind Zahlen nicht nur Mengen, sondern auch symbolische Qualitäten. Die numerologische Deutung untersucht diese Entsprechungen, ohne sie zu absoluten Bestimmungen zu machen."] },
    { title: "Form der Beratung", paragraphs: ["Die Beratung nutzt die theosophische Reduktion: Ziffern eines Datums oder Buchstabenwerte werden addiert, bis eine Zahl von 1 bis 9 entsteht; 11, 22 und 33 bleiben als Meisterzahlen erhalten, wenn die gewählte Methode dies vorsieht.", "Die Lebenswegzahl wird aus dem vollständigen Geburtsdatum berechnet, die Ausdruckszahl aus allen Buchstaben des Geburtsnamens, die Seelenzahl nur aus den Vokalen und das Persönliche Jahr aus Geburtstag, Geburtsmonat und aktuellem Kalenderjahr."] },
    { title: "Schlüssel zur Deutung", paragraphs: ["Die Lebenswegzahl gibt die strukturelle Richtung vor, sollte aber mit dem Persönlichen Jahr verglichen werden. Jedes Jahr hat eine eigene Funktion: 1 beginnt, 2 verbindet, 3 drückt aus, 4 festigt, 5 verändert, 6 übernimmt Verantwortung, 7 verinnerlicht, 8 verwirklicht und 9 vollendet.", "Eine fundierte Deutung verbindet die Zahlen, statt sie zu isolieren, und nutzt Intuition, um ihre konkrete Resonanz in der Erfahrung eines Menschen zu erkennen."] },
  ] },
  PT: { back: "Voltar ao início", eyebrow: "NÚMERO · CICLO · SIGNIFICADO", title: "Numerologia", subtitle: "A arquitetura simbólica do nome e da data", choose: "Escolha o enfoque", pending: "CÁLCULO PENDENTE", pendingDescription: "O formulário de dados e o cálculo numerológico serão incorporados na próxima etapa.", numberLabel: "Número essencial", masterLabel: "Número mestre", focuses: [
    { symbol: "∑", title: "Número de Vida", level: "Essencial · Raiz", description: "A data completa de nascimento como orientação e caminho de aprendizagem." },
    { symbol: "A", title: "Número de Expressão", level: "Identidade · Manifestação", description: "O nome completo de nascimento como mapa de talentos e capacidades." },
    { symbol: "◉", title: "Número da Alma", level: "Interior · Desejo", description: "As vogais do nome como sinal de motivações e necessidades profundas." },
    { symbol: "↻", title: "Ano Pessoal e Ciclos", level: "Dinâmica · Temporal", description: "O clima simbólico do período e a etapa ativa do ciclo de nove anos." },
  ], intro: [
    { title: "História e contexto", paragraphs: ["A numerologia estuda o significado simbólico dos números e os interpreta como arquétipos que expressam padrões de personalidade, aprendizagem e ciclos de experiência.", "Suas raízes são associadas à antiga Babilônia, à gematria hebraica ligada ao Sefer Yetzirah, aos Vedas da Índia e especialmente à escola pitagórica da Grécia clássica. No século VI a.C., o pensamento atribuído a Pitágoras propôs compreender a ordem do universo por meio de relações numéricas.", "Nessa cosmovisão, os números não representam apenas quantidades: também atuam como qualidades simbólicas. A leitura numerológica explora essas correspondências sem transformá-las em determinações absolutas."] },
    { title: "Forma de consulta", paragraphs: ["A consulta utiliza a redução teosófica: somam-se os dígitos de uma data ou os valores das letras até obter um número de 1 a 9, preservando 11, 22 e 33 como números mestres quando o método escolhido assim determina.", "O Número de Vida usa a data completa de nascimento; o Número de Expressão, todas as letras do nome de nascimento; o Número da Alma, apenas suas vogais; e o Ano Pessoal relaciona o dia e o mês de nascimento ao ano vigente."] },
    { title: "Chave para a interpretação", paragraphs: ["O Número de Vida oferece a direção estrutural, mas deve ser comparado ao Ano Pessoal para compreender o momento atual. Cada ano tem uma função: 1 inicia, 2 conecta, 3 expressa, 4 consolida, 5 transforma, 6 responsabiliza, 7 interioriza, 8 materializa e 9 conclui.", "Uma interpretação sólida cruza os números em vez de isolá-los e utiliza a intuição para reconhecer como seus símbolos se manifestam na experiência concreta da pessoa."] },
  ] },
};

const meanings: Record<Language, string[]> = {
  ES: ["Inicio, autonomía y voluntad.","Cooperación, sensibilidad y vínculo.","Expresión, creatividad y comunicación.","Estructura, constancia y fundamento.","Cambio, libertad y adaptación.","Responsabilidad, cuidado y armonía.","Introspección, análisis y sabiduría.","Gestión, poder y realización.","Cierre, servicio y amplitud.","Intuición e inspiración amplificadas.","Visión aplicada y construcción colectiva.","Servicio compasivo y enseñanza."],
  EN: ["Beginnings, autonomy, and will.","Cooperation, sensitivity, and connection.","Expression, creativity, and communication.","Structure, consistency, and foundation.","Change, freedom, and adaptation.","Responsibility, care, and harmony.","Introspection, analysis, and wisdom.","Management, power, and achievement.","Completion, service, and breadth.","Heightened intuition and inspiration.","Applied vision and collective building.","Compassionate service and teaching."],
  FR: ["Début, autonomie et volonté.","Coopération, sensibilité et lien.","Expression, créativité et communication.","Structure, constance et fondement.","Changement, liberté et adaptation.","Responsabilité, soin et harmonie.","Introspection, analyse et sagesse.","Gestion, pouvoir et réalisation.","Achèvement, service et ampleur.","Intuition et inspiration amplifiées.","Vision appliquée et construction collective.","Service compatissant et enseignement."],
  DE: ["Beginn, Selbstständigkeit und Wille.","Zusammenarbeit, Sensibilität und Bindung.","Ausdruck, Kreativität und Kommunikation.","Struktur, Beständigkeit und Grundlage.","Wandel, Freiheit und Anpassung.","Verantwortung, Fürsorge und Harmonie.","Innenschau, Analyse und Weisheit.","Führung, Kraft und Verwirklichung.","Abschluss, Dienst und Weite.","Verstärkte Intuition und Inspiration.","Angewandte Vision und gemeinsamer Aufbau.","Mitfühlender Dienst und Lehre."],
  PT: ["Início, autonomia e vontade.","Cooperação, sensibilidade e vínculo.","Expressão, criatividade e comunicação.","Estrutura, constância e fundamento.","Mudança, liberdade e adaptação.","Responsabilidade, cuidado e harmonia.","Introspecção, análise e sabedoria.","Gestão, poder e realização.","Conclusão, serviço e amplitude.","Intuição e inspiração ampliadas.","Visão aplicada e construção coletiva.","Serviço compassivo e ensino."],
};

const libraryNumbers = [1,2,3,4,5,6,7,8,9,11,22,33];
const resultsBack:Record<Language,string>={ES:"Volver a los enfoques",EN:"Back to focuses",FR:"Retour aux approches",DE:"Zurück zu den Schwerpunkten",PT:"Voltar aos enfoques"};

export function NumerologySite({ lang, onBack, selected, consultationOpen, onSelect, onCloseConsultation,onOpenProfile }: { lang: Language; onBack: () => void; selected: number | null; consultationOpen: boolean; onSelect: (index: number, focus: string) => void; onCloseConsultation: () => void;onOpenProfile?:()=>void }) {
  const text = content[lang];
  const library: DisciplineLibraryItem[] = libraryNumbers.map((number, index) => ({ id: `number-${number}`, name: `${text.numberLabel} ${number}`, category: number > 9 ? text.masterLabel : text.numberLabel, description: meanings[lang][index], symbol: String(number), image:"/oracles/numerology/number-medallion-base-v1.webp", visual:"astro-medallion", tone:"numerology" }));
  const focus = selected === null ? null : text.focuses[selected];

  useEffect(() => { window.scrollTo({ top: 0, behavior: "smooth" }); }, []);

  if (consultationOpen && focus) return <section className="astrology-site numerology-site astrology-results-page">
    <button type="button" className="astrology-back" onClick={onCloseConsultation}>← {resultsBack[lang]}</button>
    <AstroConsultationFlow discipline="numerology" focus={focus.title} focusIndex={selected!} lang={lang} fromProfile onOpenProfile={onOpenProfile} />
  </section>;

  return <section className="astrology-site numerology-site">
    <button type="button" className="astrology-back" onClick={onBack}>← {text.back}</button>
    <header className="astrology-heading"><span>{text.eyebrow}</span><h1>{text.title}</h1><strong>{text.subtitle}</strong><div className="astrology-introduction-sections">{text.intro.map(section => <section key={section.title}><h2>{section.title}</h2>{section.paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</section>)}</div></header>
    <section className="astrology-focus-panel" aria-labelledby="numerology-focus-title"><span className="astrology-mini-label" id="numerology-focus-title">{text.choose}</span><div className="astrology-focus-grid">{text.focuses.map((item, index) => <button type="button" className={selected === index ? "selected" : ""} onClick={() => onSelect(index, item.title)} key={item.title}><i aria-hidden="true">{item.symbol}</i><span><small>{item.level}</small><b>{item.title}</b><em>{item.description}</em></span><strong aria-hidden="true">{selected === index ? "✓" : "+"}</strong></button>)}</div></section>
    <CollapsibleDisciplineLibrary lang={lang} items={library}/>
  </section>;
}
