"use client";

import {useMemo,useState,type CSSProperties,type ReactNode} from "react";
import "./pendulum-experience.css";

export type PendulumExperienceProps={enfoque:string;angulo:number;intensidad:number;interpretacion?:ReactNode;onComplete?:()=>void};
type Phase="ready"|"swinging"|"waiting"|"result";
const normalizeAngle=(value:number)=>((value%360)+360)%360;
function pendulumAnswer(angle:number){const value=normalizeAngle(angle);if(value>=315||value<45)return "NO";if(value>=135&&value<225)return "SÍ";return "NEUTRAL"}

export default function PendulumExperience({enfoque,angulo,intensidad,interpretacion,onComplete}:PendulumExperienceProps){
 const [phase,setPhase]=useState<Phase>("ready"),safeAngle=normalizeAngle(angulo),safeIntensity=Math.max(0,Math.min(100,Math.round(intensidad))),answer=pendulumAnswer(safeAngle);
 const arrow=useMemo(()=>{const radians=(safeAngle-90)*Math.PI/180,radius=35;return{x:50+Math.cos(radians)*radius,y:50+Math.sin(radians)*radius}},[safeAngle]);
 function activate(){if(phase==="ready"){setPhase("swinging");window.setTimeout(()=>setPhase("waiting"),3600);return}if(phase==="waiting"){setPhase("result");onComplete?.()}}
 if(phase==="result")return <section className="pendulum-result" aria-live="polite"><header className="pendulum-step-title"><span>RESPUESTA RADIESTÉSICA</span><h1>{enfoque}</h1></header><div className="pendulum-result-grid"><article className="pendulum-board-panel"><div className="pendulum-board-visual"><img src="/oracles/pendulum/radiesthesia-board.svg" alt="Tablero radiestésico visto desde arriba"/><svg viewBox="0 0 100 100" aria-label={`Dirección del péndulo: ${safeAngle} grados`}><defs><marker id="pendulum-arrowhead" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z"/></marker></defs><circle cx="50" cy="50" r="3.2"/><line x1="50" y1="50" x2={arrow.x} y2={arrow.y} markerEnd="url(#pendulum-arrowhead)"/></svg><strong className={`pendulum-board-answer answer-${answer.toLowerCase().replace("í","i")}`}>{answer}</strong></div><small>DIRECCIÓN · {Math.round(safeAngle)}°</small></article><article className="pendulum-reading-panel"><span className="pendulum-reading-label">RESPUESTA</span><p className="pendulum-answer"><b>{answer}</b><i>·</i><strong>{safeIntensity}%</strong><small>intensidad</small></p><div className="pendulum-intensity" aria-label={`Intensidad ${safeIntensity} por ciento`}><i style={{"--intensity":`${safeIntensity}%`} as CSSProperties}/></div><span className="pendulum-reading-label">MENSAJE E INTERPRETACIÓN</span><h2>Lo que el péndulo revela</h2><div className="pendulum-ai-copy">{interpretacion||<p>La interpretación se mostrará aquí cuando el motor de inteligencia artificial termine de analizar la consulta.</p>}</div></article></div></section>;
 const instruction=phase==="ready"?`Antes de hacer click, concéntrate en tu pregunta sobre ${enfoque}.`:phase==="swinging"?"Mantén tu atención en la pregunta mientras el péndulo encuentra su movimiento.":"El movimiento terminó. Haz click para ver la respuesta.";
 return <section className={`pendulum-presentation phase-${phase}`}><header className="pendulum-step-title"><span>CONSULTA CON PÉNDULO</span><h1>{enfoque}</h1><p>{instruction}</p></header><button className="pendulum-photo-action" type="button" onClick={activate} disabled={phase==="swinging"} aria-label={phase==="waiting"?"Ver la respuesta del péndulo":"Activar péndulo"}><img src="/oracles/pendulum/silver-witness-pendulum-held.jpg" alt="Péndulo de plata sostenido por una mano"/><span className="pendulum-photo-shade"/><span className="animated-silver-pendulum" aria-hidden="true"><i/><b/></span><span className="pendulum-action-copy">{phase==="ready"?"Activar péndulo":phase==="swinging"?"El péndulo está en movimiento…":"Haz click para ver la respuesta"}</span></button></section>;
}
