"use client";

import { useEffect, useMemo, useState } from "react";
import type { Language } from "../translations";
import { useUserProfile } from "../hooks/useUserProfile";
import { isAstroProfileComplete, type UserProfileData } from "../user-profile";
import { calculateAllAstros } from "./astro-full-calculations";
import type { AstroConsultationPayload, AstroDiscipline } from "./AstroConsultationFlow";
import { buildImago, buildReflexus, readReflexusCache, reflexusKeys, writeReflexusCache, type ImagoArea, type ImagoReport, type ReflexusReport, type ReflexusSignal } from "./reflexus-engine";
import type { ReflexusArea } from "./reflexus-config";
import { buildImagoAreaDeterministicInterpretation, buildImagoDeterministicInterpretation, buildReflexusDeterministicInterpretation, type DeterministicInterpretationSection } from "./reflexus-deterministic-interpretation";
import "./reflexus-sites.css";
import "./reflexus-temporal.css";

const areaNames: Record<Language, Record<ReflexusArea, string>> = {
  ES: { identity:"Identidad y expresión",emotions:"Emociones y mundo interior",relationships:"Amor y relaciones",vocation:"Profesión y vocación",resources:"Dinero y recursos",health:"Salud y equilibrio",family:"Familia y raíces",learning:"Retos y aprendizajes",spirituality:"Espiritualidad y propósito",transformation:"Transformación y evolución",direction:"Dirección y ciclos" },
  EN: { identity:"Identity and expression",emotions:"Emotions and inner world",relationships:"Love and relationships",vocation:"Profession and vocation",resources:"Money and resources",health:"Health and balance",family:"Family and roots",learning:"Challenges and learning",spirituality:"Spirituality and purpose",transformation:"Transformation and evolution",direction:"Direction and cycles" },
  FR: { identity:"Identité et expression",emotions:"Émotions et monde intérieur",relationships:"Amour et relations",vocation:"Profession et vocation",resources:"Argent et ressources",health:"Santé et équilibre",family:"Famille et racines",learning:"Défis et apprentissages",spirituality:"Spiritualité et but",transformation:"Transformation et évolution",direction:"Direction et cycles" },
  DE: { identity:"Identität und Ausdruck",emotions:"Emotionen und Innenwelt",relationships:"Liebe und Beziehungen",vocation:"Beruf und Berufung",resources:"Geld und Ressourcen",health:"Gesundheit und Gleichgewicht",family:"Familie und Wurzeln",learning:"Herausforderungen und Lernen",spirituality:"Spiritualität und Sinn",transformation:"Transformation und Entwicklung",direction:"Richtung und Zyklen" },
  PT: { identity:"Identidade e expressão",emotions:"Emoções e mundo interior",relationships:"Amor e relações",vocation:"Profissão e vocação",resources:"Dinheiro e recursos",health:"Saúde e equilíbrio",family:"Família e raízes",learning:"Desafios e aprendizados",spirituality:"Espiritualidade e propósito",transformation:"Transformação e evolução",direction:"Direção e ciclos" },
};

const copy: Record<Language, Record<string, string>> = {
  ES:{back:"Volver",eyebrow:"LECTURA DETERMINÍSTICA INTEGRADA",your:"TU REFLEXUS",western:"Astrología Occidental",eastern:"Astrología Oriental",numerology:"Numerología",structure:"TU ESTRUCTURA",present:"TU PRESENTE",trend:"TU TENDENCIA",highlighted:"ÁREAS DESTACADAS",evidence:"Ver evidencia calculada",hide:"Ocultar evidencia",relevance:"Relevancia interna",strength:"Soporte de la señal",loading:"Calculando tu REFLEXUS…",error:"No fue posible completar el cálculo.",account:"Crea una cuenta o inicia sesión para usar los datos de tu perfil.",profile:"Completa tu perfil astrológico para realizar el cálculo.",imago:"IMAGO SPECULI",imagoSub:"Tres reflejos. Una imagen.",imagoDesc:"Tres sistemas independientes. Una imagen integrada. Descubre dónde convergen, dónde contrastan y qué temas dominan tu momento.",sources:"ESTADO DE LOS TRES REFLEXUS",dominant:"TEMAS DOMINANTES",matrix:"MATRIZ DE CONVERGENCIA",openArea:"Abrir área",convergence:"Convergencia",consistency:"Consistencia",contrast:"CONTRASTES Y COMPLEMENTOS",temporality:"CAPAS TEMPORALES",facts:"EVIDENCIA TRAZABLE",insufficient:"Datos insuficientes",versions:"Versiones y referencia",retry:"Intentar de nuevo"},
  EN:{back:"Back",eyebrow:"INTEGRATED DETERMINISTIC READING",your:"YOUR REFLEXUS",western:"Western Astrology",eastern:"Eastern Astrology",numerology:"Numerology",structure:"YOUR STRUCTURE",present:"YOUR PRESENT",trend:"YOUR TREND",highlighted:"HIGHLIGHTED AREAS",evidence:"View calculated evidence",hide:"Hide evidence",relevance:"Internal relevance",strength:"Signal support",loading:"Calculating your REFLEXUS…",error:"The calculation could not be completed.",account:"Create an account or sign in to use your profile data.",profile:"Complete your astrological profile to perform the calculation.",imago:"IMAGO SPECULI",imagoSub:"Three reflections. One image.",imagoDesc:"Three independent systems. One integrated image. Discover where they converge, where they contrast, and which themes dominate your present moment.",sources:"STATUS OF THE THREE REFLEXUS",dominant:"DOMINANT THEMES",matrix:"CONVERGENCE MATRIX",openArea:"Open area",convergence:"Convergence",consistency:"Consistency",contrast:"CONTRASTS AND COMPLEMENTS",temporality:"TEMPORAL LAYERS",facts:"TRACEABLE EVIDENCE",insufficient:"Insufficient data",versions:"Versions and reference",retry:"Try again"},
  FR:{back:"Retour",eyebrow:"LECTURE DÉTERMINISTE INTÉGRÉE",your:"VOTRE REFLEXUS",western:"Astrologie occidentale",eastern:"Astrologie orientale",numerology:"Numérologie",structure:"VOTRE STRUCTURE",present:"VOTRE PRÉSENT",trend:"VOTRE TENDANCE",highlighted:"DOMAINES PRINCIPAUX",evidence:"Voir les preuves calculées",hide:"Masquer les preuves",relevance:"Pertinence interne",strength:"Soutien du signal",loading:"Calcul de votre REFLEXUS…",error:"Le calcul n’a pas pu être terminé.",account:"Créez un compte ou connectez-vous pour utiliser votre profil.",profile:"Complétez votre profil astrologique pour effectuer le calcul.",imago:"IMAGO SPECULI",imagoSub:"Trois reflets. Une image.",imagoDesc:"Trois systèmes indépendants. Une image intégrée. Découvrez leurs convergences, leurs contrastes et les thèmes dominants du moment.",sources:"ÉTAT DES TROIS REFLEXUS",dominant:"THÈMES DOMINANTS",matrix:"MATRICE DE CONVERGENCE",openArea:"Ouvrir le domaine",convergence:"Convergence",consistency:"Cohérence",contrast:"CONTRASTES ET COMPLÉMENTS",temporality:"COUCHES TEMPORELLES",facts:"PREUVES TRAÇABLES",insufficient:"Données insuffisantes",versions:"Versions et référence",retry:"Réessayer"},
  DE:{back:"Zurück",eyebrow:"INTEGRIERTE DETERMINISTISCHE LESUNG",your:"IHR REFLEXUS",western:"Westliche Astrologie",eastern:"Östliche Astrologie",numerology:"Numerologie",structure:"IHRE STRUKTUR",present:"IHRE GEGENWART",trend:"IHRE TENDENZ",highlighted:"HERVORGEHOBENE BEREICHE",evidence:"Berechnete Belege anzeigen",hide:"Belege ausblenden",relevance:"Interne Relevanz",strength:"Signalunterstützung",loading:"Ihr REFLEXUS wird berechnet…",error:"Die Berechnung konnte nicht abgeschlossen werden.",account:"Erstellen Sie ein Konto oder melden Sie sich an, um Ihre Profildaten zu verwenden.",profile:"Vervollständigen Sie Ihr astrologisches Profil für die Berechnung.",imago:"IMAGO SPECULI",imagoSub:"Drei Spiegelungen. Ein Bild.",imagoDesc:"Drei unabhängige Systeme. Ein integriertes Bild. Erkennen Sie Übereinstimmungen, Kontraste und die dominanten Themen Ihres Augenblicks.",sources:"STATUS DER DREI REFLEXUS",dominant:"DOMINANTE THEMEN",matrix:"KONVERGENZMATRIX",openArea:"Bereich öffnen",convergence:"Konvergenz",consistency:"Konsistenz",contrast:"KONTRASTE UND ERGÄNZUNGEN",temporality:"ZEITEBENEN",facts:"NACHVOLLZIEHBARE BELEGE",insufficient:"Unzureichende Daten",versions:"Versionen und Referenz",retry:"Erneut versuchen"},
  PT:{back:"Voltar",eyebrow:"LEITURA DETERMINÍSTICA INTEGRADA",your:"SEU REFLEXUS",western:"Astrologia Ocidental",eastern:"Astrologia Oriental",numerology:"Numerologia",structure:"SUA ESTRUTURA",present:"SEU PRESENTE",trend:"SUA TENDÊNCIA",highlighted:"ÁREAS EM DESTAQUE",evidence:"Ver evidência calculada",hide:"Ocultar evidência",relevance:"Relevância interna",strength:"Suporte do sinal",loading:"Calculando seu REFLEXUS…",error:"Não foi possível concluir o cálculo.",account:"Crie uma conta ou entre para usar os dados do seu perfil.",profile:"Complete seu perfil astrológico para realizar o cálculo.",imago:"IMAGO SPECULI",imagoSub:"Três reflexos. Uma imagem.",imagoDesc:"Três sistemas independentes. Uma imagem integrada. Descubra onde convergem, onde contrastam e quais temas dominam seu momento.",sources:"ESTADO DOS TRÊS REFLEXUS",dominant:"TEMAS DOMINANTES",matrix:"MATRIZ DE CONVERGÊNCIA",openArea:"Abrir área",convergence:"Convergência",consistency:"Consistência",contrast:"CONTRASTES E COMPLEMENTOS",temporality:"CAMADAS TEMPORAIS",facts:"EVIDÊNCIA RASTREÁVEL",insufficient:"Dados insuficientes",versions:"Versões e referência",retry:"Tentar novamente"},
};

const supplementalCopy: Record<Language, {openAccount:string;openProfile:string;who:string;where:string;changing:string;next:string}> = {
  ES:{openAccount:"Crear cuenta o iniciar sesión",openProfile:"Completar mi perfil",who:"QUIÉN ERES",where:"DÓNDE ESTÁS",changing:"QUÉ ESTÁ CAMBIANDO",next:"QUÉ SIGUE"},
  EN:{openAccount:"Create account or sign in",openProfile:"Complete my profile",who:"WHO YOU ARE",where:"WHERE YOU ARE",changing:"WHAT IS CHANGING",next:"WHAT COMES NEXT"},
  FR:{openAccount:"Créer un compte ou se connecter",openProfile:"Compléter mon profil",who:"QUI VOUS ÊTES",where:"OÙ VOUS ÊTES",changing:"CE QUI CHANGE",next:"CE QUI SUIT"},
  DE:{openAccount:"Konto erstellen oder anmelden",openProfile:"Profil vervollständigen",who:"WER SIE SIND",where:"WO SIE STEHEN",changing:"WAS SICH VERÄNDERT",next:"WAS ALS NÄCHSTES KOMMT"},
  PT:{openAccount:"Criar conta ou entrar",openProfile:"Completar meu perfil",who:"QUEM VOCÊ É",where:"ONDE VOCÊ ESTÁ",changing:"O QUE ESTÁ MUDANDO",next:"O QUE VEM A SEGUIR"},
};

const reflexusProductCopy: Record<Language, Record<AstroDiscipline,{subtitle:string;description:string}>> = {
  ES:{western:{subtitle:"Tu perfil occidental integrado",description:"Reúne tu estructura natal, tu momento actual y tus principales tendencias en una sola visión."},eastern:{subtitle:"Tu perfil oriental integrado",description:"Integra tu estructura BaZi, el equilibrio de elementos, tus ciclos y los palacios de Zi Wei Dou Shu."},numerology:{subtitle:"Tu perfil numerológico integrado",description:"Reúne tus números estructurales, motivaciones, talentos, retos y ciclos personales."}},
  EN:{western:{subtitle:"Your integrated Western profile",description:"Brings together your natal structure, current moment, and main trends in a single view."},eastern:{subtitle:"Your integrated Eastern profile",description:"Integrates your BaZi structure, elemental balance, cycles, and Zi Wei Dou Shu palaces."},numerology:{subtitle:"Your integrated numerology profile",description:"Brings together your structural numbers, motivations, talents, challenges, and personal cycles."}},
  FR:{western:{subtitle:"Votre profil occidental intégré",description:"Réunit votre structure natale, votre moment actuel et vos principales tendances en une seule vue."},eastern:{subtitle:"Votre profil oriental intégré",description:"Intègre votre structure BaZi, l’équilibre des éléments, vos cycles et les palais du Zi Wei Dou Shu."},numerology:{subtitle:"Votre profil numérologique intégré",description:"Réunit vos nombres structurels, motivations, talents, défis et cycles personnels."}},
  DE:{western:{subtitle:"Ihr integriertes westliches Profil",description:"Vereint Ihre Geburtsstruktur, den aktuellen Moment und die wichtigsten Tendenzen in einer Ansicht."},eastern:{subtitle:"Ihr integriertes östliches Profil",description:"Integriert Ihre BaZi-Struktur, das Gleichgewicht der Elemente, Ihre Zyklen und die Zi-Wei-Dou-Shu-Paläste."},numerology:{subtitle:"Ihr integriertes Numerologieprofil",description:"Vereint Ihre strukturellen Zahlen, Motivationen, Talente, Herausforderungen und persönlichen Zyklen."}},
  PT:{western:{subtitle:"Seu perfil ocidental integrado",description:"Reúne sua estrutura natal, seu momento atual e suas principais tendências em uma única visão."},eastern:{subtitle:"Seu perfil oriental integrado",description:"Integra sua estrutura BaZi, o equilíbrio dos elementos, seus ciclos e os palácios do Zi Wei Dou Shu."},numerology:{subtitle:"Seu perfil numerológico integrado",description:"Reúne seus números estruturais, motivações, talentos, desafios e ciclos pessoais."}},
};

function payloadFromProfile(profile: UserProfileData, discipline: AstroDiscipline, lang: Language): AstroConsultationPayload {
  return { discipline, focus:"REFLEXUS", language:lang, name:profile.currentName||profile.fullName, birthName:profile.fullName, currentName:profile.currentName, birthDate:profile.birthDate, birthTime:`${profile.birthHour}:${profile.birthMinute}`, birthPlace:`${profile.birthCity}, ${profile.birthCountry}`, currentPlace:profile.currentCity&&profile.currentCountry?`${profile.currentCity}, ${profile.currentCountry}`:"", timezone:profile.timezone, targetDate:new Date().toISOString().slice(0,10), calendar:profile.calendar, gender:profile.gender, question:"" };
}

async function loadReport(profile: UserProfileData, discipline: AstroDiscipline, lang: Language) {
  const payload = payloadFromProfile(profile, discipline, lang);
  const key = reflexusKeys(payload).temporalKey;
  const cached = readReflexusCache(discipline, key);
  if (cached) return cached;
  const calculation = await calculateAllAstros(payload);
  const report = buildReflexus(discipline, payload, calculation);
  writeReflexusCache(report);
  return report;
}

function EvidenceList({ report, signals, text }: { report:ReflexusReport; signals:ReflexusSignal[]; text:Record<string,string> }) {
  const [open,setOpen]=useState(false);
  return <div className="reflexus-evidence"><button type="button" onClick={()=>setOpen(value=>!value)}>{open?text.hide:text.evidence} <span>{open?"−":"+"}</span></button>{open&&<div className="reflexus-evidence-list">{signals.map(signal=><article key={signal.id}><small>{signal.source.replaceAll("_"," ")} · {signal.temporalClass.replaceAll("_"," ")}</small><b>{signal.label}</b><p>{text.relevance}: {signal.relevance}/100 · {text.strength}: {signal.evidenceStrength}/100</p><code>{signal.evidenceIds.join(" · ")}</code></article>)}</div>}<small className="reflexus-version">{text.versions}: {report.engineVersion} · {report.rulesVersion} · {report.referenceDate} · {report.timezone}</small></div>;
}

function DeterministicInterpretation({title,summary,sections,method,evidenceLabel}:{title:string;summary:string;sections:DeterministicInterpretationSection[];method:string;evidenceLabel:string}) {
  return <section className="deterministic-interpretation"><div className="deterministic-heading"><small>{title}</small><span aria-hidden="true">◎</span></div><p className="deterministic-summary">{summary}</p><div className="deterministic-sections">{sections.map((section,index)=><article key={section.id}><span>{String(index+1).padStart(2,"0")}</span><div><h2>{section.title}</h2><p>{section.text}</p><details><summary>{evidenceLabel}</summary><code>{section.evidenceIds.join(" · ")}</code></details></div></article>)}</div><p className="deterministic-method">{method}</p></section>;
}

function ReportStatus({ lang, message, onBack, action, actionLabel }: {lang:Language;message:string;onBack:()=>void;action?:()=>void;actionLabel?:string}) { const t=copy[lang]; return <section className="reflexus-page"><button className="astrology-back" onClick={onBack}>← {t.back}</button><div className="reflexus-status"><span>◉</span><h1>{message}</h1>{action&&<button onClick={action}>{actionLabel||t.retry}</button>}</div></section>; }

export function ReflexusSite({ discipline, lang, onBack, onOpenProfile, onOpenAccount }:{discipline:AstroDiscipline;lang:Language;onBack:()=>void;onOpenProfile:()=>void;onOpenAccount:()=>void}) {
  const {user,profile,loading:profileLoading}=useUserProfile();
  const [report,setReport]=useState<ReflexusReport|null>(null);
  const [error,setError]=useState("");
  const [retry,setRetry]=useState(0);
  const t=copy[lang];
  useEffect(()=>{let active=true;if(profileLoading||!user||!isAstroProfileComplete(profile))return;setError("");void loadReport(profile,discipline,lang).then(value=>{if(active)setReport(value)}).catch(cause=>{console.error("REFLEXUS calculation failed",cause);if(active)setError(t.error)});return()=>{active=false}},[discipline,lang,profile,profileLoading,retry,t.error,user]);
  if(profileLoading)return <ReportStatus lang={lang} message={t.loading} onBack={onBack}/>;
  if(!user)return <ReportStatus lang={lang} message={t.account} onBack={onBack} action={onOpenAccount} actionLabel={supplementalCopy[lang].openAccount}/>;
  if(!isAstroProfileComplete(profile))return <ReportStatus lang={lang} message={t.profile} onBack={onBack} action={onOpenProfile} actionLabel={supplementalCopy[lang].openProfile}/>;
  if(error)return <ReportStatus lang={lang} message={error} onBack={onBack} action={()=>setRetry(value=>value+1)}/>;
  if(!report)return <ReportStatus lang={lang} message={t.loading} onBack={onBack}/>;
  const dominant=report.areas.slice(0,6);
  const product=reflexusProductCopy[lang][discipline];
  const interpretation=buildReflexusDeterministicInterpretation(report,lang);
  const groups=[
    {title:t.structure,classes:discipline==="eastern"?["structure","balance"]:discipline==="numerology"?["structure","stage"]:["structure"]},
    {title:t.present,classes:discipline==="eastern"?["present","current_cycle"]:discipline==="numerology"?["present"]:["present"]},
    {title:t.trend,classes:["trend"]},
  ];
  return <section className={`reflexus-page reflexus-${discipline}`}><button className="astrology-back" onClick={onBack}>← {t.back}</button><header className="reflexus-hero"><small>{t[discipline]}</small><h1>{t.your}</h1><strong>{product.subtitle}</strong><p>{product.description}</p><p>{report.referenceDate} · {report.timezone}</p></header><section className="reflexus-ranking"><small>{t.highlighted}</small><div>{dominant.map(item=><article key={item.area}><span>{String(item.rank).padStart(2,"0")}</span><div><h2>{areaNames[lang][item.area]}</h2><p>{t.relevance}: {item.relevance}/100 · {t.strength}: {item.evidenceStrength}/100</p></div></article>)}</div></section><DeterministicInterpretation title={interpretation.title} summary={interpretation.summary} sections={interpretation.sections} method={interpretation.method} evidenceLabel={t.facts}/>{groups.map(group=>{const signals=report.signals.filter(signal=>group.classes.includes(signal.temporalClass)).sort((a,b)=>b.relevance-a.relevance);return <section className="reflexus-layer" key={group.title}><div className="reflexus-layer-title"><small>{group.title}</small><b>{signals.length}</b></div><div className="reflexus-area-grid">{report.areas.filter(area=>area.signalIds.some(id=>signals.some(signal=>signal.id===id))).slice(0,6).map(area=><article key={area.area}><small>{area.dominantClass}</small><h3>{areaNames[lang][area.area]}</h3><div className="reflexus-meter"><i style={{width:`${area.relevance}%`}}/></div><p>{area.relevance}/100</p></article>)}</div><EvidenceList report={report} signals={signals.slice(0,18)} text={t}/></section>})}<div className="ai-slot" hidden data-ai-slot="reflexus-summary" data-engine={discipline}/><div className="ai-slot" hidden data-ai-slot="reflexus-who-you-are" data-engine={discipline}/><div className="ai-slot" hidden data-ai-slot="reflexus-present" data-engine={discipline}/><div className="ai-slot" hidden data-ai-slot="reflexus-trend" data-engine={discipline}/></section>;
}

function engineName(lang:Language,engine:AstroDiscipline){return copy[lang][engine]}

export function ImagoSpeculiSite({lang,onBack,onOpenProfile,onOpenAccount}:{lang:Language;onBack:()=>void;onOpenProfile:()=>void;onOpenAccount:()=>void}) {
  const {user,profile,loading:profileLoading}=useUserProfile();
  const [reports,setReports]=useState<Record<AstroDiscipline,ReflexusReport>|null>(null);
  const [imago,setImago]=useState<ImagoReport|null>(null);
  const [selected,setSelected]=useState<ImagoArea|null>(null);
  const [error,setError]=useState("");
  const [retry,setRetry]=useState(0);
  const t=copy[lang];
  useEffect(()=>{let active=true;if(profileLoading||!user||!isAstroProfileComplete(profile))return;setError("");void Promise.all((["western","eastern","numerology"] as AstroDiscipline[]).map(engine=>loadReport(profile,engine,lang))).then(values=>{if(!active)return;const source={western:values[0],eastern:values[1],numerology:values[2]};setReports(source);setImago(buildImago(source))}).catch(cause=>{console.error("IMAGO SPECULI calculation failed",cause);if(active)setError(t.error)});return()=>{active=false}},[lang,profile,profileLoading,retry,t.error,user]);
  if(profileLoading)return <ReportStatus lang={lang} message={t.loading} onBack={onBack}/>;
  if(!user)return <ReportStatus lang={lang} message={t.account} onBack={onBack} action={onOpenAccount} actionLabel={supplementalCopy[lang].openAccount}/>;
  if(!isAstroProfileComplete(profile))return <ReportStatus lang={lang} message={t.profile} onBack={onBack} action={onOpenProfile} actionLabel={supplementalCopy[lang].openProfile}/>;
  if(error)return <ReportStatus lang={lang} message={error} onBack={onBack} action={()=>setRetry(value=>value+1)}/>;
  if(!imago||!reports)return <ReportStatus lang={lang} message={t.loading} onBack={onBack}/>;
  if(selected)return <ImagoAreaReport lang={lang} area={selected} reports={reports} onBack={()=>setSelected(null)}/>;
  const layers=supplementalCopy[lang];
  const temporalLayers=[{label:layers.who,classes:["structure"]},{label:layers.where,classes:["present"]},{label:layers.changing,classes:["balance","stage","current_cycle"]},{label:layers.next,classes:["trend"]}];
  const contrasts=imago.areas.filter(area=>["divergent","mixed","complementary"].includes(area.consistency)).slice(0,4);
  const interpretation=buildImagoDeterministicInterpretation(imago,lang);
  return <section className="reflexus-page imago-page"><button className="astrology-back" onClick={onBack}>← {t.back}</button><header className="reflexus-hero imago-hero"><small>{t.eyebrow}</small><h1>{t.imago}</h1><strong>{t.imagoSub}</strong><p>{t.imagoDesc}</p></header><section className="imago-source-status"><small>{t.sources}</small><div>{(["western","eastern","numerology"] as AstroDiscipline[]).map(engine=><article key={engine}><span>✓</span><div><b>{engineName(lang,engine)} REFLEXUS</b><p>{reports[engine].referenceDate} · v{reports[engine].engineVersion}</p></div></article>)}</div></section><section className="imago-dominant"><small>{t.dominant}</small><div>{imago.areas.slice(0,5).map((area,index)=><button onClick={()=>setSelected(area)} key={area.area}><span>{index+1}</span><h2>{areaNames[lang][area.area]}</h2><p>{area.convergence} · {area.consistency}</p><b>{area.relevance}/100 →</b></button>)}</div></section><DeterministicInterpretation title={interpretation.title} summary={interpretation.summary} sections={interpretation.sections} method={interpretation.method} evidenceLabel={t.facts}/><section className="imago-temporal"><small>{t.temporality}</small><div>{temporalLayers.map(layer=>{const matches=imago.areas.filter(area=>area.temporalClasses.some(item=>layer.classes.includes(item))).slice(0,3);return <article key={layer.label}><small>{layer.label}</small>{matches.length?matches.map(area=><button key={area.area} onClick={()=>setSelected(area)}>{areaNames[lang][area.area]} <span>{area.relevance}</span></button>):<p>{t.insufficient}</p>}</article>})}</div></section><section className="imago-contrasts"><small>{t.contrast}</small><div>{contrasts.length?contrasts.map(area=><button key={area.area} onClick={()=>setSelected(area)}><b>{areaNames[lang][area.area]}</b><span>{area.consistency} · {area.convergence}</span></button>):<p>{t.insufficient}</p>}</div></section><section className="imago-matrix"><small>{t.matrix}</small><div className="imago-table"><div className="imago-row imago-head"><b></b><b>{engineName(lang,"western")}</b><b>{engineName(lang,"eastern")}</b><b>{engineName(lang,"numerology")}</b><b>{t.convergence}</b></div>{imago.areas.map(area=><button className="imago-row" onClick={()=>setSelected(area)} key={area.area}><b>{areaNames[lang][area.area]}</b>{area.engines.map(engine=><span key={engine.engine}>{engine.relevance}<small>#{engine.rank}</small></span>)}<strong>{area.convergence}</strong></button>)}</div></section><div className="ai-slot" hidden data-ai-slot="imago-summary"/><div className="ai-slot" hidden data-ai-slot="imago-who-you-are"/><div className="ai-slot" hidden data-ai-slot="imago-present"/><div className="ai-slot" hidden data-ai-slot="imago-trend"/><footer className="imago-version">{t.versions}: {imago.engineVersion} · {imago.rulesVersion} · {imago.referenceDate} · {imago.timezone}</footer></section>;
}

function ImagoAreaReport({lang,area,reports,onBack}:{lang:Language;area:ImagoArea;reports:Record<AstroDiscipline,ReflexusReport>;onBack:()=>void}) {
  const t=copy[lang];
  const evidence=useMemo(()=>area.engines.map(engine=>({engine:engine.engine,signals:reports[engine.engine].signals.filter(signal=>engine.signalIds.includes(signal.id))})),[area,reports]);
  const interpretation=buildImagoAreaDeterministicInterpretation(area,lang);
  return <section className="reflexus-page imago-page imago-area-page"><button className="astrology-back" onClick={onBack}>← {t.back}</button><header className="reflexus-hero imago-hero"><small>{t.imago} · {area.convergence}</small><h1>{areaNames[lang][area.area]}</h1><strong>{t.consistency}: {area.consistency}</strong></header><DeterministicInterpretation title={interpretation.title} summary={interpretation.text} sections={[]} method={buildImagoDeterministicInterpretation(buildImago(reports),lang).method} evidenceLabel={t.facts}/><div className="imago-three-columns">{evidence.map(column=><article key={column.engine}><small>{engineName(lang,column.engine)} REFLEXUS</small><h2>{area.engines.find(item=>item.engine===column.engine)?.relevance}/100</h2>{column.signals.map(signal=><div key={signal.id}><b>{signal.label}</b><p>{signal.source.replaceAll("_"," ")} · {signal.temporalClass.replaceAll("_"," ")}</p><code>{signal.evidenceIds.join(" · ")}</code></div>)}</article>)}</div><section className="imago-area-summary"><article><small>{t.convergence}</small><h3>{area.convergence}</h3><p>{area.consistency}</p></article><article><small>{t.temporality}</small><p>{area.temporalClasses.join(" · ")||t.insufficient}</p></article><article><small>{t.facts}</small><p>{area.evidenceIds.length}</p></article></section><div className="ai-slot" hidden data-ai-slot="imago-area-editorial" data-area={area.area}/></section>;
}

export function ReflexusMenuCard({discipline,lang,onClick}:{discipline:AstroDiscipline;lang:Language;onClick:()=>void}) {const t=copy[lang],product=reflexusProductCopy[lang][discipline];return <button type="button" className="reflexus-menu-card" onClick={onClick}><i aria-hidden="true">◉</i><span><small>{product.subtitle}</small><b>{t.your}</b><em>{product.description}</em></span><strong aria-hidden="true">→</strong></button>}
