import type { Language } from "./spread-translations.ts";

type Localized4 = { EN: string; FR: string; DE: string; PT: string };

// ---------- Zen ----------

export const ZEN_GROUP_T: Record<string, Localized4> = {
  "Conciencia": { EN: "Consciousness", FR: "Conscience", DE: "Bewusstsein", PT: "Consciência" },
  "Fuego": { EN: "Fire", FR: "Feu", DE: "Feuer", PT: "Fogo" },
  "Agua": { EN: "Water", FR: "Eau", DE: "Wasser", PT: "Água" },
  "Nubes": { EN: "Clouds", FR: "Nuages", DE: "Wolken", PT: "Nuvens" },
  "Arcoíris": { EN: "Rainbow", FR: "Arc-en-ciel", DE: "Regenbogen", PT: "Arco-íris" },
};

export const ZEN_CARD_NAME_T: Record<string, Localized4> = {
  "Apertura": { EN: "Opening", FR: "Ouverture", DE: "Öffnung", PT: "Abertura" },
  "Presencia": { EN: "Presence", FR: "Présence", DE: "Präsenz", PT: "Presença" },
  "Testigo interior": { EN: "Inner Witness", FR: "Témoin intérieur", DE: "Innerer Zeuge", PT: "Testemunha interior" },
  "Impulso creador": { EN: "Creative Impulse", FR: "Élan créateur", DE: "Schöpferischer Impuls", PT: "Impulso criador" },
  "Libertad consciente": { EN: "Conscious Freedom", FR: "Liberté consciente", DE: "Bewusste Freiheit", PT: "Liberdade consciente" },
  "Vacío fértil": { EN: "Fertile Void", FR: "Vide fertile", DE: "Fruchtbare Leere", PT: "Vazio fértil" },
  "Encuentro": { EN: "Encounter", FR: "Rencontre", DE: "Begegnung", PT: "Encontro" },
  "Claridad": { EN: "Clarity", FR: "Clarté", DE: "Klarheit", PT: "Clareza" },
  "Valor sereno": { EN: "Serene Courage", FR: "Courage serein", DE: "Gelassener Mut", PT: "Coragem serena" },
  "Soledad plena": { EN: "Full Solitude", FR: "Solitude pleine", DE: "Erfüllte Einsamkeit", PT: "Solidão plena" },
  "Movimiento": { EN: "Movement", FR: "Mouvement", DE: "Bewegung", PT: "Movimento" },
  "Umbral": { EN: "Threshold", FR: "Seuil", DE: "Schwelle", PT: "Limiar" },
  "Mirada nueva": { EN: "New Outlook", FR: "Regard neuf", DE: "Neuer Blick", PT: "Novo olhar" },
  "Metamorfosis": { EN: "Metamorphosis", FR: "Métamorphose", DE: "Metamorphose", PT: "Metamorfose" },
  "Centro": { EN: "Center", FR: "Centre", DE: "Zentrum", PT: "Centro" },
  "Máscaras": { EN: "Masks", FR: "Masques", DE: "Masken", PT: "Máscaras" },
  "Despertar súbito": { EN: "Sudden Awakening", FR: "Éveil soudain", DE: "Plötzliches Erwachen", PT: "Despertar súbito" },
  "Quietud": { EN: "Stillness", FR: "Quiétude", DE: "Stille", PT: "Quietude" },
  "Huellas": { EN: "Footprints", FR: "Empreintes", DE: "Spuren", PT: "Pegadas" },
  "Frescura": { EN: "Freshness", FR: "Fraîcheur", DE: "Frische", PT: "Frescor" },
  "Velo transparente": { EN: "Transparent Veil", FR: "Voile transparent", DE: "Durchsichtiger Schleier", PT: "Véu transparente" },
  "Círculo completo": { EN: "Full Circle", FR: "Cercle complet", DE: "Vollendeter Kreis", PT: "Círculo completo" },
  "Guía interior": { EN: "Inner Guide", FR: "Guide intérieur", DE: "Innerer Führer", PT: "Guia interior" },
  "Semilla": { EN: "Seed", FR: "Graine", DE: "Same", PT: "Semente" },
  "Horizonte": { EN: "Horizon", FR: "Horizon", DE: "Horizont", PT: "Horizonte" },
  "Vivencia": { EN: "Lived Experience", FR: "Vécu", DE: "Erlebnis", PT: "Vivência" },
  "Círculo": { EN: "Circle", FR: "Cercle", DE: "Kreis", PT: "Círculo" },
  "Entrega": { EN: "Surrender", FR: "Don de soi", DE: "Hingabe", PT: "Entrega" },
  "Cumbre": { EN: "Summit", FR: "Sommet", DE: "Gipfel", PT: "Cume" },
  "Tensión": { EN: "Tension", FR: "Tension", DE: "Spannung", PT: "Tensão" },
  "Camino": { EN: "Path", FR: "Chemin", DE: "Weg", PT: "Caminho" },
  "Reserva": { EN: "Reserve", FR: "Réserve", DE: "Reserve", PT: "Reserva" },
  "Contención": { EN: "Containment", FR: "Contenance", DE: "Zurückhaltung", PT: "Contenção" },
  "Juego": { EN: "Play", FR: "Jeu", DE: "Spiel", PT: "Jogo" },
  "Pulso": { EN: "Pulse", FR: "Pouls", DE: "Puls", PT: "Pulso" },
  "Ofrenda": { EN: "Offering", FR: "Offrande", DE: "Opfergabe", PT: "Oferenda" },
  "Artesano": { EN: "Craftsman", FR: "Artisan", DE: "Handwerker", PT: "Artesão" },
  "Corriente": { EN: "Current", FR: "Courant", DE: "Strömung", PT: "Corrente" },
  "Afinidad": { EN: "Affinity", FR: "Affinité", DE: "Affinität", PT: "Afinidade" },
  "Júbilo": { EN: "Jubilation", FR: "Jubilation", DE: "Jubel", PT: "Júbilo" },
  "Regreso": { EN: "Return", FR: "Retour", DE: "Rückkehr", PT: "Regresso" },
  "Memoria": { EN: "Memory", FR: "Mémoire", DE: "Erinnerung", PT: "Memória" },
  "Imaginación": { EN: "Imagination", FR: "Imagination", DE: "Vorstellungskraft", PT: "Imaginação" },
  "Espejo": { EN: "Mirror", FR: "Miroir", DE: "Spiegel", PT: "Espelho" },
  "Desprendimiento": { EN: "Letting Go", FR: "Détachement", DE: "Loslassen", PT: "Desapego" },
  "Reposo": { EN: "Rest", FR: "Repos", DE: "Ruhe", PT: "Repouso" },
  "Resonancia": { EN: "Resonance", FR: "Résonance", DE: "Resonanz", PT: "Ressonância" },
  "Comprensión": { EN: "Understanding", FR: "Compréhension", DE: "Verständnis", PT: "Compreensão" },
  "Confianza": { EN: "Trust", FR: "Confiance", DE: "Vertrauen", PT: "Confiança" },
  "Apertura receptiva": { EN: "Receptive Opening", FR: "Ouverture réceptive", DE: "Empfängliche Öffnung", PT: "Abertura receptiva" },
  "Reparación": { EN: "Repair", FR: "Réparation", DE: "Reparatur", PT: "Reparação" },
  "Observador": { EN: "Observer", FR: "Observateur", DE: "Beobachter", PT: "Observador" },
  "División": { EN: "Division", FR: "Division", DE: "Teilung", PT: "Divisão" },
  "Distancia": { EN: "Distance", FR: "Distance", DE: "Distanz", PT: "Distância" },
  "Espera": { EN: "Waiting", FR: "Attente", DE: "Warten", PT: "Espera" },
  "Medida": { EN: "Measure", FR: "Mesure", DE: "Maß", PT: "Medida" },
  "Peso": { EN: "Weight", FR: "Poids", DE: "Gewicht", PT: "Peso" },
  "Estrategia": { EN: "Strategy", FR: "Stratégie", DE: "Strategie", PT: "Estratégia" },
  "Remordimiento": { EN: "Remorse", FR: "Remords", DE: "Reue", PT: "Remorso" },
  "Duelo": { EN: "Grief", FR: "Deuil", DE: "Trauer", PT: "Luto" },
  "Renacer": { EN: "Rebirth", FR: "Renaissance", DE: "Wiedergeburt", PT: "Renascer" },
  "Rumor mental": { EN: "Mental Chatter", FR: "Rumeur mentale", DE: "Gedankenlärm", PT: "Rumor mental" },
  "Defensa": { EN: "Defense", FR: "Défense", DE: "Verteidigung", PT: "Defesa" },
  "Norma": { EN: "Norm", FR: "Norme", DE: "Norm", PT: "Norma" },
  "Dominio": { EN: "Mastery", FR: "Maîtrise", DE: "Beherrschung", PT: "Domínio" },
  "Cosecha": { EN: "Harvest", FR: "Récolte", DE: "Ernte", PT: "Colheita" },
  "Paso presente": { EN: "Present Step", FR: "Pas présent", DE: "Gegenwärtiger Schritt", PT: "Passo presente" },
  "Brújula": { EN: "Compass", FR: "Boussole", DE: "Kompass", PT: "Bússola" },
  "Acumulación": { EN: "Accumulation", FR: "Accumulation", DE: "Anhäufung", PT: "Acumulação" },
  "Umbral exterior": { EN: "Outer Threshold", FR: "Seuil extérieur", DE: "Äußere Schwelle", PT: "Limiar exterior" },
  "Acuerdo": { EN: "Agreement", FR: "Accord", DE: "Übereinkunft", PT: "Acordo" },
  "Gestación": { EN: "Gestation", FR: "Gestation", DE: "Reifung", PT: "Gestação" },
  "Sencillez": { EN: "Simplicity", FR: "Simplicité", DE: "Einfachheit", PT: "Simplicidade" },
  "Fruto": { EN: "Fruit", FR: "Fruit", DE: "Frucht", PT: "Fruto" },
  "Comunidad": { EN: "Community", FR: "Communauté", DE: "Gemeinschaft", PT: "Comunidade" },
  "Exploración": { EN: "Exploration", FR: "Exploration", DE: "Erkundung", PT: "Exploração" },
  "Pausa": { EN: "Pause", FR: "Pause", DE: "Pause", PT: "Pausa" },
  "Expansión": { EN: "Expansion", FR: "Expansion", DE: "Expansion", PT: "Expansão" },
  "Prosperidad": { EN: "Prosperity", FR: "Prospérité", DE: "Wohlstand", PT: "Prosperidade" },
};

export const ZEN_PHASE_T: Record<string, { phase: Localized4; message: Localized4; question: Localized4; action: Localized4 }> = {
  "Observar": {
    phase: { EN: "Observe", FR: "Observer", DE: "Beobachten", PT: "Observar" },
    message: { EN: "Watch the pattern without correcting it yet.", FR: "Regarde le schéma sans encore le corriger.", DE: "Betrachte das Muster, ohne es schon zu korrigieren.", PT: "Observe o padrão sem corrigi-lo ainda." },
    question: { EN: "What's happening in you before you explain it?", FR: "Que se passe-t-il en toi avant de l'expliquer ?", DE: "Was geschieht in dir, bevor du es erklärst?", PT: "O que está acontecendo em você antes de explicá-lo?" },
    action: { EN: "Name one sensation, one thought, and one fact.", FR: "Nomme une sensation, une pensée et un fait.", DE: "Benenne eine Empfindung, einen Gedanken und eine Tatsache.", PT: "Nomeie uma sensação, um pensamento e um fato." },
  },
  "Permitir": {
    phase: { EN: "Allow", FR: "Permettre", DE: "Zulassen", PT: "Permitir" },
    message: { EN: "Make space for the experience without turning it into identity.", FR: "Fais de la place à l'expérience sans en faire une identité.", DE: "Schaffe Raum für die Erfahrung, ohne sie zu einer Identität zu machen.", PT: "Abra espaço para a experiência sem transformá-la em identidade." },
    question: { EN: "What changes if you stop fighting this moment?", FR: "Qu'est-ce qui change si tu arrêtes de lutter contre ce moment ?", DE: "Was ändert sich, wenn du aufhörst, gegen diesen Moment zu kämpfen?", PT: "O que muda se você parar de lutar contra este momento?" },
    action: { EN: "Take three breaths and allow a deliberate pause.", FR: "Respire trois fois et permets une pause délibérée.", DE: "Atme dreimal und erlaube dir eine bewusste Pause.", PT: "Respire três vezes e permita uma pausa deliberada." },
  },
  "Integrar": {
    phase: { EN: "Integrate", FR: "Intégrer", DE: "Integrieren", PT: "Integrar" },
    message: { EN: "Turn the understanding into one small, verifiable action.", FR: "Transforme la compréhension en une petite action vérifiable.", DE: "Verwandle das Verständnis in eine kleine, überprüfbare Handlung.", PT: "Transforme a compreensão em uma ação pequena e verificável." },
    question: { EN: "What gesture expresses this awareness in daily life?", FR: "Quel geste exprime cette conscience dans la vie quotidienne ?", DE: "Welche Geste drückt dieses Bewusstsein im Alltag aus?", PT: "Que gesto expressa essa consciência na vida cotidiana?" },
    action: { EN: "Choose one concrete step you can take today.", FR: "Choisis un pas concret que tu peux faire aujourd'hui.", DE: "Wähle einen konkreten Schritt, den du heute tun kannst.", PT: "Escolha um passo concreto que você possa realizar hoje." },
  },
};

export function translateZenGroup(group: string, language: Language): string {
  if (language === "ES") return group;
  return ZEN_GROUP_T[group]?.[language] || group;
}
export function translateZenCardName(name: string, language: Language): string {
  if (language === "ES") return name;
  return ZEN_CARD_NAME_T[name]?.[language] || name;
}
export function translateZenPhase(phase: string, language: Exclude<Language, "ES">): { phase: string; message: string; question: string; action: string } | null {
  const entry = ZEN_PHASE_T[phase];
  if (!entry) return null;
  return { phase: entry.phase[language] || phase, message: entry.message[language], question: entry.question[language], action: entry.action[language] };
}

// ---------- Power Animals ----------

type AnimalRow = { name: Localized4; meaning: Localized4; message: Localized4 };
export const ANIMAL_T: AnimalRow[] = [
  { name: { EN: "Eagle", FR: "Aigle", DE: "Adler", PT: "Águia" }, meaning: { EN: "Vision", FR: "Vision", DE: "Weitsicht", PT: "Visão" }, message: { EN: "Step back to make out the whole landscape.", FR: "Prends du recul pour distinguer le paysage complet.", DE: "Tritt zurück, um die gesamte Landschaft zu erfassen.", PT: "Tome distância para distinguir o panorama completo." } },
  { name: { EN: "Wolf", FR: "Loup", DE: "Wolf", PT: "Lobo" }, meaning: { EN: "Instinct", FR: "Instinct", DE: "Instinkt", PT: "Instinto" }, message: { EN: "Listen to your instinct and weigh it against your community's experience.", FR: "Écoute ton instinct et confronte-le à l'expérience de ta communauté.", DE: "Höre auf deinen Instinkt und gleiche ihn mit der Erfahrung deiner Gemeinschaft ab.", PT: "Escute seu instinto e compare-o com a experiência da sua comunidade." } },
  { name: { EN: "Bear", FR: "Ours", DE: "Bär", PT: "Urso" }, meaning: { EN: "Strength", FR: "Force", DE: "Stärke", PT: "Força" }, message: { EN: "Protect your energy and act from a calm strength.", FR: "Protège ton énergie et agis depuis une force sereine.", DE: "Schütze deine Energie und handle aus ruhiger Kraft.", PT: "Proteja sua energia e aja a partir de uma força serena." } },
  { name: { EN: "Owl", FR: "Hibou", DE: "Eule", PT: "Coruja" }, meaning: { EN: "Observation", FR: "Observation", DE: "Beobachtung", PT: "Observação" }, message: { EN: "Watch what happens when the noise settles.", FR: "Observe ce qui se passe quand le bruit diminue.", DE: "Schau, was geschieht, wenn der Lärm nachlässt.", PT: "Observe o que acontece quando o ruído diminui." } },
  { name: { EN: "Jaguar", FR: "Jaguar", DE: "Jaguar", PT: "Onça" }, meaning: { EN: "Presence", FR: "Présence", DE: "Präsenz", PT: "Presença" }, message: { EN: "Move with attention and save your strength for when it's needed.", FR: "Avance avec attention et réserve ta force pour le moment nécessaire.", DE: "Bewege dich aufmerksam und spare deine Kraft für den nötigen Moment.", PT: "Avance com atenção e reserve sua força para o momento necessário." } },
  { name: { EN: "Deer", FR: "Cerf", DE: "Hirsch", PT: "Cervo" }, meaning: { EN: "Sensitivity", FR: "Sensibilité", DE: "Sensibilität", PT: "Sensibilidade" }, message: { EN: "Approach gently without abandoning your limits.", FR: "Approche-toi avec douceur sans abandonner tes limites.", DE: "Nähere dich sanft, ohne deine Grenzen aufzugeben.", PT: "Aproxime-se com gentileza sem abandonar seus limites." } },
  { name: { EN: "Fox", FR: "Renard", DE: "Fuchs", PT: "Raposa" }, meaning: { EN: "Adaptation", FR: "Adaptation", DE: "Anpassung", PT: "Adaptação" }, message: { EN: "Change strategy without losing the intention.", FR: "Change de stratégie sans perdre l'intention.", DE: "Ändere die Strategie, ohne die Absicht zu verlieren.", PT: "Mude de estratégia sem perder a intenção." } },
  { name: { EN: "Horse", FR: "Cheval", DE: "Pferd", PT: "Cavalo" }, meaning: { EN: "Freedom", FR: "Liberté", DE: "Freiheit", PT: "Liberdade" }, message: { EN: "Regain movement through a coherent decision.", FR: "Retrouve le mouvement grâce à une décision cohérente.", DE: "Gewinne Bewegung durch eine stimmige Entscheidung zurück.", PT: "Recupere o movimento por meio de uma decisão coerente." } },
  { name: { EN: "Raven", FR: "Corbeau", DE: "Rabe", PT: "Corvo" }, meaning: { EN: "Intelligence", FR: "Intelligence", DE: "Intelligenz", PT: "Inteligência" }, message: { EN: "Use what's available in a new way.", FR: "Utilise ce qui est disponible d'une manière nouvelle.", DE: "Nutze das Vorhandene auf neue Weise.", PT: "Use o que está disponível de uma forma nova." } },
  { name: { EN: "Lion", FR: "Lion", DE: "Löwe", PT: "Leão" }, meaning: { EN: "Leadership", FR: "Leadership", DE: "Führung", PT: "Liderança" }, message: { EN: "Take responsibility without turning authority into domination.", FR: "Assume la responsabilité sans transformer l'autorité en domination.", DE: "Übernimm Verantwortung, ohne Autorität in Herrschaft zu verwandeln.", PT: "Assuma responsabilidade sem transformar autoridade em domínio." } },
  { name: { EN: "Butterfly", FR: "Papillon", DE: "Schmetterling", PT: "Borboleta" }, meaning: { EN: "Transformation", FR: "Transformation", DE: "Verwandlung", PT: "Transformação" }, message: { EN: "Let a stage change shape.", FR: "Permets à une étape de changer de forme.", DE: "Lass eine Phase ihre Form ändern.", PT: "Permita que uma etapa mude de forma." } },
  { name: { EN: "Snake", FR: "Serpent", DE: "Schlange", PT: "Serpente" }, meaning: { EN: "Renewal", FR: "Renouveau", DE: "Erneuerung", PT: "Renovação" }, message: { EN: "Shed a layer that no longer protects your growth.", FR: "Laisse tomber une couche qui ne protège plus ta croissance.", DE: "Lass eine Schicht los, die dein Wachstum nicht mehr schützt.", PT: "Solte uma camada que já não protege seu crescimento." } },
  { name: { EN: "Turtle", FR: "Tortue", DE: "Schildkröte", PT: "Tartaruga" }, meaning: { EN: "Perseverance", FR: "Constance", DE: "Beständigkeit", PT: "Constância" }, message: { EN: "Move at a pace you can sustain.", FR: "Avance à un rythme que tu peux soutenir.", DE: "Bewege dich in einem Tempo, das du durchhalten kannst.", PT: "Avance em um ritmo que você possa sustentar." } },
  { name: { EN: "Hummingbird", FR: "Colibri", DE: "Kolibri", PT: "Beija-flor" }, meaning: { EN: "Joy", FR: "Joie", DE: "Freude", PT: "Alegria" }, message: { EN: "Recognize the small source of energy close to you.", FR: "Reconnais la petite source d'énergie qui est près de toi.", DE: "Erkenne die kleine Energiequelle in deiner Nähe.", PT: "Reconheça a pequena fonte de energia que você tem por perto." } },
  { name: { EN: "Elephant", FR: "Éléphant", DE: "Elefant", PT: "Elefante" }, meaning: { EN: "Memory", FR: "Mémoire", DE: "Erinnerung", PT: "Memória" }, message: { EN: "Learn from the past without staying trapped in it.", FR: "Apprends du passé sans y rester piégé.", DE: "Lerne aus der Vergangenheit, ohne darin gefangen zu bleiben.", PT: "Aprenda com o passado sem ficar preso a ele." } },
  { name: { EN: "Dolphin", FR: "Dauphin", DE: "Delfin", PT: "Golfinho" }, meaning: { EN: "Communication", FR: "Communication", DE: "Kommunikation", PT: "Comunicação" }, message: { EN: "Make room for play and clear communication.", FR: "Fais de la place au jeu et à une communication claire.", DE: "Schaffe Raum für Spiel und klare Kommunikation.", PT: "Abra espaço para o jogo e a comunicação clara." } },
  { name: { EN: "Whale", FR: "Baleine", DE: "Wal", PT: "Baleia" }, meaning: { EN: "Depth", FR: "Profondeur", DE: "Tiefe", PT: "Profundidade" }, message: { EN: "Listen to what only appears when you stay silent.", FR: "Écoute ce qui n'apparaît que dans le silence.", DE: "Höre, was nur im Schweigen erscheint.", PT: "Escute o que só aparece quando você permanece em silêncio." } },
  { name: { EN: "Buffalo", FR: "Buffle", DE: "Büffel", PT: "Búfalo" }, meaning: { EN: "Sustenance", FR: "Subsistance", DE: "Versorgung", PT: "Sustento" }, message: { EN: "Honor the resources and those who sustain the path.", FR: "Honore les ressources et ceux qui soutiennent le chemin.", DE: "Ehre die Ressourcen und diejenigen, die den Weg tragen.", PT: "Honre os recursos e aqueles que sustentam o caminho." } },
  { name: { EN: "Rabbit", FR: "Lapin", DE: "Hase", PT: "Coelho" }, meaning: { EN: "Attention", FR: "Attention", DE: "Aufmerksamkeit", PT: "Atenção" }, message: { EN: "Tell caution apart from fear before reacting.", FR: "Distingue la prudence de la peur avant de réagir.", DE: "Unterscheide Vorsicht von Angst, bevor du reagierst.", PT: "Distinga prudência de medo antes de reagir." } },
  { name: { EN: "Frog", FR: "Grenouille", DE: "Frosch", PT: "Sapo" }, meaning: { EN: "Cleansing", FR: "Purification", DE: "Reinigung", PT: "Limpeza" }, message: { EN: "Renew your emotional environment with one simple action.", FR: "Renouvelle ton environnement émotionnel par une action simple.", DE: "Erneuere dein emotionales Umfeld mit einer einfachen Handlung.", PT: "Renove o ambiente emocional com uma ação simples." } },
  { name: { EN: "Spider", FR: "Araignée", DE: "Spinne", PT: "Aranha" }, meaning: { EN: "Creation", FR: "Création", DE: "Schöpfung", PT: "Criação" }, message: { EN: "Observe what web you're building with your decisions.", FR: "Observe quel réseau tu construis avec tes décisions.", DE: "Beobachte, welches Netz du mit deinen Entscheidungen webst.", PT: "Observe que rede você está construindo com suas decisões." } },
  { name: { EN: "Dragonfly", FR: "Libellule", DE: "Libelle", PT: "Libélula" }, meaning: { EN: "Clarity", FR: "Clarté", DE: "Klarheit", PT: "Clareza" }, message: { EN: "Look beyond the first impression.", FR: "Regarde au-delà de la première impression.", DE: "Schau über den ersten Eindruck hinaus.", PT: "Olhe além da primeira impressão." } },
  { name: { EN: "Bee", FR: "Abeille", DE: "Biene", PT: "Abelha" }, meaning: { EN: "Cooperation", FR: "Coopération", DE: "Zusammenarbeit", PT: "Cooperação" }, message: { EN: "Contribute your part without forgetting the wellbeing of the whole.", FR: "Apporte ta part sans oublier le bien-être de l'ensemble.", DE: "Bring deinen Teil ein, ohne das Wohl des Ganzen zu vergessen.", PT: "Contribua com sua parte sem esquecer o bem-estar do conjunto." } },
  { name: { EN: "Ant", FR: "Fourmi", DE: "Ameise", PT: "Formiga" }, meaning: { EN: "Discipline", FR: "Discipline", DE: "Disziplin", PT: "Disciplina" }, message: { EN: "Divide the work and trust the sum of small steps.", FR: "Divise le travail et fais confiance à la somme des petits pas.", DE: "Teile die Arbeit auf und vertraue der Summe kleiner Schritte.", PT: "Divida o trabalho e confie na soma de pequenos passos." } },
  { name: { EN: "Beaver", FR: "Castor", DE: "Biber", PT: "Castor" }, meaning: { EN: "Construction", FR: "Construction", DE: "Aufbau", PT: "Construção" }, message: { EN: "Build a useful structure before expanding.", FR: "Crée une structure utile avant de t'agrandir.", DE: "Errichte eine nützliche Struktur, bevor du erweiterst.", PT: "Crie uma estrutura útil antes de ampliar." } },
  { name: { EN: "Otter", FR: "Loutre", DE: "Otter", PT: "Lontra" }, meaning: { EN: "Play", FR: "Jeu", DE: "Spiel", PT: "Diversão" }, message: { EN: "Flexibility can also be a form of intelligence.", FR: "La flexibilité peut aussi être une forme d'intelligence.", DE: "Flexibilität kann auch eine Form von Intelligenz sein.", PT: "A flexibilidade também pode ser uma forma de inteligência." } },
  { name: { EN: "Salmon", FR: "Saumon", DE: "Lachs", PT: "Salmão" }, meaning: { EN: "Perseverance", FR: "Persévérance", DE: "Ausdauer", PT: "Perseverança" }, message: { EN: "Remember your direction when the path offers resistance.", FR: "Souviens-toi de ta direction quand le chemin oppose de la résistance.", DE: "Erinnere dich an deine Richtung, wenn der Weg Widerstand leistet.", PT: "Lembre-se da sua direção quando o caminho oferecer resistência." } },
  { name: { EN: "Hawk", FR: "Faucon", DE: "Habicht", PT: "Falcão" }, meaning: { EN: "Focus", FR: "Concentration", DE: "Fokus", PT: "Foco" }, message: { EN: "Choose one goal and reduce scattering.", FR: "Choisis un objectif et réduis la dispersion.", DE: "Wähle ein Ziel und verringere die Zerstreuung.", PT: "Escolha um objetivo e reduza a dispersão." } },
  { name: { EN: "Peregrine Falcon", FR: "Faucon pèlerin", DE: "Wanderfalke", PT: "Falcão peregrino" }, meaning: { EN: "Precision", FR: "Précision", DE: "Präzision", PT: "Precisão" }, message: { EN: "Act when intention and timing are aligned.", FR: "Agis quand l'intention et le moment sont alignés.", DE: "Handle, wenn Absicht und Moment übereinstimmen.", PT: "Aja quando a intenção e o momento estiverem alinhados." } },
  { name: { EN: "Swan", FR: "Cygne", DE: "Schwan", PT: "Cisne" }, meaning: { EN: "Grace", FR: "Grâce", DE: "Anmut", PT: "Graça" }, message: { EN: "Let the transformation mature without showing off every effort.", FR: "Laisse la transformation mûrir sans exhiber chaque effort.", DE: "Lass die Verwandlung reifen, ohne jede Anstrengung zur Schau zu stellen.", PT: "Permita que a transformação amadureça sem exibir cada esforço." } },
  { name: { EN: "Peacock", FR: "Paon", DE: "Pfau", PT: "Pavão" }, meaning: { EN: "Expression", FR: "Expression", DE: "Ausdruck", PT: "Expressão" }, message: { EN: "Show yourself authentically without depending on approval.", FR: "Montre-toi avec authenticité sans dépendre de l'approbation.", DE: "Zeig dich authentisch, ohne von Zustimmung abhängig zu sein.", PT: "Mostre-se com autenticidade sem depender da aprovação." } },
  { name: { EN: "Rooster", FR: "Coq", DE: "Hahn", PT: "Galo" }, meaning: { EN: "Awakening", FR: "Éveil", DE: "Erwachen", PT: "Despertar" }, message: { EN: "Announce the beginning through a visible action.", FR: "Annonce le commencement par une action visible.", DE: "Kündige den Anfang durch eine sichtbare Handlung an.", PT: "Anuncie o começo por meio de uma ação visível." } },
  { name: { EN: "Dog", FR: "Chien", DE: "Hund", PT: "Cachorro" }, meaning: { EN: "Loyalty", FR: "Loyauté", DE: "Treue", PT: "Lealdade" }, message: { EN: "Take care of the bonds that also know how to take care of you.", FR: "Prends soin des liens qui savent aussi prendre soin de toi.", DE: "Kümmere dich um die Bindungen, die sich auch um dich kümmern.", PT: "Cuide dos vínculos que também sabem cuidar de você." } },
  { name: { EN: "Cat", FR: "Chat", DE: "Katze", PT: "Gato" }, meaning: { EN: "Autonomy", FR: "Autonomie", DE: "Autonomie", PT: "Autonomia" }, message: { EN: "Protect your space and keep your curiosity.", FR: "Protège ton espace et conserve ta curiosité.", DE: "Schütze deinen Raum und bewahre deine Neugier.", PT: "Proteja seu espaço e conserve a curiosidade." } },
  { name: { EN: "Lynx", FR: "Lynx", DE: "Luchs", PT: "Lince" }, meaning: { EN: "Discernment", FR: "Discernement", DE: "Unterscheidungsvermögen", PT: "Discernimento" }, message: { EN: "Observe the details before revealing your position.", FR: "Observe les détails avant de révéler ta position.", DE: "Beobachte die Details, bevor du deine Position preisgibst.", PT: "Observe os detalhes antes de revelar sua posição." } },
  { name: { EN: "Bat", FR: "Chauve-souris", DE: "Fledermaus", PT: "Morcego" }, meaning: { EN: "Transition", FR: "Transition", DE: "Übergang", PT: "Transição" }, message: { EN: "Find your bearings with new senses when the familiar path isn't enough.", FR: "Oriente-toi avec de nouveaux sens quand la voie connue ne suffit plus.", DE: "Orientiere dich mit neuen Sinnen, wenn der bekannte Weg nicht ausreicht.", PT: "Oriente-se com novos sentidos quando o caminho conhecido não for suficiente." } },
  { name: { EN: "Moth", FR: "Papillon de nuit", DE: "Nachtfalter", PT: "Mariposa" }, meaning: { EN: "Attraction", FR: "Attraction", DE: "Anziehung", PT: "Atração" }, message: { EN: "Check whether what attracts you is also good for you.", FR: "Vérifie si ce qui t'attire te fait aussi du bien.", DE: "Prüfe, ob das, was dich anzieht, dir auch guttut.", PT: "Verifique se aquilo que atrai você também faz bem a você." } },
  { name: { EN: "Gorilla", FR: "Gorille", DE: "Gorilla", PT: "Gorila" }, meaning: { EN: "Family Protection", FR: "Protection familiale", DE: "Familienschutz", PT: "Proteção familiar" }, message: { EN: "Use strength to care for others, not to impose.", FR: "Utilise la force pour prendre soin, pas pour imposer.", DE: "Nutze Stärke, um zu beschützen, nicht um zu beherrschen.", PT: "Use a força para cuidar, não para impor." } },
  { name: { EN: "Chameleon", FR: "Caméléon", DE: "Chamäleon", PT: "Camaleão" }, meaning: { EN: "Flexibility", FR: "Flexibilité", DE: "Flexibilität", PT: "Flexibilidade" }, message: { EN: "Adapt to the context without forgetting who you are.", FR: "Adapte-toi au contexte sans oublier qui tu es.", DE: "Passe dich dem Kontext an, ohne zu vergessen, wer du bist.", PT: "Adapte-se ao contexto sem esquecer quem você é." } },
  { name: { EN: "Crocodile", FR: "Crocodile", DE: "Krokodil", PT: "Crocodilo" }, meaning: { EN: "Patience", FR: "Patience", DE: "Geduld", PT: "Paciência" }, message: { EN: "Stay alert and avoid spending energy before it's time.", FR: "Reste attentif et évite de dépenser de l'énergie avant l'heure.", DE: "Bleib aufmerksam und vermeide es, vorzeitig Energie zu verschwenden.", PT: "Permaneça atento e evite gastar energia antes da hora." } },
  { name: { EN: "Scorpion", FR: "Scorpion", DE: "Skorpion", PT: "Escorpião" }, meaning: { EN: "Boundaries", FR: "Limites", DE: "Grenzen", PT: "Limites" }, message: { EN: "Respond with measure and protect what's vulnerable.", FR: "Réponds avec mesure et protège ce qui est vulnérable.", DE: "Reagiere mit Maß und schütze das Verletzliche.", PT: "Responda com medida e proteja o que é vulnerável." } },
  { name: { EN: "Beetle", FR: "Scarabée", DE: "Käfer", PT: "Besouro" }, meaning: { EN: "Rebirth", FR: "Renaissance", DE: "Wiedergeburt", PT: "Renascimento" }, message: { EN: "Turn what's difficult into material for a new stage.", FR: "Transforme ce qui est difficile en matière pour une nouvelle étape.", DE: "Verwandle das Schwierige in Material für eine neue Etappe.", PT: "Transforme o difícil em matéria para uma nova etapa." } },
  { name: { EN: "Crane", FR: "Grue", DE: "Kranich", PT: "Grou" }, meaning: { EN: "Balance", FR: "Équilibre", DE: "Gleichgewicht", PT: "Equilíbrio" }, message: { EN: "Maintain stability while the environment changes.", FR: "Maintiens la stabilité pendant que l'environnement change.", DE: "Bewahre Stabilität, während sich das Umfeld verändert.", PT: "Mantenha estabilidade enquanto o ambiente muda." } },
  { name: { EN: "Condor", FR: "Condor", DE: "Kondor", PT: "Condor" }, meaning: { EN: "Perspective", FR: "Perspective", DE: "Perspektive", PT: "Perspectiva" }, message: { EN: "Raise your gaze and leave behind an unnecessary burden.", FR: "Élève ton regard et laisse derrière toi un poids inutile.", DE: "Hebe deinen Blick und lass eine unnötige Last zurück.", PT: "Eleve o olhar e deixe para trás uma carga desnecessária." } },
];

export function translateAnimal(index: number, field: "name" | "meaning" | "message", fallback: string, language: Language): string {
  if (language === "ES") return fallback;
  return ANIMAL_T[index]?.[field]?.[language] || fallback;
}

// ---------- Angels ----------

export const ANGEL_FAMILY_T: Record<string, Localized4> = {
  "Arcángeles y tradición oriental": { EN: "Archangels and Eastern tradition", FR: "Archanges et tradition orientale", DE: "Erzengel und östliche Tradition", PT: "Arcanjos e tradição oriental" },
  "Angelología mística posterior": { EN: "Later mystical angelology", FR: "Angélologie mystique tardive", DE: "Spätere mystische Engelslehre", PT: "Angelologia mística posterior" },
  "Tradiciones apócrifas y devocionales": { EN: "Apocryphal and devotional traditions", FR: "Traditions apocryphes et dévotionnelles", DE: "Apokryphe und andächtige Traditionen", PT: "Tradições apócrifas e devocionais" },
  "Ángeles del Shem HaMephorash": { EN: "Angels of the Shem HaMephorash", FR: "Anges du Shem HaMephorash", DE: "Engel des Shem HaMephorasch", PT: "Anjos do Shem HaMephorash" },
};

export const ANGEL_TRADITION_T: Record<string, Localized4> = {
  "Tradición bíblica y cristiana": { EN: "Biblical and Christian tradition", FR: "Tradition biblique et chrétienne", DE: "Biblische und christliche Tradition", PT: "Tradição bíblica e cristã" },
  "Tradición bíblica, cristiana e islámica": { EN: "Biblical, Christian, and Islamic tradition", FR: "Tradition biblique, chrétienne et islamique", DE: "Biblische, christliche und islamische Tradition", PT: "Tradição bíblica, cristã e islâmica" },
  "Libro de Tobit y tradición cristiana": { EN: "Book of Tobit and Christian tradition", FR: "Livre de Tobie et tradition chrétienne", DE: "Buch Tobit und christliche Tradition", PT: "Livro de Tobias e tradição cristã" },
  "Tradición apócrifa y cristiana oriental": { EN: "Apocryphal and Eastern Christian tradition", FR: "Tradition apocryphe et chrétienne orientale", DE: "Apokryphe und östlich-christliche Tradition", PT: "Tradição apócrifa e cristã oriental" },
  "Tradición enoquiana": { EN: "Enochian tradition", FR: "Tradition hénochienne", DE: "Henochische Tradition", PT: "Tradição enoquiana" },
  "Tradición enoquiana y apócrifa": { EN: "Enochian and apocryphal tradition", FR: "Tradition hénochienne et apocryphe", DE: "Henochische und apokryphe Tradition", PT: "Tradição enoquiana e apócrifa" },
  "Tradición cristiana oriental": { EN: "Eastern Christian tradition", FR: "Tradition chrétienne orientale", DE: "Östlich-christliche Tradition", PT: "Tradição cristã oriental" },
  "Mística judía posterior": { EN: "Later Jewish mysticism", FR: "Mysticisme juif tardif", DE: "Spätere jüdische Mystik", PT: "Misticismo judaico posterior" },
  "Angelología medieval y mística judía": { EN: "Medieval angelology and Jewish mysticism", FR: "Angélologie médiévale et mysticisme juif", DE: "Mittelalterliche Engelslehre und jüdische Mystik", PT: "Angelologia medieval e misticismo judaico" },
  "Angelología cristiana posterior": { EN: "Later Christian angelology", FR: "Angélologie chrétienne tardive", DE: "Spätere christliche Engelslehre", PT: "Angelologia cristã posterior" },
  "Devoción cristiana posterior": { EN: "Later Christian devotion", FR: "Dévotion chrétienne tardive", DE: "Spätere christliche Andacht", PT: "Devoção cristã posterior" },
  "Mística judía y angelología posterior": { EN: "Jewish mysticism and later angelology", FR: "Mysticisme juif et angélologie tardive", DE: "Jüdische Mystik und spätere Engelslehre", PT: "Misticismo judaico e angelologia posterior" },
  "Angelología medieval y posterior": { EN: "Medieval and later angelology", FR: "Angélologie médiévale et tardive", DE: "Mittelalterliche und spätere Engelslehre", PT: "Angelologia medieval e posterior" },
  "Tradición islámica y folclore posterior": { EN: "Islamic tradition and later folklore", FR: "Tradition islamique et folklore tardif", DE: "Islamische Tradition und späterer Volksglaube", PT: "Tradição islâmica e folclore posterior" },
  "Angelología medieval": { EN: "Medieval angelology", FR: "Angélologie médiévale", DE: "Mittelalterliche Engelslehre", PT: "Angelologia medieval" },
  "Tradición apócrifa": { EN: "Apocryphal tradition", FR: "Tradition apocryphe", DE: "Apokryphe Tradition", PT: "Tradição apócrifa" },
  "Apocalipsis de Abraham y tradición mística": { EN: "Apocalypse of Abraham and mystical tradition", FR: "Apocalypse d'Abraham et tradition mystique", DE: "Apokalypse des Abraham und mystische Tradition", PT: "Apocalipse de Abraão e tradição mística" },
  "Tradición rabínica y mística": { EN: "Rabbinic and mystical tradition", FR: "Tradition rabbinique et mystique", DE: "Rabbinische und mystische Tradition", PT: "Tradição rabínica e mística" },
  "Tradición judía y folclore posterior": { EN: "Jewish tradition and later folklore", FR: "Tradition juive et folklore tardif", DE: "Jüdische Tradition und späterer Volksglaube", PT: "Tradição judaica e folclore posterior" },
  "Tradición rabínica y folclore judío": { EN: "Rabbinic tradition and Jewish folklore", FR: "Tradition rabbinique et folklore juif", DE: "Rabbinische Tradition und jüdischer Volksglaube", PT: "Tradição rabínica e folclore judaico" },
  "Tradición judía y mística": { EN: "Jewish and mystical tradition", FR: "Tradition juive et mystique", DE: "Jüdische und mystische Tradition", PT: "Tradição judaica e mística" },
  "Angelología devocional posterior": { EN: "Later devotional angelology", FR: "Angélologie dévotionnelle tardive", DE: "Spätere andächtige Engelslehre", PT: "Angelologia devocional posterior" },
  "Tradición apócrifa y mística": { EN: "Apocryphal and mystical tradition", FR: "Tradition apocryphe et mystique", DE: "Apokryphe und mystische Tradition", PT: "Tradição apócrifa e mística" },
  "Angelología occidental posterior": { EN: "Later Western angelology", FR: "Angélologie occidentale tardive", DE: "Spätere westliche Engelslehre", PT: "Angelologia ocidental posterior" },
  "Shem HaMephorash, tradición cabalística occidental": { EN: "Shem HaMephorash, Western kabbalistic tradition", FR: "Shem HaMephorash, tradition kabbalistique occidentale", DE: "Shem HaMephorasch, westliche kabbalistische Tradition", PT: "Shem HaMephorash, tradição cabalística ocidental" },
};

export function translateAngelFamily(family: string, language: Language): string {
  if (language === "ES") return family;
  return ANGEL_FAMILY_T[family]?.[language] || family;
}
export function translateAngelTradition(tradition: string, language: Language): string {
  if (language === "ES") return tradition;
  return ANGEL_TRADITION_T[tradition]?.[language] || tradition;
}

type AngelRow = { name?: Localized4; role: Localized4; message: Localized4; attribute: Localized4; keys: [Localized4, Localized4] };
export const ANGEL_T: AngelRow[] = [
  { name: { EN: "Archangel Michael", FR: "Archange Michel", DE: "Erzengel Michael", PT: "Arcanjo Miguel" }, role: { EN: "Protection and courage", FR: "Protection et courage", DE: "Schutz und Mut", PT: "Proteção e coragem" }, message: { EN: "Defend what matters most with firmness, without letting fear choose for you.", FR: "Défends l'essentiel avec fermeté, sans laisser la peur choisir à ta place.", DE: "Verteidige das Wesentliche mit Entschlossenheit, ohne die Angst für dich entscheiden zu lassen.", PT: "Defenda o essencial com firmeza, sem deixar que o medo escolha por você." }, attribute: { EN: "Sword and shield", FR: "Épée et bouclier", DE: "Schwert und Schild", PT: "Espada e escudo" }, keys: [{ EN: "protection", FR: "protection", DE: "Schutz", PT: "proteção" }, { EN: "courage", FR: "courage", DE: "Mut", PT: "coragem" }] },
  { name: { EN: "Archangel Gabriel", FR: "Archange Gabriel", DE: "Erzengel Gabriel", PT: "Arcanjo Gabriel" }, role: { EN: "Message and communication", FR: "Message et communication", DE: "Botschaft und Kommunikation", PT: "Mensagem e comunicação" }, message: { EN: "Express clearly what needs to be heard, and confirm your message was understood.", FR: "Exprime clairement ce qui doit être entendu et confirme que ton message a été compris.", DE: "Drücke klar aus, was gehört werden muss, und bestätige, dass deine Botschaft verstanden wurde.", PT: "Expresse com clareza o que precisa ser ouvido e confirme que sua mensagem foi compreendida." }, attribute: { EN: "Lily and trumpet", FR: "Lys et trompette", DE: "Lilie und Trompete", PT: "Lírio e trombeta" }, keys: [{ EN: "message", FR: "message", DE: "Botschaft", PT: "mensagem" }, { EN: "clarity", FR: "clarté", DE: "Klarheit", PT: "clareza" }] },
  { name: { EN: "Archangel Raphael", FR: "Archange Raphaël", DE: "Erzengel Raphael", PT: "Arcanjo Rafael" }, role: { EN: "Healing and journey", FR: "Guérison et voyage", DE: "Heilung und Reise", PT: "Cura e viagem" }, message: { EN: "Care for the process of recovery and accept capable company along the way.", FR: "Prends soin du processus de guérison et accepte une compagnie compétente en chemin.", DE: "Kümmere dich um den Genesungsprozess und akzeptiere kompetente Begleitung auf dem Weg.", PT: "Cuide do processo de recuperação e aceite companhia competente durante o caminho." }, attribute: { EN: "Staff and green light", FR: "Bâton et lumière verte", DE: "Stab und grünes Licht", PT: "Bastão e luz verde" }, keys: [{ EN: "healing", FR: "guérison", DE: "Heilung", PT: "cura" }, { EN: "companionship", FR: "accompagnement", DE: "Begleitung", PT: "acompanhamento" }] },
  { name: { EN: "Archangel Uriel", FR: "Archange Uriel", DE: "Erzengel Uriel", PT: "Arcanjo Uriel" }, role: { EN: "Wisdom and light", FR: "Sagesse et lumière", DE: "Weisheit und Licht", PT: "Sabedoria e luz" }, message: { EN: "Illuminate the situation with knowledge before turning an impression into a decision.", FR: "Éclaire la situation par la connaissance avant de transformer une impression en décision.", DE: "Erhelle die Situation mit Wissen, bevor du einen Eindruck in eine Entscheidung verwandelst.", PT: "Ilumine a situação com conhecimento antes de transformar uma impressão em decisão." }, attribute: { EN: "Book and flame", FR: "Livre et flamme", DE: "Buch und Flamme", PT: "Livro e chama" }, keys: [{ EN: "wisdom", FR: "sagesse", DE: "Weisheit", PT: "sabedoria" }, { EN: "discernment", FR: "discernement", DE: "Urteilsvermögen", PT: "discernimento" }] },
  { name: { EN: "Archangel Raguel", FR: "Archange Raguel", DE: "Erzengel Raguel", PT: "Arcanjo Raguel" }, role: { EN: "Justice and harmony", FR: "Justice et harmonie", DE: "Gerechtigkeit und Harmonie", PT: "Justiça e harmonia" }, message: { EN: "Seek a fair agreement that restores balance without hiding the conflict.", FR: "Cherche un accord juste qui répare l'équilibre sans cacher le conflit.", DE: "Suche eine faire Vereinbarung, die das Gleichgewicht wiederherstellt, ohne den Konflikt zu verbergen.", PT: "Busque um acordo justo que repare o equilíbrio sem esconder o conflito." }, attribute: { EN: "Scale", FR: "Balance", DE: "Waage", PT: "Balança" }, keys: [{ EN: "justice", FR: "justice", DE: "Gerechtigkeit", PT: "justiça" }, { EN: "harmony", FR: "harmonie", DE: "Harmonie", PT: "harmonia" }] },
  { name: { EN: "Archangel Sariel", FR: "Archange Sariel", DE: "Erzengel Sariel", PT: "Arcanjo Sariel" }, role: { EN: "Knowledge and guidance", FR: "Connaissance et orientation", DE: "Wissen und Orientierung", PT: "Conhecimento e orientação" }, message: { EN: "Observe the full cycle before judging an isolated moment.", FR: "Observe le cycle complet avant de juger un moment isolé.", DE: "Betrachte den gesamten Zyklus, bevor du einen isolierten Moment beurteilst.", PT: "Observe o ciclo completo antes de julgar um momento isolado." }, attribute: { EN: "Moon and scroll", FR: "Lune et parchemin", DE: "Mond und Schriftrolle", PT: "Lua e pergaminho" }, keys: [{ EN: "knowledge", FR: "connaissance", DE: "Wissen", PT: "conhecimento" }, { EN: "cycles", FR: "cycles", DE: "Zyklen", PT: "ciclos" }] },
  { name: { EN: "Archangel Jeremiel", FR: "Archange Jeremiel", DE: "Erzengel Jeremiel", PT: "Arcanjo Jeremiel" }, role: { EN: "Review and hope", FR: "Révision et espoir", DE: "Rückschau und Hoffnung", PT: "Revisão e esperança" }, message: { EN: "Look honestly at what you've lived to choose what lesson to carry forward.", FR: "Regarde ce que tu as vécu avec honnêteté pour choisir quelle leçon emporter avec toi.", DE: "Schau ehrlich auf das Erlebte, um zu wählen, welche Lehre du mitnimmst.", PT: "Olhe para o vivido com honestidade para escolher qual aprendizado levar consigo." }, attribute: { EN: "Mirror", FR: "Miroir", DE: "Spiegel", PT: "Espelho" }, keys: [{ EN: "review", FR: "révision", DE: "Rückschau", PT: "revisão" }, { EN: "hope", FR: "espoir", DE: "Hoffnung", PT: "esperança" }] },
  { name: { EN: "Archangel Selaphiel", FR: "Archange Selaphiel", DE: "Erzengel Selaphiel", PT: "Arcanjo Selaphiel" }, role: { EN: "Prayer and stillness", FR: "Prière et recueillement", DE: "Gebet und Sammlung", PT: "Oração e recolhimento" }, message: { EN: "Reduce the noise and voice sincerely what you need to ask or understand.", FR: "Réduis le bruit et formule avec sincérité ce que tu as besoin de demander ou de comprendre.", DE: "Verringere den Lärm und formuliere aufrichtig, was du erbitten oder verstehen musst.", PT: "Reduza o ruído e formule com sinceridade o que precisa pedir ou compreender." }, attribute: { EN: "Censer", FR: "Encensoir", DE: "Weihrauchfass", PT: "Incensário" }, keys: [{ EN: "prayer", FR: "prière", DE: "Gebet", PT: "oração" }, { EN: "presence", FR: "présence", DE: "Präsenz", PT: "presença" }] },
  { name: { EN: "Archangel Jegudiel", FR: "Archange Jegudiel", DE: "Erzengel Jegudiel", PT: "Arcanjo Jegudiel" }, role: { EN: "Effort and responsibility", FR: "Effort et responsabilité", DE: "Anstrengung und Verantwortung", PT: "Esforço e responsabilidade" }, message: { EN: "Honor your work through a job well done, not just through intention.", FR: "Honore ton travail par une action bien faite, pas seulement par l'intention.", DE: "Ehre deine Arbeit durch eine gut gemachte Tat, nicht nur durch Absicht.", PT: "Honre seu trabalho por meio de uma ação bem feita, não apenas de intenção." }, attribute: { EN: "Crown and staff", FR: "Couronne et bâton", DE: "Krone und Stab", PT: "Coroa e bastão" }, keys: [{ EN: "effort", FR: "effort", DE: "Anstrengung", PT: "esforço" }, { EN: "responsibility", FR: "responsabilité", DE: "Verantwortung", PT: "responsabilidade" }] },
  { name: { EN: "Archangel Barachiel", FR: "Archange Barachiel", DE: "Erzengel Barachiel", PT: "Arcanjo Barachiel" }, role: { EN: "Blessing and gratitude", FR: "Bénédiction et gratitude", DE: "Segen und Dankbarkeit", PT: "Bênção e gratidão" }, message: { EN: "Recognize what already sustains your life and share it responsibly.", FR: "Reconnais ce qui soutient déjà ta vie et partage-le de manière responsable.", DE: "Erkenne, was dein Leben bereits trägt, und teile es verantwortungsvoll.", PT: "Reconheça o que já sustenta sua vida e compartilhe-o de forma responsável." }, attribute: { EN: "White roses", FR: "Roses blanches", DE: "Weiße Rosen", PT: "Rosas brancas" }, keys: [{ EN: "blessing", FR: "bénédiction", DE: "Segen", PT: "bênção" }, { EN: "gratitude", FR: "gratitude", DE: "Dankbarkeit", PT: "gratidão" }] },
  { name: { EN: "Metatron", FR: "Metatron", DE: "Metatron", PT: "Metatron" }, role: { EN: "Order and record", FR: "Ordre et registre", DE: "Ordnung und Aufzeichnung", PT: "Ordem e registro" }, message: { EN: "Organize ideas, timing, and commitments until the essential pattern becomes visible.", FR: "Organise idées, temps et engagements jusqu'à rendre visible le schéma essentiel.", DE: "Ordne Ideen, Zeiten und Verpflichtungen, bis das wesentliche Muster sichtbar wird.", PT: "Organize ideias, tempos e compromissos até tornar visível o padrão essencial." }, attribute: { EN: "Geometry and writing", FR: "Géométrie et écriture", DE: "Geometrie und Schrift", PT: "Geometria e escrita" }, keys: [{ EN: "order", FR: "ordre", DE: "Ordnung", PT: "ordem" }, { EN: "integration", FR: "intégration", DE: "Integration", PT: "integração" }] },
  { role: { EN: "Prayer and music", FR: "Prière et musique", DE: "Gebet und Musik", PT: "Oração e música" }, message: { EN: "Turn your intention into a concrete practice and let rhythm sustain the process.", FR: "Transforme ton intention en une pratique concrète et laisse le rythme soutenir le processus.", DE: "Verwandle deine Absicht in eine konkrete Praxis und lass den Rhythmus den Prozess tragen.", PT: "Transforme sua intenção em uma prática concreta e permita que o ritmo sustente o processo." }, attribute: { EN: "Music and earth", FR: "Musique et terre", DE: "Musik und Erde", PT: "Música e terra" }, keys: [{ EN: "prayer", FR: "prière", DE: "Gebet", PT: "oração" }, { EN: "grounding", FR: "ancrage", DE: "Verwurzelung", PT: "enraizamento" }] },
  { role: { EN: "Mystery and knowledge", FR: "Mystère et connaissance", DE: "Geheimnis und Wissen", PT: "Mistério e conhecimento" }, message: { EN: "Study what you don't understand without rushing to fill the gaps with fantasy.", FR: "Étudie ce que tu ne comprends pas sans te précipiter à combler les vides avec l'imagination.", DE: "Erforsche, was du nicht verstehst, ohne dich zu beeilen, die Lücken mit Fantasie zu füllen.", PT: "Estude o que você não compreende sem se apressar em preencher os vazios com fantasia." }, attribute: { EN: "Book and rainbow", FR: "Livre et arc-en-ciel", DE: "Buch und Regenbogen", PT: "Livro e arco-íris" }, keys: [{ EN: "mystery", FR: "mystère", DE: "Geheimnis", PT: "mistério" }, { EN: "study", FR: "étude", DE: "Studium", PT: "estudo" }] },
  { role: { EN: "Beauty and wisdom", FR: "Beauté et sagesse", DE: "Schönheit und Weisheit", PT: "Beleza e sabedoria" }, message: { EN: "Put your surroundings and thoughts in order to tell what's beautiful from what's merely attractive.", FR: "Mets de l'ordre dans ton environnement et tes pensées pour distinguer le beau du simplement attirant.", DE: "Ordne dein Umfeld und deine Gedanken, um das Schöne vom bloß Attraktiven zu unterscheiden.", PT: "Ordene seu ambiente e seus pensamentos para distinguir o belo do meramente atraente." }, attribute: { EN: "Golden light and flowers", FR: "Lumière dorée et fleurs", DE: "Goldenes Licht und Blumen", PT: "Luz dourada e flores" }, keys: [{ EN: "beauty", FR: "beauté", DE: "Schönheit", PT: "beleza" }, { EN: "wisdom", FR: "sagesse", DE: "Weisheit", PT: "sabedoria" }] },
  { role: { EN: "Peace and reconciliation", FR: "Paix et réconciliation", DE: "Frieden und Versöhnung", PT: "Paz e reconciliação" }, message: { EN: "Approach the bond from self-respect and a genuine willingness to listen.", FR: "Approche-toi du lien depuis le respect de toi-même et une réelle volonté d'écouter.", DE: "Nähere dich der Bindung aus Selbstachtung und echter Bereitschaft zuzuhören.", PT: "Aproxime-se do vínculo a partir do respeito próprio e da vontade real de escutar." }, attribute: { EN: "Heart and roses", FR: "Cœur et roses", DE: "Herz und Rosen", PT: "Coração e rosas" }, keys: [{ EN: "peace", FR: "paix", DE: "Frieden", PT: "paz" }, { EN: "reconciliation", FR: "réconciliation", DE: "Versöhnung", PT: "reconciliação" }] },
  { role: { EN: "Mercy and forgiveness", FR: "Miséricorde et pardon", DE: "Gnade und Vergebung", PT: "Misericórdia e perdão" }, message: { EN: "Release the weight you can release without denying what happened or abandoning your limits.", FR: "Lâche le poids que tu peux lâcher sans nier ce qui s'est passé ni abandonner tes limites.", DE: "Lass das Gewicht los, das du loslassen kannst, ohne das Geschehene zu leugnen oder deine Grenzen aufzugeben.", PT: "Solte o peso que você pode soltar sem negar o que aconteceu nem abandonar seus limites." }, attribute: { EN: "Cup and violet light", FR: "Coupe et lumière violette", DE: "Kelch und violettes Licht", PT: "Cálice e luz violeta" }, keys: [{ EN: "mercy", FR: "miséricorde", DE: "Gnade", PT: "misericórdia" }, { EN: "forgiveness", FR: "pardon", DE: "Vergebung", PT: "perdão" }] },
  { role: { EN: "Grace and joy", FR: "Grâce et joie", DE: "Anmut und Freude", PT: "Graça e alegria" }, message: { EN: "Let simple wellbeing take place without demanding an extraordinary reason.", FR: "Permets au bien-être simple d'avoir lieu sans exiger une raison extraordinaire.", DE: "Lass einfaches Wohlbefinden zu, ohne einen außergewöhnlichen Grund zu verlangen.", PT: "Permita que o bem-estar simples aconteça sem exigir uma razão extraordinária." }, attribute: { EN: "Moon and silver rose", FR: "Lune et rose argentée", DE: "Mond und silberne Rose", PT: "Lua e rosa prateada" }, keys: [{ EN: "grace", FR: "grâce", DE: "Anmut", PT: "graça" }, { EN: "joy", FR: "joie", DE: "Freude", PT: "alegria" }] },
  { role: { EN: "Nature and courage", FR: "Nature et courage", DE: "Natur und Mut", PT: "Natureza e coragem" }, message: { EN: "Recover strength through the body, the earth, and a brave but proportionate action.", FR: "Retrouve ta force à travers le corps, la terre et une action courageuse mais proportionnée.", DE: "Gewinne Kraft zurück durch den Körper, die Erde und eine mutige, aber angemessene Handlung.", PT: "Recupere força por meio do corpo, da terra e de uma ação corajosa, mas proporcional." }, attribute: { EN: "Lion and landscape", FR: "Lion et paysage", DE: "Löwe und Landschaft", PT: "Leão e paisagem" }, keys: [{ EN: "nature", FR: "nature", DE: "Natur", PT: "natureza" }, { EN: "courage", FR: "courage", DE: "Mut", PT: "coragem" }] },
  { role: { EN: "Transition and comfort", FR: "Transition et réconfort", DE: "Übergang und Trost", PT: "Transição e consolo" }, message: { EN: "Accompany the closing with compassion; ending a stage also requires care.", FR: "Accompagne la clôture avec compassion ; terminer une étape demande aussi du soin.", DE: "Begleite den Abschluss mit Mitgefühl; eine Etappe zu beenden braucht ebenfalls Fürsorge.", PT: "Acompanhe o encerramento com compaixão; terminar uma etapa também exige cuidado." }, attribute: { EN: "Threshold", FR: "Seuil", DE: "Schwelle", PT: "Limiar" }, keys: [{ EN: "transition", FR: "transition", DE: "Übergang", PT: "transição" }, { EN: "comfort", FR: "réconfort", DE: "Trost", PT: "consolo" }] },
  { role: { EN: "Time and patience", FR: "Temps et patience", DE: "Zeit und Geduld", PT: "Tempo e paciência" }, message: { EN: "Accept the real pace of the process and use the wait to prepare yourself.", FR: "Accepte le rythme réel du processus et utilise l'attente pour te préparer.", DE: "Akzeptiere das wahre Tempo des Prozesses und nutze das Warten, um dich vorzubereiten.", PT: "Aceite o ritmo real do processo e use a espera para se preparar." }, attribute: { EN: "Hourglass", FR: "Sablier", DE: "Sanduhr", PT: "Ampulheta" }, keys: [{ EN: "time", FR: "temps", DE: "Zeit", PT: "tempo" }, { EN: "patience", FR: "patience", DE: "Geduld", PT: "paciência" }] },
  { role: { EN: "Harmony and affection", FR: "Harmonie et affection", DE: "Harmonie und Zuneigung", PT: "Harmonia e afeto" }, message: { EN: "Cultivate a relationship where affection and dignity can coexist.", FR: "Cultive une relation où l'affection et la dignité peuvent coexister.", DE: "Pflege eine Beziehung, in der Zuneigung und Würde nebeneinander bestehen können.", PT: "Cultive um relacionamento onde o afeto e a dignidade possam coexistir." }, attribute: { EN: "Copper rose", FR: "Rose cuivrée", DE: "Kupferrose", PT: "Rosa cobreada" }, keys: [{ EN: "harmony", FR: "harmonie", DE: "Harmonie", PT: "harmonia" }, { EN: "affection", FR: "affection", DE: "Zuneigung", PT: "afeto" }] },
  { role: { EN: "Expansion and generosity", FR: "Expansion et générosité", DE: "Ausdehnung und Großzügigkeit", PT: "Expansão e generosidade" }, message: { EN: "Manage abundance with judgment and let it benefit more than one person.", FR: "Gère l'abondance avec discernement et laisse-la profiter à plus d'une personne.", DE: "Verwalte den Überfluss mit Urteilsvermögen und lass ihn mehr als einer Person zugutekommen.", PT: "Administre a abundância com critério e deixe que beneficie mais de uma pessoa." }, attribute: { EN: "Cornucopia", FR: "Corne d'abondance", DE: "Füllhorn", PT: "Cornucópia" }, keys: [{ EN: "expansion", FR: "expansion", DE: "Ausdehnung", PT: "expansão" }, { EN: "generosity", FR: "générosité", DE: "Großzügigkeit", PT: "generosidade" }] },
  { role: { EN: "Hope and return", FR: "Espoir et retour", DE: "Hoffnung und Rückkehr", PT: "Esperança e retorno" }, message: { EN: "Return to what orients you and repair with actions what can still be repaired.", FR: "Reviens à ce qui t'oriente et répare par des actes ce qui peut encore l'être.", DE: "Kehre zu dem zurück, was dich orientiert, und repariere mit Taten, was noch reparierbar ist.", PT: "Volte para aquilo que o orienta e repare com atos o que ainda for reparável." }, attribute: { EN: "Lantern", FR: "Lanterne", DE: "Laterne", PT: "Lanterna" }, keys: [{ EN: "hope", FR: "espoir", DE: "Hoffnung", PT: "esperança" }, { EN: "return", FR: "retour", DE: "Rückkehr", PT: "retorno" }] },
  { role: { EN: "Vision and expectation", FR: "Vision et attente", DE: "Vision und Erwartung", PT: "Visão e expectativa" }, message: { EN: "Watch the horizon without abandoning the concrete needs of the present.", FR: "Observe l'horizon sans abandonner les besoins concrets du présent.", DE: "Betrachte den Horizont, ohne die konkreten Bedürfnisse der Gegenwart aufzugeben.", PT: "Observe o horizonte sem abandonar as necessidades concretas do presente." }, attribute: { EN: "Stars and scroll", FR: "Étoiles et parchemin", DE: "Sterne und Schriftrolle", PT: "Estrelas e pergaminho" }, keys: [{ EN: "vision", FR: "vision", DE: "Vision", PT: "visão" }, { EN: "perspective", FR: "perspective", DE: "Perspektive", PT: "perspectiva" }] },
  { role: { EN: "Contemplation and understanding", FR: "Contemplation et compréhension", DE: "Kontemplation und Verständnis", PT: "Contemplação e compreensão" }, message: { EN: "Stay with the question until a deeper understanding appears.", FR: "Reste avec la question jusqu'à ce qu'apparaisse une compréhension plus profonde.", DE: "Bleib bei der Frage, bis ein tieferes Verständnis erscheint.", PT: "Permaneça com a pergunta até que apareça uma compreensão mais profunda." }, attribute: { EN: "Vessel and water", FR: "Vase et eau", DE: "Gefäß und Wasser", PT: "Vasilha e água" }, keys: [{ EN: "contemplation", FR: "contemplation", DE: "Kontemplation", PT: "contemplação" }, { EN: "understanding", FR: "compréhension", DE: "Verständnis", PT: "compreensão" }] },
  { role: { EN: "Presence and consecration", FR: "Présence et consécration", DE: "Präsenz und Weihe", PT: "Presença e consagração" }, message: { EN: "Treat this moment as worthy of your full attention.", FR: "Traite ce moment comme digne d'une attention complète.", DE: "Behandle diesen Moment als würdig deiner vollen Aufmerksamkeit.", PT: "Trate este momento como algo digno de atenção completa." }, attribute: { EN: "Fire and incense", FR: "Feu et encens", DE: "Feuer und Weihrauch", PT: "Fogo e incenso" }, keys: [{ EN: "presence", FR: "présence", DE: "Präsenz", PT: "presença" }, { EN: "dedication", FR: "dévouement", DE: "Hingabe", PT: "dedicação" }] },
  { role: { EN: "Music and expression", FR: "Musique et expression", DE: "Musik und Ausdruck", PT: "Música e expressão" }, message: { EN: "Give audible or visible form to what still lives only inside you.", FR: "Donne une forme audible ou visible à ce qui ne vit encore qu'en toi.", DE: "Gib dem, was noch nur in dir lebt, eine hörbare oder sichtbare Form.", PT: "Dê forma audível ou visível ao que ainda vive só dentro de você." }, attribute: { EN: "Sheet music and quill", FR: "Partition et plume", DE: "Notenblatt und Feder", PT: "Partitura e pena" }, keys: [{ EN: "expression", FR: "expression", DE: "Ausdruck", PT: "expressão" }, { EN: "creativity", FR: "créativité", DE: "Kreativität", PT: "criatividade" }] },
  { role: { EN: "Silence and acceptance", FR: "Silence et acceptation", DE: "Stille und Annahme", PT: "Silêncio e aceitação" }, message: { EN: "Don't force words where silence can hold a difficult truth.", FR: "Ne force pas les mots là où le silence peut soutenir une vérité difficile.", DE: "Erzwinge keine Worte, wo Stille eine schwierige Wahrheit tragen kann.", PT: "Não force palavras onde o silêncio pode sustentar uma verdade difícil." }, attribute: { EN: "Closed book", FR: "Livre fermé", DE: "Geschlossenes Buch", PT: "Livro fechado" }, keys: [{ EN: "silence", FR: "silence", DE: "Stille", PT: "silêncio" }, { EN: "acceptance", FR: "acceptation", DE: "Annahme", PT: "aceitação" }] },
  { role: { EN: "Night and rest", FR: "Nuit et repos", DE: "Nacht und Ruhe", PT: "Noite e descanso" }, message: { EN: "Protect your rest; a tired mind turns uncertainty into threat.", FR: "Protège ton repos ; un esprit fatigué transforme l'incertitude en menace.", DE: "Schütze deine Ruhe; ein erschöpfter Geist macht aus Ungewissheit eine Bedrohung.", PT: "Proteja seu descanso; a mente cansada transforma incerteza em ameaça." }, attribute: { EN: "Starry veil", FR: "Voile étoilé", DE: "Sternenschleier", PT: "Véu estrelado" }, keys: [{ EN: "rest", FR: "repos", DE: "Ruhe", PT: "descanso" }, { EN: "protection", FR: "protection", DE: "Schutz", PT: "proteção" }] },
  { role: { EN: "Fire and protection", FR: "Feu et protection", DE: "Feuer und Schutz", PT: "Fogo e proteção" }, message: { EN: "Use your intensity to illuminate and protect, not to react without measure.", FR: "Utilise ton intensité pour éclairer et protéger, pas pour réagir sans mesure.", DE: "Nutze deine Intensität, um zu erleuchten und zu schützen, nicht um maßlos zu reagieren.", PT: "Use sua intensidade para iluminar e proteger, não para reagir sem medida." }, attribute: { EN: "Fire and crystal", FR: "Feu et cristal", DE: "Feuer und Kristall", PT: "Fogo e cristal" }, keys: [{ EN: "fire", FR: "feu", DE: "Feuer", PT: "fogo" }, { EN: "protection", FR: "protection", DE: "Schutz", PT: "proteção" }] },
  { role: { EN: "Moral courage", FR: "Courage moral", DE: "Moralischer Mut", PT: "Coragem moral" }, message: { EN: "Hold on to what's right even when it brings no immediate recognition.", FR: "Tiens bon sur ce qui est juste, même sans reconnaissance immédiate.", DE: "Halte an dem fest, was richtig ist, auch wenn es keine sofortige Anerkennung bringt.", PT: "Sustente o que é correto mesmo quando isso não traga reconhecimento imediato." }, attribute: { EN: "Standard", FR: "Étendard", DE: "Feldzeichen", PT: "Estandarte" }, keys: [{ EN: "courage", FR: "courage", DE: "Mut", PT: "coragem" }, { EN: "integrity", FR: "intégrité", DE: "Integrität", PT: "integridade" }] },
  { role: { EN: "Purification and review", FR: "Purification et révision", DE: "Reinigung und Überprüfung", PT: "Purificação e revisão" }, message: { EN: "Clear out habits and commitments that no longer match your direction.", FR: "Élimine les habitudes et engagements qui ne correspondent plus à ta direction.", DE: "Räume Gewohnheiten und Verpflichtungen aus, die nicht mehr zu deiner Richtung passen.", PT: "Limpe hábitos e compromissos que já não são coerentes com sua direção." }, attribute: { EN: "Water and bowl", FR: "Eau et coupe", DE: "Wasser und Schale", PT: "Água e tigela" }, keys: [{ EN: "purification", FR: "purification", DE: "Reinigung", PT: "purificação" }, { EN: "review", FR: "révision", DE: "Überprüfung", PT: "revisão" }] },
  { role: { EN: "Nature and sensitivity", FR: "Nature et sensibilité", DE: "Natur und Sensibilität", PT: "Natureza e sensibilidade" }, message: { EN: "Listen to your sensitivity without letting it absorb everything happening around you.", FR: "Écoute ta sensibilité sans la laisser absorber tout ce qui se passe autour de toi.", DE: "Höre auf deine Sensibilität, ohne sie alles absorbieren zu lassen, was um dich herum geschieht.", PT: "Escute sua sensibilidade sem permitir que ela absorva tudo o que acontece ao redor." }, attribute: { EN: "Flowers and water", FR: "Fleurs et eau", DE: "Blumen und Wasser", PT: "Flores e água" }, keys: [{ EN: "sensitivity", FR: "sensibilité", DE: "Sensibilität", PT: "sensibilidade" }, { EN: "nature", FR: "nature", DE: "Natur", PT: "natureza" }] },
  { role: { EN: "Will and beginning", FR: "Volonté et commencement", DE: "Wille und Anfang", PT: "Vontade e início" }, message: { EN: "Turn intention into a clear, achievable first step.", FR: "Transforme l'intention en un premier pas clair et réalisable.", DE: "Verwandle die Absicht in einen klaren, machbaren ersten Schritt.", PT: "Transforme a intenção em um primeiro passo claro e realizável." }, attribute: { EN: "Initial flame", FR: "Flamme initiale", DE: "Anfängliche Flamme", PT: "Chama inicial" }, keys: [{ EN: "will", FR: "volonté", DE: "Wille", PT: "vontade" }, { EN: "beginning", FR: "commencement", DE: "Anfang", PT: "início" }] },
  { role: { EN: "Union and reconciliation", FR: "Union et réconciliation", DE: "Vereinigung und Versöhnung", PT: "União e reconciliação" }, message: { EN: "Look for the point where two legitimate needs can meet.", FR: "Cherche le point où deux besoins légitimes peuvent se rencontrer.", DE: "Suche den Punkt, an dem sich zwei berechtigte Bedürfnisse treffen können.", PT: "Busque o ponto onde duas necessidades legítimas possam se encontrar." }, attribute: { EN: "Two currents and doves", FR: "Deux courants et colombes", DE: "Zwei Ströme und Tauben", PT: "Duas correntes e pombas" }, keys: [{ EN: "union", FR: "union", DE: "Vereinigung", PT: "união" }, { EN: "reconciliation", FR: "réconciliation", DE: "Versöhnung", PT: "reconciliação" }] },
  { role: { EN: "Construction and shelter", FR: "Construction et refuge", DE: "Aufbau und Zuflucht", PT: "Construção e refúgio" }, message: { EN: "Strengthen the structure before expanding the project.", FR: "Renforce la structure avant d'agrandir le projet.", DE: "Stärke die Struktur, bevor du das Projekt erweiterst.", PT: "Fortaleça a estrutura antes de ampliar o projeto." }, attribute: { EN: "Stone arch", FR: "Arche de pierre", DE: "Steinbogen", PT: "Arco de pedra" }, keys: [{ EN: "construction", FR: "construction", DE: "Aufbau", PT: "construção" }, { EN: "security", FR: "sécurité", DE: "Sicherheit", PT: "segurança" }] },
  { role: { EN: "Direction and discovery", FR: "Direction et découverte", DE: "Richtung und Entdeckung", PT: "Direção e descoberta" }, message: { EN: "Review the course and correct any deviation early.", FR: "Révise le cap et corrige tôt toute déviation.", DE: "Überprüfe den Kurs und korrigiere jede Abweichung frühzeitig.", PT: "Revise o rumo e corrija cedo qualquer desvio." }, attribute: { EN: "Celestial ship", FR: "Navire céleste", DE: "Himmlisches Schiff", PT: "Navio celeste" }, keys: [{ EN: "direction", FR: "direction", DE: "Richtung", PT: "direção" }, { EN: "discovery", FR: "découverte", DE: "Entdeckung", PT: "descoberta" }] },
  { role: { EN: "Learning and repair", FR: "Apprentissage et réparation", DE: "Lernen und Wiedergutmachung", PT: "Aprendizado e reparação" }, message: { EN: "Correct with patience and let the mistake turn into knowledge.", FR: "Corrige avec patience et laisse l'erreur devenir connaissance.", DE: "Korrigiere mit Geduld und lass den Fehler zu Wissen werden.", PT: "Corrija com paciência e permita que o erro se transforme em conhecimento." }, attribute: { EN: "Restored manuscript", FR: "Manuscrit restauré", DE: "Restauriertes Manuskript", PT: "Manuscrito restaurado" }, keys: [{ EN: "learning", FR: "apprentissage", DE: "Lernen", PT: "aprendizado" }, { EN: "repair", FR: "réparation", DE: "Wiedergutmachung", PT: "reparação" }] },
  { role: { EN: "Light and creativity", FR: "Lumière et créativité", DE: "Licht und Kreativität", PT: "Luz e criatividade" }, message: { EN: "Make your ability visible through a concrete work.", FR: "Rends ta capacité visible à travers une œuvre concrète.", DE: "Mach deine Fähigkeit durch ein konkretes Werk sichtbar.", PT: "Torne visível sua capacidade por meio de uma obra concreta." }, attribute: { EN: "Solar disc", FR: "Disque solaire", DE: "Sonnenscheibe", PT: "Disco solar" }, keys: [{ EN: "light", FR: "lumière", DE: "Licht", PT: "luz" }, { EN: "creativity", FR: "créativité", DE: "Kreativität", PT: "criatividade" }] },
  { role: { EN: "Patience and understanding", FR: "Patience et compréhension", DE: "Geduld und Verständnis", PT: "Paciência e compreensão" }, message: { EN: "Investigate the small details; that's where the missing piece may be.", FR: "Examine les petites choses ; c'est peut-être là que se trouve la pièce manquante.", DE: "Untersuche das Kleine; dort kann das fehlende Teil liegen.", PT: "Investigue o pequeno; ali pode estar a peça que falta." }, attribute: { EN: "Seed and clock", FR: "Graine et horloge", DE: "Samenkorn und Uhr", PT: "Semente e relógio" }, keys: [{ EN: "patience", FR: "patience", DE: "Geduld", PT: "paciência" }, { EN: "research", FR: "recherche", DE: "Erforschung", PT: "investigação" }] },
  { role: { EN: "Gratitude and harvest", FR: "Gratitude et récolte", DE: "Dankbarkeit und Ernte", PT: "Gratidão e colheita" }, message: { EN: "Acknowledge what you've received and care for the conditions that made it possible.", FR: "Reconnais ce que tu as reçu et prends soin des conditions qui l'ont rendu possible.", DE: "Erkenne, was du erhalten hast, und pflege die Bedingungen, die es möglich gemacht haben.", PT: "Reconheça o que recebeu e cuide das condições que o tornaram possível." }, attribute: { EN: "Grain and fields", FR: "Grain et champs", DE: "Korn und Felder", PT: "Grão e campos" }, keys: [{ EN: "gratitude", FR: "gratitude", DE: "Dankbarkeit", PT: "gratidão" }, { EN: "harvest", FR: "récolte", DE: "Ernte", PT: "colheita" }] },
  { role: { EN: "Mercy and trust", FR: "Miséricorde et confiance", DE: "Gnade und Vertrauen", PT: "Misericórdia e confiança" }, message: { EN: "Offer a chance for repair without abandoning your judgment.", FR: "Offre une chance de réparation sans abandonner ton discernement.", DE: "Biete eine Chance zur Wiedergutmachung, ohne dein Urteilsvermögen aufzugeben.", PT: "Ofereça uma oportunidade de reparação sem abandonar o critério." }, attribute: { EN: "Open chains", FR: "Chaînes ouvertes", DE: "Geöffnete Ketten", PT: "Correntes abertas" }, keys: [{ EN: "mercy", FR: "miséricorde", DE: "Gnade", PT: "misericórdia" }, { EN: "trust", FR: "confiance", DE: "Vertrauen", PT: "confiança" }] },
  { role: { EN: "Recovery and balance", FR: "Récupération et équilibre", DE: "Erholung und Gleichgewicht", PT: "Recuperação e equilíbrio" }, message: { EN: "Attend to yourself promptly and return gradually to a sustainable pace.", FR: "Prends soin de toi rapidement et reviens progressivement à un rythme durable.", DE: "Kümmere dich frühzeitig um dich selbst und kehre schrittweise zu einem tragfähigen Tempo zurück.", PT: "Cuide de si prontamente e volte gradualmente a um ritmo sustentável." }, attribute: { EN: "Healing bowl", FR: "Bol guérisseur", DE: "Heilende Schale", PT: "Tigela curativa" }, keys: [{ EN: "recovery", FR: "récupération", DE: "Erholung", PT: "recuperação" }, { EN: "balance", FR: "équilibre", DE: "Gleichgewicht", PT: "equilíbrio" }] },
  { role: { EN: "Dream and revelation", FR: "Rêve et révélation", DE: "Traum und Offenbarung", PT: "Sonho e revelação" }, message: { EN: "Record what emerges from the dream and evaluate it calmly upon waking.", FR: "Note ce qui émerge du rêve et évalue-le avec sérénité au réveil.", DE: "Halte fest, was aus dem Traum auftaucht, und bewerte es beim Erwachen mit Gelassenheit.", PT: "Registre o que emerge do sonho e avalie-o com serenidade ao despertar." }, attribute: { EN: "Constellations and harp", FR: "Constellations et harpe", DE: "Sternbilder und Harfe", PT: "Constelações e harpa" }, keys: [{ EN: "dream", FR: "rêve", DE: "Traum", PT: "sonho" }, { EN: "revelation", FR: "révélation", DE: "Offenbarung", PT: "revelação" }] },
];

export function translateAngel(index: number, field: "name" | "role" | "message" | "attribute", fallback: string, language: Language): string {
  if (language === "ES") return fallback;
  const row = ANGEL_T[index];
  if (!row) return fallback;
  if (field === "name") return row.name?.[language] || fallback;
  return row[field][language] || fallback;
}
export function translateAngelKeys(index: number, fallback: string[], language: Language): string[] {
  if (language === "ES") return fallback;
  const row = ANGEL_T[index];
  if (!row) return fallback;
  return row.keys.map((k, i) => k[language] || fallback[i]);
}

// ---------- Composite card localizers (used to build the oracle deck's display fields) ----------

export function localizeZenCard(card: { name: string; group: string; phase: string; message: string; question: string; action: string }, language: Language): { name: string; theme: string; message: string; detail: string } {
  const name = translateZenCardName(card.name, language);
  if (language === "ES") return { name, theme: `${card.group} · ${card.phase}`, message: card.message, detail: `${card.question} ${card.action}` };
  const group = translateZenGroup(card.group, language);
  const p = translateZenPhase(card.phase, language as Exclude<Language, "ES">);
  return { name, theme: `${group} · ${p?.phase || card.phase}`, message: p?.message || card.message, detail: `${p?.question || card.question} ${p?.action || card.action}` };
}

export function localizeAnimalCard(card: { name: string; meaning: string; message: string }, index: number, language: Language): { name: string; theme: string; message: string; detail: string } {
  const name = translateAnimal(index, "name", card.name, language);
  const meaning = translateAnimal(index, "meaning", card.meaning, language);
  const message = translateAnimal(index, "message", card.message, language);
  const detailByLanguage: Record<Language, string> = {
    ES: `Su cualidad es ${meaning.toLowerCase()}. Observa dónde puedes aplicarla de manera concreta.`,
    EN: `Its quality is ${meaning.toLowerCase()}. Notice where you can apply it concretely.`,
    FR: `Sa qualité est ${meaning.toLowerCase()}. Observe où tu peux l'appliquer concrètement.`,
    DE: `Seine Qualität ist ${meaning.toLowerCase()}. Beobachte, wo du sie konkret anwenden kannst.`,
    PT: `Sua qualidade é ${meaning.toLowerCase()}. Observe onde você pode aplicá-la de forma concreta.`,
  };
  return { name, theme: meaning, message, detail: detailByLanguage[language] || detailByLanguage.ES };
}

const ANGEL_DETAIL_LABEL: Localized4 & { ES: string } = { ES: "Tradición de referencia", EN: "Reference tradition", FR: "Tradition de référence", DE: "Bezugstradition", PT: "Tradição de referência" };

export function localizeAngelCard(card: { name: string; role: string; family: string; message: string; attribute: string; keys: string[]; tradition: string }, index: number, language: Language): { name: string; theme: string; message: string; detail: string } {
  const name = translateAngel(index, "name", card.name, language);
  const role = translateAngel(index, "role", card.role, language);
  const family = translateAngelFamily(card.family, language);
  const message = translateAngel(index, "message", card.message, language);
  const attribute = translateAngel(index, "attribute", card.attribute, language);
  const keys = translateAngelKeys(index, card.keys, language);
  const tradition = translateAngelTradition(card.tradition, language);
  const label = ANGEL_DETAIL_LABEL[language] || ANGEL_DETAIL_LABEL.ES;
  return { name, theme: `${role} · ${family}`, message, detail: `${attribute}. ${keys.join(", ")}. ${label}: ${tradition}.` };
}
