export type RiderCard = {
  id: string;
  name: string;
  en: string;
  arcana: "Mayor" | "Menor";
  suit: "Bastos" | "Copas" | "Espadas" | "Oros" | null;
  number: number;
  keys: string[];
  general: string;
  love: string;
  work: string;
  money: string;
  growth: string;
  advice: string;
  symbols: string;
  reversed: string;
  image: string;
};

type MajorSeed = Omit<RiderCard, "id" | "arcana" | "suit" | "image">;

const majorImages: Record<number, string> = {
  0: "00-fool.jpg",
  1: "01-magician.jpg",
  2: "02-priestess.jpg",
  6: "06-lovers.jpg",
  9: "09-hermit.jpg",
  10: "10-wheel.jpg",
  13: "13-death.jpg",
  14: "14-temperance.jpg",
  17: "17-star.jpg",
};

const majorSeeds: MajorSeed[] = [
  { number:0, name:"El Loco", en:"The Fool", keys:["inicio","libertad","confianza"], general:"Un comienzo invita a avanzar con apertura, sin ignorar los riesgos.", love:"Renovar la forma de vincularse y hablar con honestidad.", work:"Explorar una vía nueva con una prueba pequeña.", money:"Evitar impulsos y conservar margen de seguridad.", growth:"Recuperar curiosidad y flexibilidad.", advice:"Da el primer paso con atención.", symbols:"Camino, horizonte, equipaje ligero.", reversed:"Impulsividad, falta de dirección o miedo a comenzar." },
  { number:1, name:"El Mago", en:"The Magician", keys:["iniciativa","recursos","acción"], general:"Los recursos necesarios están disponibles si se usan con intención.", love:"La comunicación clara puede cambiar la dinámica.", work:"Conviene convertir una idea en una acción concreta.", money:"Ordenar los recursos antes de ampliarlos.", growth:"Reconocer la propia capacidad de elegir.", advice:"Enfoca tu energía en una acción verificable.", symbols:"Mesa, herramientas, infinito.", reversed:"Talento disperso, manipulación o comunicación poco clara." },
  { number:2, name:"La Sacerdotisa", en:"The High Priestess", keys:["intuición","pausa","profundidad"], general:"Hay información sutil que requiere silencio y observación.", love:"Escuchar lo no dicho sin convertir suposiciones en hechos.", work:"Esperar datos antes de decidir.", money:"Revisar detalles ocultos y condiciones no expresadas.", growth:"Confiar en la percepción y contrastarla.", advice:"Observa antes de actuar.", symbols:"Velo, luna, libro.", reversed:"Desconexión interna, información oculta o secretos confusos." },
  { number:3, name:"La Emperatriz", en:"The Empress", keys:["crecimiento","fertilidad","cuidado"], general:"Algo puede crecer si recibe tiempo, atención y condiciones adecuadas.", love:"El afecto se fortalece con presencia y cuidado recíproco.", work:"Una idea creativa tiene capacidad de desarrollarse.", money:"Los recursos crecen mejor con administración constante que con prisa.", growth:"Permitir que la creatividad y el cuerpo tengan un lugar real.", advice:"Cuida lo que deseas ver crecer.", symbols:"Trigo, corona de estrellas, jardín.", reversed:"Cuidado excesivo, dependencia o creatividad estancada." },
  { number:4, name:"El Emperador", en:"The Emperor", keys:["estructura","autoridad","límites"], general:"La situación necesita orden, reglas claras y responsabilidad.", love:"Un vínculo estable requiere límites y compromisos explícitos.", work:"Conviene establecer prioridades, funciones y plazos.", money:"Un presupuesto y una estructura firme protegen la estabilidad.", growth:"Aprender a ejercer autoridad sin rigidez.", advice:"Define la estructura antes de exigir resultados.", symbols:"Trono, carneros, armadura.", reversed:"Rigidez, control excesivo o falta de estructura." },
  { number:5, name:"El Hierofante", en:"The Hierophant", keys:["tradición","aprendizaje","guía"], general:"La experiencia acumulada, una institución o una enseñanza formal pueden orientar el proceso.", love:"Hablar de valores, acuerdos y compromiso evita expectativas incompatibles.", work:"Buscar mentoría o seguir un método probado puede ahorrar errores.", money:"Preferir reglas conocidas y asesoría competente.", growth:"Distinguir entre una tradición útil y una obediencia automática.", advice:"Aprende la regla antes de decidir si debes conservarla.", symbols:"Llaves, columnas, bendición.", reversed:"Dogma, rebeldía sin criterio o consejo inadecuado." },
  { number:6, name:"Los Enamorados", en:"The Lovers", keys:["elección","vínculo","valores"], general:"Una decisión pide coherencia entre deseo y valores.", love:"El vínculo requiere elección consciente y reciprocidad.", work:"Elegir alianzas compatibles con tus principios.", money:"No sacrificar estabilidad por aprobación.", growth:"Integrar partes aparentemente opuestas.", advice:"Decide desde tus valores, no desde la presión.", symbols:"Pareja, ángel, montaña.", reversed:"Desalineación, deslealtad o una decisión postergada." },
  { number:7, name:"El Carro", en:"The Chariot", keys:["determinación","avance","dirección"], general:"El avance depende de sostener una dirección y controlar fuerzas opuestas.", love:"La relación progresa si ambas partes acuerdan hacia dónde van.", work:"Tomar el mando y ejecutar un plan puede romper el estancamiento.", money:"Mantener el control del gasto mientras se persigue una meta.", growth:"Convertir voluntad en disciplina.", advice:"Elige un rumbo y evita dispersarte.", symbols:"Carro, esfinges, ciudad.", reversed:"Falta de control, agresividad o avance sin dirección." },
  { number:8, name:"La Fuerza", en:"Strength", keys:["fortaleza","dominio","compasión"], general:"La firmeza serena puede manejar una situación que la fuerza bruta empeoraría.", love:"La paciencia y el respeto contienen tensiones sin negar lo que ocurre.", work:"Sostener la presión con autocontrol demuestra capacidad real.", money:"Evitar decisiones financieras nacidas de ansiedad o orgullo.", growth:"Relacionarse con los impulsos sin quedar dominado por ellos.", advice:"Responde con firmeza, no con violencia.", symbols:"León, infinito, flores.", reversed:"Inseguridad, reacción impulsiva o pérdida de confianza." },
  { number:9, name:"El Ermitaño", en:"The Hermit", keys:["introspección","prudencia","sabiduría"], general:"La claridad llega al reducir el ruido externo.", love:"Tomar espacio puede aclarar necesidades reales.", work:"Revisar la experiencia antes del siguiente movimiento.", money:"Preferir sobriedad y análisis.", growth:"Convertir experiencia en criterio.", advice:"Haz una pausa deliberada.", symbols:"Farol, bastón, montaña.", reversed:"Aislamiento excesivo, soledad no elegida o evasión." },
  { number:10, name:"La Rueda de la Fortuna", en:"Wheel of Fortune", keys:["cambio","ciclo","adaptación"], general:"El contexto está cambiando; la respuesta útil es adaptarse.", love:"La relación entra en una nueva fase.", work:"Aprovechar una ventana sin depender del azar.", money:"Prepararse para variaciones.", growth:"Aceptar el movimiento de los ciclos.", advice:"Distingue lo que controlas de lo que no.", symbols:"Rueda, criaturas, cielo.", reversed:"Resistencia al cambio, mala sincronía o un patrón repetido." },
  { number:11, name:"La Justicia", en:"Justice", keys:["verdad","equilibrio","consecuencia"], general:"Los hechos, las decisiones previas y sus consecuencias deben mirarse con imparcialidad.", love:"La relación necesita honestidad, límites justos y responsabilidad compartida.", work:"Documentar acuerdos y evaluar con criterios objetivos.", money:"Revisar contratos, deudas y obligaciones con precisión.", growth:"Asumir la propia parte sin cargar con la de otros.", advice:"Decide con evidencia y acepta la consecuencia.", symbols:"Balanza, espada, columnas.", reversed:"Injusticia, negación de responsabilidad o información sesgada." },
  { number:12, name:"El Colgado", en:"The Hanged Man", keys:["pausa","perspectiva","entrega"], general:"Forzar el avance no ayudará; la situación pide otra perspectiva y una pausa consciente.", love:"Cambiar la forma de mirar el vínculo puede revelar lo que la insistencia oculta.", work:"Conviene detener una estrategia improductiva y reevaluar.", money:"No inmovilizar más recursos hasta entender el costo real.", growth:"Soltar temporalmente el control para comprender.", advice:"Detente y mira el problema desde otro ángulo.", symbols:"Árbol, halo, postura invertida.", reversed:"Estancamiento, sacrificio inútil o demora prolongada." },
  { number:13, name:"La Muerte", en:"Death", keys:["cierre","transformación","renovación"], general:"Un ciclo simbólico termina para liberar una forma nueva.", love:"Transformar una dinámica agotada; no implica un hecho literal.", work:"Cerrar una etapa o método que ya no sirve.", money:"Reestructurar hábitos financieros.", growth:"Soltar una identidad anterior.", advice:"Permite un cierre consciente.", symbols:"Amanecer, estandarte, paso.", reversed:"Apego, resistencia o incapacidad de cerrar una etapa concluida." },
  { number:14, name:"La Templanza", en:"Temperance", keys:["equilibrio","integración","paciencia"], general:"La mejor vía combina elementos sin forzar resultados.", love:"Regular emociones y construir acuerdos graduales.", work:"Coordinar ritmos y habilidades.", money:"Sostener un plan moderado.", growth:"Integrar extremos con paciencia.", advice:"Avanza de forma gradual y consistente.", symbols:"Copas, agua, sendero.", reversed:"Exceso, impaciencia o falta de medida." },
  { number:15, name:"El Diablo", en:"The Devil", keys:["apego","deseo","dependencia"], general:"Un deseo, miedo o hábito está ganando más poder del que conviene concederle.", love:"La atracción puede mezclarse con celos, control o dependencia.", work:"Una recompensa inmediata puede mantenerte atado a una condición dañina.", money:"Revisar deudas, consumos compulsivos y acuerdos que limitan.", growth:"Nombrar la cadena es el primer paso para dejar de alimentarla.", advice:"Identifica qué te controla y reduce su poder con hechos.", symbols:"Cadenas, antorcha, pedestal.", reversed:"Liberación gradual, negación del problema o recaída en una dependencia." },
  { number:16, name:"La Torre", en:"The Tower", keys:["ruptura","revelación","cambio"], general:"Una estructura inestable puede romperse y mostrar una verdad que ya no admite evasión.", love:"Una revelación o crisis obliga a revisar la base real del vínculo.", work:"Un cambio brusco expone fallas de estructura o planificación.", money:"Proteger liquidez y evitar riesgos innecesarios ante una alteración súbita.", growth:"Reconstruir desde la verdad, no desde la apariencia.", advice:"Atiende primero lo urgente y luego reconstruye mejor.", symbols:"Rayo, corona, torre.", reversed:"Crisis evitada por poco, cambio aplazado o derrumbe interior." },
  { number:17, name:"La Estrella", en:"The Star", keys:["esperanza","autenticidad","renovación"], general:"Se abre una etapa de recuperación y visión más limpia.", love:"Mostrar vulnerabilidad con límites sanos.", work:"Reconectar con un propósito inspirador.", money:"Recuperación gradual mediante claridad.", growth:"Volver a confiar en la propia dirección.", advice:"Cuida la esperanza con acciones pequeñas.", symbols:"Estrellas, agua, tierra.", reversed:"Desánimo, pérdida de confianza o idealización." },
  { number:18, name:"La Luna", en:"The Moon", keys:["incertidumbre","intuición","miedo"], general:"La percepción está mezclada con temor, deseo e información incompleta.", love:"No confundir intuición con suposición; hace falta confirmar lo que ocurre.", work:"Revisar rumores, ambigüedades y datos faltantes antes de actuar.", money:"Evitar compromisos mientras los términos no sean claros.", growth:"Escuchar el mundo interior sin tratar cada temor como un hecho.", advice:"Avanza despacio y verifica lo que no está claro.", symbols:"Luna, perros, sendero.", reversed:"Confusión que empieza a disiparse o engaño que queda expuesto." },
  { number:19, name:"El Sol", en:"The Sun", keys:["claridad","vitalidad","éxito"], general:"La situación gana claridad, energía y posibilidades de un resultado visible.", love:"La apertura y la alegría compartida fortalecen el vínculo.", work:"El trabajo puede recibir reconocimiento y mostrar resultados concretos.", money:"Mayor estabilidad si la confianza se mantiene respaldada por un plan.", growth:"Permitirse disfrutar sin minimizar el esfuerzo realizado.", advice:"Haz visible lo que funciona y compártelo.", symbols:"Sol, niño, girasoles.", reversed:"Optimismo forzado, retraso en el éxito o dificultad para disfrutar." },
  { number:20, name:"El Juicio", en:"Judgement", keys:["despertar","evaluación","renovación"], general:"Ha llegado el momento de evaluar lo vivido y responder a una llamada que ya es clara.", love:"Una conversación honesta permite reparar, redefinir o cerrar el vínculo.", work:"Revisar la trayectoria ayuda a tomar una decisión de mayor alcance.", money:"Corregir decisiones pasadas antes de iniciar un nuevo ciclo.", growth:"Dejar de vivir desde una versión antigua de ti mismo.", advice:"Escucha la llamada y responde con responsabilidad.", symbols:"Trompeta, figuras, bandera.", reversed:"Autocrítica paralizante, negación de la llamada o evaluación incompleta." },
  { number:21, name:"El Mundo", en:"The World", keys:["culminación","integración","logro"], general:"Un ciclo alcanza madurez y puede cerrarse con una visión completa de lo aprendido.", love:"El vínculo encuentra integración o llega a una conclusión que permite avanzar.", work:"Un proyecto se completa y abre un nivel nuevo de responsabilidad.", money:"Consolidar resultados antes de expandirse.", growth:"Reconocer la totalidad del recorrido y ocupar el lugar ganado.", advice:"Cierra bien esta etapa antes de iniciar la siguiente.", symbols:"Corona, cuatro seres, danza.", reversed:"Cierre incompleto, meta retrasada o dificultad para reconocer el logro." },
];

type MinorSeed = {
  name: string;
  en: string;
  keys: string[];
  general: string;
  love: string;
  work: string;
  money: string;
  growth: string;
  advice: string;
  reversed: string;
};

const ranks = ["As", "Dos", "Tres", "Cuatro", "Cinco", "Seis", "Siete", "Ocho", "Nueve", "Diez", "Sota", "Caballero", "Reina", "Rey"];
const englishRanks = ["Ace", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten", "Page", "Knight", "Queen", "King"];

const wands: MinorSeed[] = [
  { name:"As", en:"Ace", keys:["inicio","inspiración","acción"], general:"Una idea o impulso nuevo tiene fuerza para comenzar.", love:"La atracción o el entusiasmo renuevan la relación, pero necesitan dirección.", work:"Surge una oportunidad creativa que conviene probar pronto.", money:"Una iniciativa puede abrir ingresos si se valida antes de invertir más.", growth:"Recuperar deseo, energía y capacidad de iniciar.", advice:"Convierte el entusiasmo en un primer paso concreto.", reversed:"Falta de energía, comienzo retrasado o impulso sin dirección." },
  { name:"Dos", en:"Two", keys:["planificación","decisión","expansión"], general:"Ya existe una base; ahora toca elegir hacia dónde expandirse.", love:"La relación necesita hablar de futuro y dirección compartida.", work:"Comparar opciones antes de comprometer el proyecto.", money:"Planear la expansión sin descuidar los recursos actuales.", growth:"Atreverse a mirar más allá de lo conocido.", advice:"Elige un rumbo y define el siguiente movimiento.", reversed:"Plan limitado, miedo a salir de lo conocido o decisión aplazada." },
  { name:"Tres", en:"Three", keys:["progreso","expansión","visión"], general:"Lo iniciado empieza a mostrar alcance y requiere visión de mediano plazo.", love:"El vínculo puede crecer si ambos miran hacia una meta compatible.", work:"Los primeros resultados permiten ampliar el proyecto.", money:"Una inversión empieza a rendir, aunque todavía necesita seguimiento.", growth:"Aprender a confiar en un proceso ya puesto en marcha.", advice:"Observa los resultados y prepara la siguiente etapa.", reversed:"Demoras, expectativas poco realistas o expansión mal calculada." },
  { name:"Cuatro", en:"Four", keys:["celebración","estabilidad","comunidad"], general:"Hay una base estable que merece reconocerse y compartirse.", love:"La relación puede consolidarse mediante acuerdos y celebración.", work:"Un logro del equipo crea un momento de estabilidad.", money:"La organización permite disfrutar un resultado sin perder control.", growth:"Reconocer avances y permitir apoyo de la comunidad.", advice:"Celebra lo logrado y fortalece la base.", reversed:"Inestabilidad doméstica, celebración incompleta o falta de apoyo." },
  { name:"Cinco", en:"Five", keys:["competencia","tensión","conflicto"], general:"Varias fuerzas compiten y dificultan coordinar una dirección común.", love:"Las diferencias pueden convertirse en discusiones repetidas si nadie escucha.", work:"La competencia exige reglas claras y objetivos compartidos.", money:"Evitar gastar o invertir sólo para superar a otros.", growth:"Aprender a defender una idea sin convertir todo en lucha.", advice:"Ordena el desacuerdo antes de intentar ganar.", reversed:"Conflicto evitado, resentimiento contenido o competencia desleal." },
  { name:"Seis", en:"Six", keys:["reconocimiento","éxito","avance"], general:"El esfuerzo recibe una respuesta favorable y reconocimiento visible.", love:"El vínculo mejora cuando ambos reconocen los logros del otro.", work:"Una victoria o promoción confirma el avance.", money:"El resultado es favorable, pero no debe alimentar gastos por apariencia.", growth:"Aceptar reconocimiento sin depender de él.", advice:"Recibe el logro y mantén la disciplina.", reversed:"Falta de reconocimiento, orgullo herido o éxito más aparente que real." },
  { name:"Siete", en:"Seven", keys:["defensa","posición","resistencia"], general:"Has ganado terreno, pero necesitas sostenerlo frente a presión o competencia.", love:"Conviene defender límites sin tratar a la pareja como adversario.", work:"Mantener una postura clara ante cuestionamientos.", money:"Proteger recursos y no ceder a presiones poco convenientes.", growth:"Confiar en la posición ganada sin volverse rígido.", advice:"Defiende lo esencial y elige bien tus batallas.", reversed:"Agotamiento, defensa débil o sensación de estar superado." },
  { name:"Ocho", en:"Eight", keys:["movimiento","rapidez","mensaje"], general:"Los acontecimientos se aceleran y exigen una respuesta oportuna.", love:"Una conversación o encuentro puede avanzar rápidamente.", work:"Noticias, viajes o decisiones ponen el proyecto en movimiento.", money:"Una operación puede resolverse pronto; revisa antes de confirmar.", growth:"Aprender a actuar con rapidez sin perder precisión.", advice:"Responde a tiempo y evita distraerte.", reversed:"Demoras, mensajes cruzados o precipitación." },
  { name:"Nueve", en:"Nine", keys:["resistencia","prudencia","límites"], general:"El cansancio es real, pero todavía existe capacidad para sostener la posición.", love:"Las heridas previas pueden volver defensiva la relación.", work:"Proteger el avance sin trabajar desde la desconfianza permanente.", money:"Mantener una reserva ante posibles imprevistos.", growth:"Distinguir entre resiliencia y vivir siempre a la defensiva.", advice:"Cuida tu energía y mantén el límite necesario.", reversed:"Agotamiento, paranoia o incapacidad para bajar la guardia." },
  { name:"Diez", en:"Ten", keys:["carga","responsabilidad","esfuerzo"], general:"La responsabilidad se ha vuelto demasiado pesada o está mal distribuida.", love:"Una persona puede estar sosteniendo más de lo que le corresponde.", work:"El exceso de tareas amenaza la calidad y el bienestar.", money:"Compromisos acumulados reducen margen y flexibilidad.", growth:"Aprender a delegar y a decir que no.", advice:"Reduce, delega o reordena la carga.", reversed:"Colapso por exceso, carga que empieza a soltarse o evasión de deberes." },
  { name:"Sota", en:"Page", keys:["exploración","mensaje","entusiasmo"], general:"Una noticia o curiosidad despierta ganas de explorar algo nuevo.", love:"Surge un acercamiento espontáneo, todavía inmaduro pero sincero.", work:"Una idea joven necesita aprendizaje y experimentación.", money:"Investigar antes de convertir el entusiasmo en gasto.", growth:"Permitirse ser principiante y aprender haciendo.", advice:"Explora con curiosidad y confirma los hechos.", reversed:"Entusiasmo inconsistente, promesa vacía o inmadurez." },
  { name:"Caballero", en:"Knight", keys:["impulso","aventura","acción"], general:"La energía empuja a avanzar con rapidez, pasión y riesgo.", love:"La atracción es intensa, pero la constancia todavía debe demostrarse.", work:"Una iniciativa audaz puede abrir camino si no ignora los detalles.", money:"Evitar inversiones impulsivas o apuestas movidas por emoción.", growth:"Canalizar intensidad sin quemar etapas.", advice:"Avanza con energía, pero define límites.", reversed:"Imprudencia, inconstancia o acción agresiva." },
  { name:"Reina", en:"Queen", keys:["confianza","creatividad","autonomía"], general:"La seguridad personal y la calidez permiten influir sin imponerse.", love:"La atracción crece con autenticidad, independencia y afecto directo.", work:"El liderazgo creativo moviliza a otros.", money:"Administrar con confianza sin caer en gastos por imagen.", growth:"Ocupar espacio sin pedir disculpas por la propia fuerza.", advice:"Actúa con calidez y seguridad.", reversed:"Celos, inseguridad oculta o necesidad de atención." },
  { name:"Rey", en:"King", keys:["visión","liderazgo","expansión"], general:"Una visión amplia necesita dirección firme y capacidad para movilizar recursos.", love:"El compromiso se demuestra con iniciativa y protección sin control.", work:"Liderar con estrategia convierte la ambición en resultados.", money:"Expandir sólo cuando exista un plan y capacidad de ejecución.", growth:"Aprender a dirigir la energía con madurez.", advice:"Define la visión y hazte responsable de ejecutarla.", reversed:"Autoritarismo, impulsividad o visión sin seguimiento." },
];

const cups: MinorSeed[] = [
  { name:"As", en:"Ace", keys:["apertura","emoción","vínculo"], general:"Se abre una corriente emocional capaz de renovar la experiencia.", love:"Hay espacio para un sentimiento nuevo o una reconciliación sincera.", work:"La motivación vuelve cuando el trabajo conecta con algo significativo.", money:"Una decisión favorable nace de mayor tranquilidad, no de euforia.", growth:"Permitir sentir sin desbordarse.", advice:"Recibe la emoción y dale una forma honesta.", reversed:"Bloqueo afectivo, emoción contenida o desborde." },
  { name:"Dos", en:"Two", keys:["encuentro","reciprocidad","acuerdo"], general:"Dos partes pueden encontrarse desde el respeto mutuo.", love:"Reciprocidad y conversación de igual a igual.", work:"Una alianza puede ser productiva.", money:"El acuerdo necesita términos claros.", growth:"Aprender a recibir y ofrecer.", advice:"Busca reciprocidad, no adivinación mental.", reversed:"Desequilibrio, ruptura o expectativas distintas." },
  { name:"Tres", en:"Three", keys:["celebración","amistad","comunidad"], general:"El apoyo compartido aligera la situación y permite celebrar un avance.", love:"Amistad, alegría y vida social fortalecen el vínculo; cuida interferencias.", work:"La colaboración mejora el resultado del equipo.", money:"Compartir un logro es positivo si el gasto se mantiene proporcionado.", growth:"Aceptar apoyo y pertenencia.", advice:"Celebra con quienes han contribuido.", reversed:"Exceso, chismes, aislamiento o una tercera influencia incómoda." },
  { name:"Cuatro", en:"Four", keys:["apatía","pausa","evaluación"], general:"La insatisfacción impide ver una opción que ya está disponible.", love:"El vínculo puede haberse vuelto rutinario o emocionalmente distante.", work:"La desmotivación exige revisar qué ya no conecta contigo.", money:"No rechazar una alternativa útil sólo por cansancio.", growth:"Distinguir descanso de desconexión.", advice:"Mira de nuevo lo que estás descartando.", reversed:"Renovación del interés, salida de la apatía o inquietud creciente." },
  { name:"Cinco", en:"Five", keys:["pérdida","duelo","decepción"], general:"La atención está concentrada en lo perdido, aunque no todo se haya acabado.", love:"Una decepción necesita duelo antes de intentar reparar o sustituir.", work:"Un revés duele, pero quedan recursos y opciones por recuperar.", money:"Asumir la pérdida con realismo y proteger lo que permanece.", growth:"Dar lugar al dolor sin convertirlo en identidad.", advice:"Reconoce la pérdida y cuenta también lo que sigue en pie.", reversed:"Aceptación gradual, duelo estancado o dificultad para perdonar." },
  { name:"Seis", en:"Six", keys:["nostalgia","memoria","generosidad"], general:"El pasado vuelve como recuerdo, influencia o posibilidad de reencuentro.", love:"Una historia anterior puede aportar ternura o repetir una idealización.", work:"Experiencia antigua o un contacto previo vuelve a ser útil.", money:"Un apoyo conocido puede ayudar, pero no debe crear dependencia.", growth:"Honrar la historia sin vivir dentro de ella.", advice:"Recupera lo valioso del pasado y deja lo que ya no corresponde.", reversed:"Idealización del pasado, madurez forzada o dificultad para avanzar." },
  { name:"Siete", en:"Seven", keys:["opciones","fantasía","confusión"], general:"Hay muchas posibilidades, pero no todas son reales, convenientes o compatibles.", love:"La idealización o las alternativas difusas dificultan un compromiso claro.", work:"Conviene separar oportunidades concretas de promesas atractivas.", money:"Evitar esquemas poco claros y decisiones basadas en ilusión.", growth:"Elegir desde valores en lugar de perseguir cada deseo.", advice:"Reduce las opciones y verifica cada una.", reversed:"Claridad después de la confusión o elección hecha por presión." },
  { name:"Ocho", en:"Eight", keys:["retirada","búsqueda","cambio"], general:"Algo ya no satisface y requiere alejarse para buscar una dirección más verdadera.", love:"Puede ser necesario tomar distancia de una dinámica emocional agotada.", work:"Dejar un proyecto sin sentido abre la búsqueda de algo más coherente.", money:"Salir de una inversión o hábito que ya no compensa.", growth:"Tener el valor de dejar atrás una falsa seguridad.", advice:"Reconoce qué ya cumplió su ciclo y retírate con claridad.", reversed:"Miedo a marcharse, retorno a lo conocido o abandono prematuro." },
  { name:"Nueve", en:"Nine", keys:["satisfacción","deseo","bienestar"], general:"Un deseo puede cumplirse y traer una satisfacción tangible.", love:"Hay disfrute y apertura afectiva, pero evita dar por sentada la reciprocidad.", work:"Un resultado favorable permite disfrutar lo conseguido.", money:"La comodidad aumenta si el gasto no busca impresionar.", growth:"Agradecer sin confundir placer con plenitud total.", advice:"Disfruta el resultado y mantén medida.", reversed:"Insatisfacción, exceso o deseo cumplido que no llena." },
  { name:"Diez", en:"Ten", keys:["armonía","familia","plenitud"], general:"La estabilidad emocional se construye mediante vínculos y valores compartidos.", love:"La relación tiene potencial de armonía, hogar y compromiso duradero.", work:"Un ambiente colaborativo favorece estabilidad y pertenencia.", money:"La seguridad mejora cuando las decisiones consideran al conjunto.", growth:"Construir una felicidad que pueda compartirse.", advice:"Protege la armonía con acuerdos cotidianos.", reversed:"Conflicto familiar, expectativas irreales o armonía aparente." },
  { name:"Sota", en:"Page", keys:["sensibilidad","mensaje","intuición"], general:"Un mensaje emocional o una intuición abre una conversación delicada.", love:"Puede surgir una declaración, disculpa o interés todavía inmaduro.", work:"La creatividad y la sensibilidad aportan una idea distinta.", money:"No convertir una corazonada en decisión financiera sin comprobarla.", growth:"Escuchar la sensibilidad y aprender a expresarla.", advice:"Habla con sencillez y mantén los pies en la tierra.", reversed:"Inmadurez emocional, mensaje confuso o fantasía evasiva." },
  { name:"Caballero", en:"Knight", keys:["oferta","romance","idealismo"], general:"Una invitación o propuesta llega movida por emoción e idealismo.", love:"Aparece un gesto romántico; su valor dependerá de la constancia posterior.", work:"Una propuesta creativa inspira, pero necesita condiciones claras.", money:"No aceptar una oferta sólo porque suena atractiva.", growth:"Seguir el corazón sin abandonar el criterio.", advice:"Recibe la propuesta y verifica si puede sostenerse.", reversed:"Promesas sin hechos, idealización o manipulación emocional." },
  { name:"Reina", en:"Queen", keys:["empatía","intuición","cuidado"], general:"La sensibilidad madura permite comprender sin absorberlo todo.", love:"Escuchar con empatía fortalece el vínculo, siempre que existan límites.", work:"La intuición social ayuda a leer el ambiente y acompañar al equipo.", money:"Evitar decisiones económicas motivadas por culpa o rescate.", growth:"Cuidar a otros sin abandonarse.", advice:"Escucha profundamente y conserva tus límites.", reversed:"Dependencia emocional, sensibilidad desbordada o autoabandono." },
  { name:"Rey", en:"King", keys:["madurez","equilibrio","diplomacia"], general:"Las emociones pueden dirigirse con serenidad, criterio y compasión.", love:"La estabilidad afectiva se demuestra con presencia y comunicación madura.", work:"Mediar con calma ayuda a resolver una tensión.", money:"Mantener la serenidad evita decisiones reactivas.", growth:"Sentir intensamente sin perder gobierno propio.", advice:"Responde con calma y claridad emocional.", reversed:"Frialdad, manipulación emocional o sentimientos mal regulados." },
];

const swords: MinorSeed[] = [
  { name:"As", en:"Ace", keys:["claridad","verdad","decisión"], general:"Una idea clara corta la confusión y permite decidir.", love:"Una conversación franca puede ordenar el vínculo.", work:"Definir el problema con precisión abre una solución.", money:"Los datos deben pesar más que la presión o el miedo.", growth:"Nombrar la verdad propia aunque resulte incómoda.", advice:"Formula con claridad lo esencial.", reversed:"Confusión, juicio equivocado o palabra hiriente." },
  { name:"Dos", en:"Two", keys:["indecisión","bloqueo","equilibrio"], general:"Dos opciones se mantienen en tensión y la decisión está aplazada.", love:"Evitar una conversación no resuelve la diferencia entre ambos.", work:"Falta un dato o un criterio para elegir entre alternativas.", money:"No comprometer recursos mientras la decisión siga bloqueada.", growth:"Reconocer qué verdad estás evitando.", advice:"Retira la venda: define el criterio y decide.", reversed:"Sobrecarga de información, decisión forzada o verdad que ya no puede evitarse." },
  { name:"Tres", en:"Three", keys:["dolor","separación","verdad"], general:"Una verdad dolorosa, pérdida o separación necesita ser reconocida sin adornos.", love:"Hay herida, distancia o palabras que han afectado la confianza.", work:"Una decepción profesional exige separar el dolor de la siguiente decisión.", money:"Una pérdida o gasto inesperado obliga a corregir el plan.", growth:"Procesar el dolor sin prolongarlo mediante la negación.", advice:"Nombra la herida y evita tomar represalias desde ella.", reversed:"Dolor en recuperación, resentimiento retenido o dificultad para cerrar." },
  { name:"Cuatro", en:"Four", keys:["descanso","pausa","recuperación"], general:"La mente y el cuerpo necesitan una pausa antes de continuar.", love:"Tomar espacio con acuerdos claros puede evitar una discusión inútil.", work:"El rendimiento mejorará después de una recuperación real.", money:"Conviene suspender movimientos y revisar con calma.", growth:"Aceptar que descansar también forma parte del proceso.", advice:"Detén la actividad suficiente para recuperar claridad.", reversed:"Agotamiento, descanso interrumpido o regreso prematuro a la presión." },
  { name:"Cinco", en:"Five", keys:["conflicto","tensión","victoria"], general:"Ganar la discusión puede dejar una pérdida mayor en la relación o el entorno.", love:"El orgullo, la hostilidad o la necesidad de imponerse dañan el vínculo.", work:"Una competencia agresiva puede producir una victoria costosa.", money:"Evitar acuerdos donde una ventaja inmediata destruya confianza futura.", growth:"Distinguir defenderse de humillar o vengarse.", advice:"Pregúntate qué quedará después de ganar.", reversed:"Deseo de reconciliar, resentimiento persistente o conflicto que vuelve." },
  { name:"Seis", en:"Six", keys:["transición","distancia","cambio"], general:"La situación se mueve desde una dificultad hacia aguas más manejables.", love:"Tomar distancia o cambiar la dinámica puede reducir el conflicto.", work:"Una transición, traslado o cambio de método facilita el avance.", money:"Mover recursos hacia una opción más segura puede ser prudente.", growth:"Aceptar que avanzar también implica dejar algo atrás.", advice:"Cruza la transición con un plan y sin mirar atrás a cada paso.", reversed:"Equipaje emocional, transición detenida o regreso a un problema anterior." },
  { name:"Siete", en:"Seven", keys:["estrategia","engaño","prudencia"], general:"La situación exige estrategia, pero también revisar ocultamientos, evasiones o ventajas indebidas.", love:"Puede haber información omitida, evasión de compromiso o falta de transparencia.", work:"Planear con discreción es útil; actuar sin ética tendrá consecuencias.", money:"Cuidado con fraudes, cargos ocultos o decisiones financieras no informadas.", growth:"Observar dónde la astucia se está convirtiendo en autoengaño.", advice:"Protege tu estrategia y verifica la honestidad de todos, incluida la propia.", reversed:"Engaño descubierto, confesión, mala estrategia o autoengaño evidente." },
  { name:"Ocho", en:"Eight", keys:["restricción","miedo","bloqueo"], general:"La sensación de no tener salida es mayor que la restricción objetiva.", love:"El miedo o la culpa dificultan expresar límites y alternativas.", work:"Una creencia limitante impide usar opciones que sí existen.", money:"La ansiedad reduce la capacidad de ver soluciones prácticas.", growth:"Identificar la regla interna que te mantiene inmóvil.", advice:"Comprueba qué límite es real y cuál estás suponiendo.", reversed:"Liberación, nueva perspectiva o miedo que sigue controlando." },
  { name:"Nueve", en:"Nine", keys:["ansiedad","miedo","preocupación"], general:"La mente repite escenarios dolorosos y puede estar amplificando el peligro.", love:"La preocupación, culpa o desconfianza necesitan hablarse con hechos.", work:"El estrés está afectando descanso y capacidad de decidir.", money:"Evitar decisiones nocturnas o impulsivas nacidas de ansiedad.", growth:"Pedir apoyo y diferenciar pensamiento de realidad.", advice:"Contrasta tus temores y atiende el descanso.", reversed:"Ansiedad que disminuye, vergüenza profunda o preocupación que se niega." },
  { name:"Diez", en:"Ten", keys:["final","dolor","cierre"], general:"Una situación difícil llega a un final claro; insistir ya no la recuperará.", love:"El vínculo o una forma de relacionarse ha alcanzado un límite decisivo.", work:"Un proyecto, puesto o estrategia termina y exige reorganización.", money:"Reconocer una pérdida evita seguir destinando recursos a lo irrecuperable.", growth:"Aceptar el final para dejar de prolongar el daño.", advice:"Cierra, protege lo que queda y comienza a recuperarte.", reversed:"Recuperación lenta, resistencia al final o repetición de la herida." },
  { name:"Sota", en:"Page", keys:["vigilancia","curiosidad","mensaje"], general:"Hay que observar, preguntar y reunir información antes de concluir.", love:"La curiosidad puede abrir diálogo, pero vigilar o suponer dañará la confianza.", work:"Una idea nueva requiere investigación y comunicación precisa.", money:"Leer contratos y verificar fuentes antes de actuar.", growth:"Aprender a preguntar sin convertir la mente en sospecha permanente.", advice:"Investiga y habla con precisión.", reversed:"Rumor, espionaje, información incompleta o comunicación inmadura." },
  { name:"Caballero", en:"Knight", keys:["velocidad","determinación","confrontación"], general:"La acción es rápida y directa, pero puede atropellar matices y personas.", love:"Una conversación frontal aclara, aunque el tono puede volverla pelea.", work:"La determinación rompe la demora si se acompaña de estrategia.", money:"No mover recursos con prisa ni por competir.", growth:"Aprender a unir valentía intelectual con escucha.", advice:"Avanza con decisión y controla la agresividad.", reversed:"Impulsividad, ataque verbal o plan ejecutado sin preparación." },
  { name:"Reina", en:"Queen", keys:["discernimiento","independencia","límites"], general:"La experiencia permite ver con claridad y separar hechos de excusas.", love:"Se necesitan honestidad, autonomía y límites respetados.", work:"El análisis objetivo ayuda a tomar una decisión difícil.", money:"Cortar gastos o acuerdos que no resisten una revisión racional.", growth:"Usar la lucidez sin volverla dureza.", advice:"Sé directa, justa y precisa.", reversed:"Amargura, juicio cruel o límites usados como muro." },
  { name:"Rey", en:"King", keys:["razón","autoridad","verdad"], general:"La decisión requiere lógica, experiencia y aplicación imparcial de criterios.", love:"La claridad es necesaria, pero no debe sustituir la sensibilidad.", work:"Una autoridad técnica o legal puede ordenar la situación.", money:"Tomar decisiones basadas en reglas, evidencia y horizonte largo.", growth:"Gobernar el pensamiento sin desconectarlo de la humanidad.", advice:"Define el criterio y aplícalo con integridad.", reversed:"Abuso de autoridad, frialdad o manipulación de la verdad." },
];

const pentacles: MinorSeed[] = [
  { name:"As", en:"Ace", keys:["oportunidad","recursos","inicio"], general:"Aparece una oportunidad concreta de estabilidad, trabajo o crecimiento material.", love:"El vínculo puede construir una base más estable mediante hechos.", work:"Una oferta o proyecto tiene potencial práctico.", money:"Existe una posibilidad real de ingreso, ahorro o inversión.", growth:"Convertir una intención en algo tangible.", advice:"Evalúa la oportunidad y establece una base sólida.", reversed:"Oportunidad perdida, mala planificación o inversión insegura." },
  { name:"Dos", en:"Two", keys:["equilibrio","adaptación","recursos"], general:"Varias responsabilidades compiten y requieren ajuste continuo.", love:"Equilibrar tiempos y prioridades evita que el vínculo quede al final.", work:"La carga es manejable si se ordenan plazos y tareas.", money:"Administrar entradas y salidas con flexibilidad.", growth:"Aprender a adaptarse sin vivir permanentemente al límite.", advice:"Prioriza y deja margen para cambios.", reversed:"Desorganización, sobrecarga o desequilibrio financiero." },
  { name:"Tres", en:"Three", keys:["colaboración","habilidad","construcción"], general:"El resultado mejora cuando la habilidad individual se integra con un equipo competente.", love:"Construir juntos requiere escuchar aportes y repartir responsabilidades.", work:"La colaboración y la calidad técnica reciben reconocimiento.", money:"Un proyecto bien coordinado puede generar valor estable.", growth:"Aceptar evaluación y aprender de otros.", advice:"Trabaja con personas que complementen tu capacidad.", reversed:"Mala coordinación, trabajo mediocre o falta de reconocimiento." },
  { name:"Cuatro", en:"Four", keys:["control","seguridad","apego"], general:"Proteger recursos da estabilidad, pero el control excesivo impide que circulen.", love:"El miedo a perder puede volverse posesividad o cierre emocional.", work:"Conservar una posición es razonable si no bloquea toda innovación.", money:"Ahorrar es útil; retener por miedo puede impedir una decisión productiva.", growth:"Distinguir seguridad de apego.", advice:"Protege lo esencial y flexibiliza lo demás.", reversed:"Avaricia, pérdida de control o apertura financiera imprudente." },
  { name:"Cinco", en:"Five", keys:["carencia","dificultad","apoyo"], general:"Una etapa de escasez o exclusión pesa, pero el apoyo disponible puede no estar siendo visto.", love:"Las dificultades pueden aislar a la pareja si no se pide ayuda.", work:"La inseguridad laboral exige apoyo, información y un plan práctico.", money:"Priorizar necesidades básicas y buscar recursos concretos.", growth:"Pedir ayuda sin convertir la dificultad en identidad.", advice:"No enfrentes la carencia a solas; identifica apoyo real.", reversed:"Recuperación material, ayuda recibida o mentalidad de escasez persistente." },
  { name:"Seis", en:"Six", keys:["generosidad","equidad","intercambio"], general:"Dar y recibir deben mantenerse en una relación justa y transparente.", love:"El vínculo necesita reciprocidad, no deuda emocional.", work:"Apoyo, pago o mentoría funcionan si no crean dependencia.", money:"Puede haber ayuda, crédito o reparto; revisa las condiciones.", growth:"Dar con límites y recibir sin vergüenza.", advice:"Comprueba que el intercambio sea justo.", reversed:"Deuda, ayuda condicionada, desigualdad o generosidad interesada." },
  { name:"Siete", en:"Seven", keys:["paciencia","evaluación","cosecha"], general:"El trabajo ya está sembrado; toca evaluar si el rendimiento justifica seguir.", love:"La relación necesita paciencia y una revisión honesta de lo construido.", work:"Los resultados tardan; conviene medir avances antes de abandonar.", money:"Una inversión requiere tiempo, pero también criterios de salida.", growth:"Aprender a esperar sin dejar de evaluar.", advice:"Mide el progreso y ajusta antes de invertir más.", reversed:"Impaciencia, poco rendimiento o esfuerzo sostenido en la dirección equivocada." },
  { name:"Ocho", en:"Eight", keys:["práctica","detalle","maestría"], general:"El progreso nace de la práctica atenta y repetida.", love:"Cuidar el vínculo con acciones sostenidas.", work:"Perfeccionar una habilidad valiosa.", money:"Mejorar mediante disciplina y oficio.", growth:"Convertir intención en hábito.", advice:"Haz bien la siguiente repetición.", reversed:"Perfeccionismo, trabajo mecánico o baja calidad." },
  { name:"Nueve", en:"Nine", keys:["autonomía","abundancia","resultado"], general:"La disciplina previa permite disfrutar independencia y resultados propios.", love:"La autonomía fortalece el vínculo cuando no se usa para mantener distancia.", work:"La experiencia produce una posición sólida y autosuficiente.", money:"Hay estabilidad para disfrutar, ahorrar o consolidar patrimonio.", growth:"Reconocer el valor de lo construido por uno mismo.", advice:"Disfruta el resultado sin abandonar la prudencia.", reversed:"Dependencia, gasto por apariencia o éxito sostenido por una base frágil." },
  { name:"Diez", en:"Ten", keys:["legado","estabilidad","familia"], general:"Los recursos, la experiencia y la estructura pueden sostener algo duradero.", love:"El vínculo se relaciona con familia, hogar y compromiso de largo plazo.", work:"Una organización consolidada ofrece continuidad y responsabilidades nuevas.", money:"Patrimonio, herencia o seguridad familiar requieren buena administración.", growth:"Pensar más allá del beneficio inmediato.", advice:"Construye para durar y deja reglas claras.", reversed:"Conflicto por patrimonio, inestabilidad familiar o éxito sin continuidad." },
  { name:"Sota", en:"Page", keys:["aprendizaje","oportunidad","estudio"], general:"Una oportunidad práctica pide estudio, atención y disposición de principiante.", love:"El interés se demuestra con gestos sencillos y constantes.", work:"Un curso, oficio o tarea nueva puede abrir desarrollo profesional.", money:"Empezar a ahorrar o aprender sobre una inversión con prudencia.", growth:"Convertir curiosidad en competencia.", advice:"Estudia la oportunidad y trabaja sus fundamentos.", reversed:"Falta de enfoque, oportunidad desaprovechada o aprendizaje superficial." },
  { name:"Caballero", en:"Knight", keys:["constancia","responsabilidad","trabajo"], general:"El avance es lento, confiable y depende de cumplir cada paso.", love:"La lealtad se demuestra mediante presencia y hechos repetidos.", work:"La disciplina y la rutina producen resultados sólidos.", money:"Seguir el plan y evitar atajos protege la estabilidad.", growth:"Aprender el valor del esfuerzo sostenido.", advice:"Cumple lo acordado y mantén el ritmo.", reversed:"Estancamiento, rutina sin propósito o irresponsabilidad práctica." },
  { name:"Reina", en:"Queen", keys:["practicidad","cuidado","abundancia"], general:"La capacidad de cuidar y administrar crea un entorno estable y fértil.", love:"El afecto se expresa con presencia, seguridad y apoyo concreto.", work:"Organización y sentido práctico mantienen el proyecto funcionando.", money:"Administrar bien permite cuidar necesidades actuales y futuras.", growth:"Unir autocuidado con responsabilidad material.", advice:"Haz que el bienestar tenga una base concreta.", reversed:"Autoabandono, materialismo o cuidado que se vuelve control." },
  { name:"Rey", en:"King", keys:["solidez","dominio","prosperidad"], general:"La experiencia permite administrar recursos con autoridad y visión de largo plazo.", love:"La estabilidad se demuestra con compromiso, protección y confiabilidad.", work:"La gestión competente convierte el esfuerzo en resultados sostenibles.", money:"Hay capacidad para consolidar patrimonio si se evita la complacencia.", growth:"Usar el éxito con responsabilidad.", advice:"Administra para el largo plazo y cumple tu palabra.", reversed:"Avaricia, abuso de poder material o mala administración." },
];

const majors: RiderCard[] = majorSeeds.map((card) => {
  const padded = String(card.number).padStart(2, "0");
  return {
    ...card,
    id: padded,
    arcana: "Mayor",
    suit: null,
    image: `/cards/rws/${majorImages[card.number] ?? `major-${padded}.jpg`}`,
  };
});

const suitDefinitions = [
  { suit:"Bastos" as const, en:"Wands", slug:"wands", symbols:"Bastos, brotes, paisaje.", cards:wands },
  { suit:"Copas" as const, en:"Cups", slug:"cups", symbols:"Copas, agua, vínculos.", cards:cups },
  { suit:"Espadas" as const, en:"Swords", slug:"swords", symbols:"Espadas, cielo, pensamiento.", cards:swords },
  { suit:"Oros" as const, en:"Pentacles", slug:"pentacles", symbols:"Pentáculos, tierra, recursos.", cards:pentacles },
];

const minors: RiderCard[] = suitDefinitions.flatMap((definition) => definition.cards.map((card, index) => {
  const number = index + 1;
  const padded = String(number).padStart(2, "0");
  const id = definition.suit === "Espadas" && number === 1 ? "sw-ace"
    : definition.suit === "Copas" && number === 2 ? "cu-2"
    : definition.suit === "Oros" && number === 8 ? "pe-8"
    : `${definition.slug}-${padded}`;
  return {
    ...card,
    id,
    name: `${ranks[index]} de ${definition.suit}`,
    en: `${englishRanks[index]} of ${definition.en}`,
    arcana: "Menor",
    suit: definition.suit,
    number,
    symbols: definition.symbols,
    image: `/cards/rws/${definition.slug}-${padded}.jpg`,
  };
}));

export const riderDeck: RiderCard[] = [...majors, ...minors];
